In [1]:
import pandas as pd
from IPython.display import Image
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from pydna.dseqrecord import Dseqrecord

In [2]:
a_oryzae ={
    'F': {'TTT': 0.38, 'TTC': 0.62},
    'S': {'TCT': 0.18, 'TCC': 0.20, 'TCA': 0.14, 'TCG': 0.16, 'AGT': 0.13, 'AGC': 0.18},
    'Y': {'TAT': 0.47, 'TAC': 0.53},
    'C': {'TGT': 0.46, 'TGC': 0.54},
    '*': {'TAA': 0.33, 'TAG': 0.29, 'TGA': 0.38},
    'L': {'TTA': 0.07, 'TTG': 0.18, 'CTT': 0.19, 'CTC': 0.23, 'CTA': 0.11, 'CTG': 0.22},
    'W': {'TGG': 1.00},
    'P': {'CCT': 0.27, 'CCC': 0.26, 'CCA': 0.25, 'CCG': 0.22},
    'H': {'CAT': 0.53, 'CAC': 0.47},
    'Q': {'CAA': 0.43, 'CAG': 0.57},
    'R': {'CGT': 0.18, 'CGC': 0.23, 'CGA': 0.17, 'CGG': 0.18, 'AGA': 0.13, 'AGG': 0.12},
    'I': {'ATT': 0.36, 'ATC': 0.50, 'ATA': 0.14},
    'M': {'ATG': 1.00},
    'T': {'ACT': 0.24, 'ACC': 0.32, 'ACA': 0.23, 'ACG': 0.20},
    'N': {'AAT': 0.45, 'AAC': 0.55},
    'K': {'AAA': 0.36, 'AAG': 0.64},
    'V': {'GTT': 0.27, 'GTC': 0.33, 'GTA': 0.13, 'GTG': 0.27},
    'A': {'GCT': 0.27, 'GCC': 0.30, 'GCA': 0.23, 'GCG': 0.20},
    'D': {'GAT': 0.53, 'GAC': 0.47},
    'E': {'GAA': 0.44, 'GAG': 0.56},
    'G': {'GGT': 0.28, 'GGC': 0.31, 'GGA': 0.24, 'GGG': 0.17}
}

### SPs

In [3]:
sp_df = pd.read_csv('../data/15_SecretoGen/Best_signal_peptides_for_A_oryzae_RFP_his_tag_sorted.csv')
sp_df = sp_df.rename(columns={"SP_ID": "SecretoGen_ID"})

sp_df

    SecretoGen_ID                  Sequence  Perplexity
0          SP_997       MRPTLLALGVISFALTLHS    7.515804
1          SP_944   MKFTLIILIIVILTIIFSPGALA    7.421489
2          SP_948  MKVTLSLLAVFLAALSASAIPANG    7.179219
3          SP_993      MKAIIILLLIILTLALTVQG    7.140379
4          SP_204    MRVFSATAILALSPLLIASASP    6.925975
..            ...                       ...         ...
995        SP_656      MVLGILTITAIPTVTGLANA    1.597785
996        SP_696      MVLGLLTIAAIPTVTGVAQA    1.563614
997        SP_757   MVLGLLTIAAIPTVTGVGNAVSA    1.554127
998        SP_253      MVLGILTITAIPTVTGVAQA    1.535361
999         SP_13      MVLGILTITAIPTVTGVANA    1.530345

[1000 rows x 3 columns]

In [4]:
sp_df

    SecretoGen_ID                  Sequence  Perplexity
0          SP_997       MRPTLLALGVISFALTLHS    7.515804
1          SP_944   MKFTLIILIIVILTIIFSPGALA    7.421489
2          SP_948  MKVTLSLLAVFLAALSASAIPANG    7.179219
3          SP_993      MKAIIILLLIILTLALTVQG    7.140379
4          SP_204    MRVFSATAILALSPLLIASASP    6.925975
..            ...                       ...         ...
995        SP_656      MVLGILTITAIPTVTGLANA    1.597785
996        SP_696      MVLGLLTIAAIPTVTGVAQA    1.563614
997        SP_757   MVLGLLTIAAIPTVTGVGNAVSA    1.554127
998        SP_253      MVLGILTITAIPTVTGVAQA    1.535361
999         SP_13      MVLGILTITAIPTVTGVANA    1.530345

[1000 rows x 3 columns]

In [5]:
# Adding the length of sequences to the dataframe
sp_df['Length'] = sp_df['Sequence'].apply(len)

# Removing sequences with length over 26
filtered_df = sp_df[sp_df['Length'] <= 26]
filtered_df

    SecretoGen_ID                  Sequence  Perplexity  Length
0          SP_997       MRPTLLALGVISFALTLHS    7.515804      19
1          SP_944   MKFTLIILIIVILTIIFSPGALA    7.421489      23
2          SP_948  MKVTLSLLAVFLAALSASAIPANG    7.179219      24
3          SP_993      MKAIIILLLIILTLALTVQG    7.140379      20
4          SP_204    MRVFSATAILALSPLLIASASP    6.925975      22
..            ...                       ...         ...     ...
995        SP_656      MVLGILTITAIPTVTGLANA    1.597785      20
996        SP_696      MVLGLLTIAAIPTVTGVAQA    1.563614      20
997        SP_757   MVLGLLTIAAIPTVTGVGNAVSA    1.554127      23
998        SP_253      MVLGILTITAIPTVTGVAQA    1.535361      20
999         SP_13      MVLGILTITAIPTVTGVANA    1.530345      20

[998 rows x 4 columns]

In [6]:

# Getting the top 30
top_30 = sp_df.head(30)

# Sampling the remaining dataframe for a good mix
remaining_sample_size = 84 - 30
remaining_sample = sp_df.iloc[30:].sample(n=remaining_sample_size, random_state=1)

# Combining the top 30 with the remaining sample
final_sample = pd.concat([top_30, remaining_sample]).reset_index(drop=True)
final_sample

   SecretoGen_ID                  Sequence  Perplexity  Length
0         SP_997       MRPTLLALGVISFALTLHS    7.515804      19
1         SP_944   MKFTLIILIIVILTIIFSPGALA    7.421489      23
2         SP_948  MKVTLSLLAVFLAALSASAIPANG    7.179219      24
3         SP_993      MKAIIILLLIILTLALTVQG    7.140379      20
4         SP_204    MRVFSATAILALSPLLIASASP    6.925975      22
..           ...                       ...         ...     ...
79        SP_952      MRVSTIPTALLGLSLSAVNA    3.271387      20
80        SP_659     MVRLNSITALASLLAVSLTAA    3.640410      21
81        SP_576  MILSYRSLVVTTVALLGLSTPATA    3.873739      24
82        SP_560     MVLLKPLLATALLASLTPAVA    3.045672      21
83        SP_256    MVHLKTLALAVSALLTPSIVSA    3.073488      22

[84 rows x 4 columns]

# Back-translate

In [7]:
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio import SeqIO
from pydna.dseq import Dseq

# Simplified back-translation codon table
back_translation_code = {
        'A': ['GCA', 'GCC', 'GCG', 'GCT'],
        'C': ['TGT', 'TGC'],
        'D': ['GAC', 'GAT'],
        'E': ['GAG', 'GAA'],
        'F': ['TTT', 'TTC'],
        'G': ['GGT', 'GGG', 'GGA', 'GGC'],
        'H': ['CAT', 'CAC'],
        'I': ['ATC', 'ATA', 'ATT'],
        'K': ['AAG', 'AAA'],
        'L': ['CTT', 'CTG', 'CTA', 'CTC', 'TTA', 'TTG'],
        'M': ['ATG'],
        'N': ['AAC', 'AAT'],
        'P': ['CCT', 'CCG', 'CCA', 'CCC'],
        'Q': ['CAA', 'CAG'],
        'R': ['AGG', 'AGA', 'CGA', 'CGC', 'CGG', 'CGT'],
        'S': ['AGC', 'AGT', 'TCT', 'TCG', 'TCC', 'TCA'],
        'T': ['ACA', 'ACG', 'ACT', 'ACC'],
        'V': ['GTA', 'GTC', 'GTG', 'GTT'],
        'W': ['TGG'],
        'Y': ['TAT', 'TAC'],
        '*': ['TAA', 'TGA', 'TAG']
    }


def back_translate(protein_sequence):
    return ''.join([back_translation_code[aa][0] for aa in protein_sequence])

In [8]:

seq_records = []
for index, row in final_sample.iterrows():
    dna_sequence = back_translate(row['Sequence'])
    dseq_obj = Dseq(dna_sequence)
    dseqrecord = Dseqrecord(dseq_obj, name=row['SecretoGen_ID'], description=f"Perplexity: {row['Perplexity']}, Length: {row['Length']}")
    seq_records.append(dseqrecord)

seq_records

[Dseqrecord(-57),
 Dseqrecord(-69),
 Dseqrecord(-72),
 Dseqrecord(-60),
 Dseqrecord(-66),
 Dseqrecord(-57),
 Dseqrecord(-69),
 Dseqrecord(-60),
 Dseqrecord(-60),
 Dseqrecord(-75),
 Dseqrecord(-66),
 Dseqrecord(-63),
 Dseqrecord(-54),
 Dseqrecord(-51),
 Dseqrecord(-66),
 Dseqrecord(-57),
 Dseqrecord(-63),
 Dseqrecord(-63),
 Dseqrecord(-57),
 Dseqrecord(-51),
 Dseqrecord(-57),
 Dseqrecord(-84),
 Dseqrecord(-66),
 Dseqrecord(-54),
 Dseqrecord(-60),
 Dseqrecord(-63),
 Dseqrecord(-57),
 Dseqrecord(-54),
 Dseqrecord(-60),
 Dseqrecord(-60),
 Dseqrecord(-66),
 Dseqrecord(-57),
 Dseqrecord(-57),
 Dseqrecord(-63),
 Dseqrecord(-72),
 Dseqrecord(-66),
 Dseqrecord(-51),
 Dseqrecord(-63),
 Dseqrecord(-63),
 Dseqrecord(-63),
 Dseqrecord(-54),
 Dseqrecord(-60),
 Dseqrecord(-66),
 Dseqrecord(-60),
 Dseqrecord(-72),
 Dseqrecord(-60),
 Dseqrecord(-63),
 Dseqrecord(-66),
 Dseqrecord(-57),
 Dseqrecord(-60),
 Dseqrecord(-60),
 Dseqrecord(-63),
 Dseqrecord(-60),
 Dseqrecord(-63),
 Dseqrecord(-72),
 Dseqrecord(-63),
 Dseqrecord(-66),
 Dseqrecord(-57),
 Dseqrecord(-57),
 Dseqrecord(-72),
 Dseqrecord(-66),
 Dseqrecord(-63),
 Dseqrecord(-60),
 Dseqrecord(-60),
 Dseqrecord(-57),
 Dseqrecord(-66),
 Dseqrecord(-66),
 Dseqrecord(-66),
 Dseqrecord(-63),
 Dseqrecord(-60),
 Dseqrecord(-69),
 Dseqrecord(-57),
 Dseqrecord(-57),
 Dseqrecord(-66),
 Dseqrecord(-48),
 Dseqrecord(-60),
 Dseqrecord(-60),
 Dseqrecord(-54),
 Dseqrecord(-63),
 Dseqrecord(-60),
 Dseqrecord(-63),
 Dseqrecord(-72),
 Dseqrecord(-63),
 Dseqrecord(-66)]

In [9]:
print(seq_records[0].seq)

ATGAGGCCTACACTTCTTGCACTTGGTGTAATCAGCTTTGCACTTACACTTCATAGC

### Codon optimize the sequences:

A. oryzae tax id : 5062

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=5062&lvl=3&lin=f&keep=1&srchmode=1&unlock

In [10]:
from dnachisel import DnaOptimizationProblem, CodonOptimize, EnforceTranslation, EnforceGCContent

# Codon optimization for Aspergillus oryzae
codon_optimized_records = []
codon_optimized_records_str = []
taxonomy_id = 5062 # a oryzae

for seq in seq_records:
    problem = DnaOptimizationProblem(
        sequence=str(seq.seq),
        constraints=[
            EnforceGCContent(mini=0.3, maxi=0.7, window=len(seq)),
            EnforceTranslation(location=(0, len(seq)))
        ],
        #objectives=[CodonOptimize(codon_usage_table=a_oryzae, method='match_codon_usage')], 
        objectives=[CodonOptimize(species=taxonomy_id, method='match_codon_usage')], 
    )
    problem.resolve_constraints()
    
    problem.optimize()
    # PRINT SUMMARIES TO CHECK THAT CONSTRAINTS PASS
    print(problem.constraints_text_summary())
    print(problem.objectives_text_summary())

    # Save the sequences
    optimized_dna_sequence = str(problem.sequence)
    
    dseq_obj = Dseq(optimized_dna_sequence)
    dseqrecord = Dseqrecord(dseq_obj, name=row['SecretoGen_ID'], description=f"Perplexity: {row['Perplexity']}, Length: {row['Length']}")
    codon_optimized_records.append(dseqrecord)
    codon_optimized_records_str.append(str(dseqrecord.seq))
    
final_sample['codon_optimized_sequences']= codon_optimized_records_str

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -15.55
    -15.55 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.55E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-69](mini:0.30, maxi:0.70, window:69)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-69(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.87
    -12.87 ┍ MatchTargetCodonUsage[0-69](5062)
           │ Codon opt. on window 0-69 scored -1.29E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-72](mini:0.30, maxi:0.70, window:72)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-72(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -14.14
    -14.14 ┍ MatchTargetCodonUsage[0-72](5062)
           │ Codon opt. on window 0-72 scored -1.41E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -10.6
     -10.6 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.06E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.08
    -12.08 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.21E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.53
    -10.53 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.05E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-69](mini:0.30, maxi:0.70, window:69)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-69(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.45
    -12.45 ┍ MatchTargetCodonUsage[0-69](5062)
           │ Codon opt. on window 0-69 scored -1.25E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.58
    -11.58 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.66
    -13.66 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.37E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-75](mini:0.30, maxi:0.70, window:75)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-75(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.97
     -9.97 ┍ MatchTargetCodonUsage[0-75](5062)
           │ Codon opt. on window 0-75 scored -9.97E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -15.14
    -15.14 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.51E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.90
    -11.90 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.19E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-54](mini:0.30, maxi:0.70, window:54)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-54(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.66
    -11.66 ┍ MatchTargetCodonUsage[0-54](5062)
           │ Codon opt. on window 0-54 scored -1.17E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.91
    -12.91 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.29E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.97
    -12.97 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.30E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.65
    -12.65 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.26E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.63
    -12.63 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.26E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -8.74
     -8.74 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -8.74E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.88
     -9.88 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -9.88E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.12
    -13.12 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.31E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.31
    -10.31 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.03E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-84](mini:0.30, maxi:0.70, window:84)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-84(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -17.96
    -17.96 ┍ MatchTargetCodonUsage[0-84](5062)
           │ Codon opt. on window 0-84 scored -1.80E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.64
    -11.64 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-54](mini:0.30, maxi:0.70, window:54)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-54(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -7.99
     -7.99 ┍ MatchTargetCodonUsage[0-54](5062)
           │ Codon opt. on window 0-54 scored -7.99E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -14.29
    -14.29 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.43E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.08
    -13.08 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.31E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.88
    -12.88 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.29E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-54](mini:0.30, maxi:0.70, window:54)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-54(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.33
    -11.33 ┍ MatchTargetCodonUsage[0-54](5062)
           │ Codon opt. on window 0-54 scored -1.13E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.39
    -11.39 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.14E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.88
    -11.88 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.19E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.60
    -12.60 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.26E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.22
    -13.22 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.32E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.14
    -10.14 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.01E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.52
    -11.52 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.15E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-72](mini:0.30, maxi:0.70, window:72)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-72(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.80
     -9.80 ┍ MatchTargetCodonUsage[0-72](5062)
           │ Codon opt. on window 0-72 scored -9.80E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.51
    -13.51 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.35E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -13.1
     -13.1 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.31E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.56
    -11.56 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.88
    -11.88 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.19E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.93
    -11.93 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.19E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-54](mini:0.30, maxi:0.70, window:54)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-54(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.94
    -13.94 ┍ MatchTargetCodonUsage[0-54](5062)
           │ Codon opt. on window 0-54 scored -1.39E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.45
    -12.45 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.24E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.48
    -10.48 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.05E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -15.5
     -15.5 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.55E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-72](mini:0.30, maxi:0.70, window:72)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-72(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.93
    -13.93 ┍ MatchTargetCodonUsage[0-72](5062)
           │ Codon opt. on window 0-72 scored -1.39E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.19
    -13.19 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.32E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.57
    -11.57 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.34
    -11.34 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.13E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.10
     -9.10 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -9.10E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.87
    -11.87 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.19E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.44
    -12.44 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.24E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.08
    -11.08 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.11E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.63
    -11.63 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -12.1
     -12.1 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.21E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-72](mini:0.30, maxi:0.70, window:72)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-72(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.57
    -11.57 ┍ MatchTargetCodonUsage[0-72](5062)
           │ Codon opt. on window 0-72 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.77
    -11.77 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.18E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.86
    -12.86 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.29E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.79
    -10.79 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.08E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.87
    -12.87 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.29E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-72](mini:0.30, maxi:0.70, window:72)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-72(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -15.26
    -15.26 ┍ MatchTargetCodonUsage[0-72](5062)
           │ Codon opt. on window 0-72 scored -1.53E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.44
    -10.44 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.04E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.66
    -11.66 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.17E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.04
    -12.04 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.20E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.30
     -9.30 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -9.30E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -8.19
     -8.19 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -8.19E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.42
     -9.42 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -9.42E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.11
    -13.11 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.31E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.77
    -13.77 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.38E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.37
    -11.37 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.14E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.15
    -12.15 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.21E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-69](mini:0.30, maxi:0.70, window:69)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-69(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.60
    -11.60 ┍ MatchTargetCodonUsage[0-69](5062)
           │ Codon opt. on window 0-69 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.63
    -10.63 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.06E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.39
    -11.39 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.14E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.74
    -11.74 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.17E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-48](mini:0.30, maxi:0.70, window:48)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-48(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.30
    -10.30 ┍ MatchTargetCodonUsage[0-48](5062)
           │ Codon opt. on window 0-48 scored -1.03E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.31
    -12.31 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.23E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.24
    -12.24 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.22E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-54](mini:0.30, maxi:0.70, window:54)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-54(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -14.65
    -14.65 ┍ MatchTargetCodonUsage[0-54](5062)
           │ Codon opt. on window 0-54 scored -1.47E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.28
    -11.28 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.13E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -14.88
    -14.88 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.49E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.60
    -11.60 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-72](mini:0.30, maxi:0.70, window:72)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-72(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.72
    -12.72 ┍ MatchTargetCodonUsage[0-72](5062)
           │ Codon opt. on window 0-72 scored -1.27E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.69
    -10.69 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.07E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.01
    -11.01 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.10E+01

## Final sample with sp_name

In [11]:
final_sample['sp_name'] = [f'SP_{i}' for i in range(len(final_sample['SecretoGen_ID'].to_list())) ]

In [12]:
with pd.option_context('display.max_rows', None,
                       'display.max_columns', None,
                       'display.precision', 3,
                       'display.width', None,
                       'display.max_colwidth', 1000
                       ):
    print(final_sample)

   SecretoGen_ID                      Sequence  Perplexity  Length  \
0         SP_997           MRPTLLALGVISFALTLHS       7.516      19
1         SP_944       MKFTLIILIIVILTIIFSPGALA       7.421      23
2         SP_948      MKVTLSLLAVFLAALSASAIPANG       7.179      24
3         SP_993          MKAIIILLLIILTLALTVQG       7.140      20
4         SP_204        MRVFSATAILALSPLLIASASP       6.926      22
5         SP_281           MRLVSLLTILGTAITTASA       6.789      19
6         SP_945       MRPLAITLGLATTIFNPITTASL       6.691      23
7         SP_914          MRVLGISSIILTTLVSTTLA       6.568      20
8         SP_662          MRPTSSAFVSILGFAAIATA       6.221      20
9         SP_849     MKIPFLLSAALLTTLSLFSTSTTLA       6.168      25
10        SP_337        MLTTLIQYTLLVSLLFGSPAAS       6.111      22
11        SP_249         MKTILPVLLSAITALASPAFA       6.103      21
12        SP_989            MRLFHLIVLATVLSLTIA       6.005      18
13        SP_847             MRLSAAFILGLSSTVIA       5.995      17
14        SP_549        MLPTLLRLFGLLAISLVAVAIA       5.975      22
15        SP_117           MRFSLLAVLSIALGLLVQA       5.955      19
16        SP_745         MRLITFLTTILALVLVSLCQA       5.886      21
17        SP_906         MRSFAFLLAVVLLSVVGLASA       5.863      21
18        SP_457           MRFFASLIIIASLLAATIA       5.837      19
19        SP_219             MRLSLGFILGTLTLVNA       5.741      17
20        SP_882           MKLILFTLIALSLFQLSLA       5.728      19
21        SP_410  MLSSSARWAFLLTTIIGLLLCLHNPIVA       5.683      28
22        SP_942        MLSSSVLLRIALLALLLALCVG       5.675      22
23        SP_663            MILTYFLIAALLLSLTAA       5.611      18
24        SP_502          MRSFISLVGILLTLALYVHS       5.543      20
25        SP_425         MRFTSLSALALGALVITSVAA       5.536      21
26        SP_668           MKLSNFVTTLVLSTPFASA       5.516      19
27         SP_33            MLLRYLLTVVLAVGLVLS       5.483      18
28        SP_946          MRFFSSVLTALAALTTSVVG       5.471      20
29         SP_41          MIPYTLAALVVACLSTLSLA       5.436      20
30        SP_459        MVLTKLSVLATALLGLSAQAIA       2.673      22
31        SP_811           MRPVSILATVLGLANLATA       2.846      19
32        SP_741           MVLTKSLLVLSTIAAQALA       2.589      19
33        SP_982         MILSNTILVATLAALSGLAHA       3.497      21
34        SP_472      MIFTRLIQLLCAALLLALVLQVQA       3.092      24
35         SP_97        MRSSALLTALVVLLGCISNAAA       4.877      22
36         SP_71             MRISIPLITAVLSTASA       4.322      17
37         SP_40         MVALQKLLLLTALASLSPTVA       2.655      21
38        SP_121         MVHFKALATAVLASLLSPTLA       2.521      21
39        SP_998         MLVPKLSALLLGALLPTVVSA       2.777      21
40        SP_172            MVRLGFFSLLATIPLALS       3.246      18
41        SP_297          MRFTLASLALLAIANTVVSA       4.072      20
42        SP_137        MVAIKSLLTAALAALSITPALA       2.357      22
43        SP_259          MVSIKNLALFVTTLLGCSQA       2.484      20
44         SP_20      MILSRILSATLVALALCLFNQATA       3.280      24
45        SP_412          MKTFIPFVALLSTISSLCAA       4.954      20
46        SP_227         MVHIKPLLATALAALSPLATA       2.205      21
47        SP_798        MLVKSIVSTLLALSLSSGLANA       3.848      22
48        SP_644           MVRLSLLASALLVASSTLA       3.057      19
49        SP_365          MRSLLLSVLFTVLFAILATA       4.172      20
50        SP_409          MLIRSIATLAVLGLSQTALS       3.160      20
51        SP_426         MVSQKLLSLATILALASLGQA       3.344      21
52        SP_316          MVALKHILTALLALSPLATA       2.439      20
53        SP_298         MIVTRFLSTLLLAASLSAANA       4.404      21
54        SP_653      MVLGITSKALAISLLACLSTPSTA       2.280      24
55        SP_173         MLLPTVTLLSVGLAALQPALA       3.490      21
56        SP_375        MVHIKPFATVALLASLLTPSLA       2.566      22
57          SP_1           MILRWTLVLLTALLALAYQ       3.764      19
58        SP_961           MVRIGISTLALALAHLVTS       3.623      19
59        SP_591      MRIIPSIGTLLTTVSLFTAHGTAA       4.951      24
60        SP_621        MVQLKSFLAVTATASLLTLSNA       2.840      22
61        SP_176         MILSKLLTTVAALSLLTPSVA       3.153      21
62        SP_721          MVHIKSFVTGLLATASTVTA       2.376      20
63        SP_163          MVQLTHLVALAASLFTLSVA       2.739      20
64        SP_148           MLFSSLIVTLAASTALSSA       4.387      19
65        SP_593        MILPHITTLLAIALSATSSALP       5.195      22
66        SP_932        MVSFKQIALLVTTLANIGLSTA       2.780      22
67        SP_131        MILSRISALLVLGLALFTQSLA       3.121      22
68        SP_592         MVQLKSFALLLGTSLFSSALA       3.095      21
69        SP_692          MVLPKIALLVTGLSATLANA       2.180      20
70        SP_703       MLPKIIHLLVALLSVLLVQLSVA       3.150      23
71        SP_255           MLSILKAALCALLLTPSLA       3.511      19
72        SP_388           MVSTKFLLTLLGAAPLALA       2.789      19
73        SP_815        MVAIKSLLVSLLAASLAPLATA       1.961      22
74        SP_857              MRFLAVAALLATTASA       3.476      16
75        SP_819          MVRLSHILTTALAILSPAVA       3.001      20
76        SP_270          MVHIKSLAVALGALLPTALA       2.241      20
77        SP_382            MLLPRLFYLGAIVPTVLS       4.459      18
78        SP_357         MVQIKSLALVLSTALFSSTLA       2.679      21
79        SP_952          MRVSTIPTALLGLSLSAVNA       3.271      20
80        SP_659         MVRLNSITALASLLAVSLTAA       3.640      21
81        SP_576      MILSYRSLVVTTVALLGLSTPATA       3.874      24
82        SP_560         MVLLKPLLATALLASLTPAVA       3.046      21
83        SP_256        MVHLKTLALAVSALLTPSIVSA       3.073      22

                                                               codon_optimized_sequences  \
0                              ATGCGCCCTACTCTCCTTGCCCTAGGCGTCATCAGCTTCGCTCTGACCTTGCATTCC
1                  ATGAAGTTCACCTTGATAATCCTCATTATCGTCATCCTTACTATTATTTTTTCCCCTGGCGCCCTGGCT
2               ATGAAGGTCACCCTGTCTCTATTGGCCGTGTTCCTCGCGGCCCTTAGCGCTTCCGCTATCCCTGCAAACGGC
3                           ATGAAGGCTATAATTATCCTCTTACTGATCATTCTTACCCTAGCCTTGACTGTCCAGGGC
4                     ATGCGCGTCTTCTCCGCCACCGCCATTCTCGCTCTGTCGCCTTTGCTTATCGCGTCTGCAAGCCCC
5                              ATGCGCCTTGTCTCCCTCTTGACAATCCTGGGCACCGCTATTACTACGGCAAGCGCC
6                  ATGCGCCCTTTGGCAATTACCCTTGGCCTCGCCACCACGATCTTCAACCCCATCACTACAGCTTCCCTG
7                           ATGCGCGTGCTTGGCATCTCTAGCATTATCCTGACGACTCTCGTCTCCACAACCTTGGCC
8                           ATGCGCCCTACCAGCTCTGCTTTTGTCTCCATCCTCGGCTTCGCAGCCATTGCGACTGCC
9            ATGAAGATCCCTTTTCTGCTATCGGCTGCCCTTTTGACCACTCTCAGCCTGTTCTCCACCTCTACGACACTCGCA
10                    ATGTTGACCACACTCATCCAGTACACTCTGTTAGTCTCTCTTCTATTCGGCAGCCCTGCTGCCTCC
11                       ATGAAGACCATTCTGCCTGTCCTCCTTTCCGCTATCACTGCCTTGGCCTCTCCCGCATTCGCG
12                                ATGCGCCTATTCCATCTTATTGTCCTCGCTACTGTGCTGTCCTTGACCATCGCC
13                                   ATGCGCCTTTCTGCAGCTTTCATCCTCGGCCTGAGCTCCACCGTCATTGCC
14                    ATGCTTCCTACCCTATTGCGCCTCTTCGGCCTGCTGGCAATCTCCCTCGTCGCGGTGGCTATTGCC
15                             ATGCGCTTCAGCTTACTTGCAGTGTTGTCCATCGCTCTGGGCCTCCTAGTCCAGGCC
16                       ATGCGCCTTATCACTTTCTTGACCACAATTCTGGCCTTAGTCCTAGTGTCCCTCTGCCAGGCT
17                       ATGCGCTCCTTCGCTTTTCTTCTGGCAGTTGTACTATTGAGCGTGGTCGGCCTCGCCTCTGCG
18                             ATGCGCTTCTTTGCCTCCCTGATCATAATTGCAAGCCTCCTTGCCGCGACCATCGCT
19                                   ATGCGCCTGTCCCTCGGCTTCATCCTTGGTACTTTGACCCTAGTCAACGCC
20                             ATGAAGCTAATCCTGTTTACCCTGATTGCCCTCTCCTTGTTCCAGCTTAGCCTCGCT
21  ATGCTATCTAGCTCCGCCCGCTGGGCTTTCCTCCTGACCACTATTATCGGCTTGCTCCTGTGCCTTCATAACCCTATCGTCGCA
22                    ATGCTCAGCTCTTCCGTCCTGCTGCGCATCGCCCTACTCGCACTTTTATTGGCTCTTTGCGTGGGC
23                                ATGATCCTTACCTACTTCTTGATTGCGGCACTATTACTGTCCCTCACTGCCGCT
24                          ATGCGCTCTTTCATTTCCTTGGTCGGCATCCTACTGACCCTTGCCCTCTACGTGCATAGC
25                       ATGCGCTTCACTTCCCTGTCTGCCCTCGCACTTGGCGCCTTGGTGATCACCAGCGTCGCTGCG
26                             ATGAAGCTGAGCAACTTTGTCACAACTCTCGTGCTTTCCACCCCTTTCGCCTCTGCT
27                                ATGCTCCTGCGCTACTTGCTGACCGTCGTACTCGCCGTGGGCCTTGTTCTATCC
28                          ATGCGCTTTTTCTCTAGCGTTCTTACTGCTCTGGCAGCCCTCACAACCTCCGTGGTCGGC
29                          ATGATCCCTTACACTCTAGCGGCACTGGTCGTGGCCTGCCTCAGCACCTTGTCCCTTGCT
30                    ATGGTGTTAACTAAGTTGAGCGTCCTGGCAACCGCCCTACTCGGCCTTTCCGCTCAGGCGATCGCC
31                             ATGCGCCCTGTGTCCATCCTCGCTACCGTCCTGGGCTTGGCGAACCTTGCAACTGCC
32                             ATGGTCTTGACCAAGTCCCTACTGGTGCTTAGCACTATCGCAGCGCAGGCTCTCGCC
33                       ATGATCCTGTCCAACACCATTCTTGTCGCTACTTTGGCCGCCCTAAGCGGCCTCGCACATGCG
34              ATGATTTTCACCCGCCTCATCCAGTTGCTTTGCGCCGCACTACTGTTAGCGCTGGTGCTCCAGGTCCAAGCT
35                    ATGCGCTCCTCTGCCCTCCTTACCGCCCTAGTCGTGCTGTTGGGCTGCATCAGCAACGCAGCTGCG
36                                   ATGCGCATTAGCATCCCTCTGATCACTGCCGTCCTCTCCACCGCATCTGCT
37                       ATGGTGGCTCTTCAGAAGCTGCTCTTGCTAACCGCCCTCGCGTCCCTGAGCCCTACTGTCGCA
38                       ATGGTGCATTTCAAGGCTCTCGCCACCGCGGTCCTAGCATCCTTGCTTAGCCCTACTCTGGCC
39                       ATGCTGGTCCCTAAGCTGTCCGCCCTCTTGCTCGGCGCACTTCTACCCACCGTGGTTAGCGCT
40                                ATGGTCCGCCTGGGCTTCTTTTCCCTTCTCGCTACCATCCCTTTGGCCCTAAGC
41                          ATGCGCTTCACCCTCGCGTCCCTGGCCCTTTTGGCTATCGCCAACACTGTCGTGAGCGCA
42                    ATGGTCGCGATCAAGTCCTTGCTAACCGCAGCTCTCGCCGCCCTTAGCATTACTCCTGCACTGGCT
43                          ATGGTGTCCATCAAGAACCTTGCCCTCTTCGTCACTACCCTGTTGGGCTGCAGCCAGGCT
44              ATGATTTTGAGCCGCATCCTGTCCGCGACCCTAGTCGCATTAGCCCTCTGCCTTTTCAACCAGGCTACTGCC
45                          ATGAAGACCTTTATCCCTTTCGTCGCTCTTCTCTCTACTATTTCCAGCCTGTGCGCAGCC
46                       ATGGTCCATATCAAGCCTCTTCTGGCCACCGCTTTGGCAGCTCTATCCCCCCTCGCCACTGCG
47                    ATGCTAGTCAAGTCCATCGTGTCGACCTTACTGGCATTGTCTCTCAGCTCAGGCCTTGCCAACGCT
48                             ATGGTGCGCTTGTCCCTGCTTGCAAGCGCTCTCCTAGTCGCGTCTTCGACCTTAGCC
49                          ATGCGCTCCTTGCTCCTGAGCGTGCTATTTACCGTCTTATTCGCAATCCTTGCCACTGCT
50                          ATGCTTATCCGCTCTATTGCAACCCTGGCTGTCTTGGGCCTCTCCCAGACTGCCCTAAGC
51                       ATGGTCTCCCAGAAGCTATTATCTTTGGCGACCATCCTTGCACTGGCTAGCCTCGGCCAAGCC
52                          ATGGTCGCCCTGAAGCATATCCTAACCGCCCTCTTAGCGTTGTCCCCTCTTGCAACTGCT
53                       ATGATCGTCACCCGCTTCCTTAGCACTCTCCTATTGGCGGCATCCCTGTCTGCTGCCAACGCC
54              ATGGTCCTGGGCATTACCTCGAAGGCTCTTGCAATCTCCTTGCTCGCGTGCCTATCTACTCCTAGCACAGCC
55                       ATGCTCCTGCCTACCGTGACTCTCTTGTCCGTCGGCCTGGCTGCCCTACAGCCCGCACTTGCG
56                    ATGGTGCATATCAAGCCTTTCGCGACTGTCGCTCTGCTAGCCAGCTTGCTTACCCCCTCCCTCGCA
57                             ATGATCCTCCGCTGGACCTTGGTCCTGCTCACTGCTCTACTTGCACTGGCCTACCAG
58                             ATGGTCCGCATTGGCATCTCCACCTTGGCCCTTGCTCTGGCACATCTCGTGACTAGC
59              ATGCGCATCATTCCTTCCATCGGTACCCTGCTCACGACCGTCAGCCTTTTCACTGCCCATGGCACAGCAGCT
60                    ATGGTCCAGTTGAAGTCCTTCCTCGCAGTGACAGCTACCGCGAGCCTTCTGACTCTATCTAACGCC
61                       ATGATCTTAAGCAAGCTACTGACTACCGTGGCAGCTCTCTCTCTTTTGACACCTTCCGTCGCC
62                          ATGGTTCATATCAAGAGCTTCGTGACTGGCCTCCTGGCAACAGCTTCCACGGTCACCGCC
63                          ATGGTTCAGCTCACCCATCTAGTGGCCCTTGCAGCTAGCCTGTTCACTTTGTCCGTCGCG
64                             ATGTTGTTCAGCTCGCTTATCGTCACTCTCGCAGCTTCCACCGCGCTGTCATCTGCC
65                    ATGATCTTGCCTCATATTACTACACTTCTAGCCATCGCTCTGAGCGCGACCTCCTCTGCACTCCCC
66                    ATGGTGAGCTTCAAGCAGATTGCTTTGCTGGTCACCACTCTCGCAAACATCGGCCTTTCCACAGCC
67                    ATGATTCTATCTCGCATCAGCGCACTGCTTGTCCTGGGCCTCGCCTTGTTCACCCAGTCCCTCGCT
68                       ATGGTCCAGTTGAAGTCTTTCGCTCTCCTGTTAGGCACCAGCCTTTTTTCGTCCGCACTAGCC
69                          ATGGTGCTTCCTAAGATCGCACTATTGGTCACCGGCCTGTCCGCTACTCTCGCGAACGCC
70                 ATGCTGCCTAAGATCATTCATTTGCTCGTGGCTCTATTAAGCGTTCTTCTCGTACAGCTGTCCGTCGCC
71                             ATGTTGAGCATCCTGAAGGCCGCGCTCTGCGCTCTACTCCTGACCCCTTCCCTTGCA
72                             ATGGTCTCCACCAAGTTCCTTCTAACTTTGCTCGGCGCCGCGCCTTTAGCTCTGGCA
73                    ATGGTCGCTATCAAGAGCCTACTGGTGTCCTTACTCGCAGCCTCTTTGGCCCCTCTTGCGACCGCT
74                                      ATGCGCTTCCTCGCCGTCGCAGCGCTTCTGGCTACCACTGCCTCCGCT
75                          ATGGTGCGCCTCTCCCATATTCTTACCACTGCTTTGGCAATCCTGAGCCCTGCGGTCGCC
76                          ATGGTGCATATCAAGTCCCTTGCTGTCGCCCTAGGCGCATTGCTGCCTACCGCCCTCGCG
77                                ATGTTGCTTCCTCGCCTGTTCTACCTCGGCGCCATCGTCCCCACCGTGCTATCC
78                       ATGGTGCAGATCAAGTCTCTGGCCCTAGTCCTTTCCACTGCTTTGTTCTCGAGCACCCTCGCA
79                          ATGCGCGTGAGCACCATCCCTACTGCTCTCTTGGGCCTTTCTCTGTCCGCAGTCAACGCC
80                       ATGGTCCGCCTGAACTCCATCACCGCACTCGCTTCTCTTCTAGCGGTGAGCTTGACTGCCGCC
81              ATGATCCTGTCTTACCGCAGCCTTGTTGTGACAACTGTCGCTTTGCTAGGCCTCTCCACGCCTGCCACCGCA
82                       ATGGTGCTACTGAAGCCCCTTCTGGCTACTGCCCTCCTCGCATCCTTGACCCCTGCCGTCGCG
83                    ATGGTCCATCTGAAGACCCTCGCGCTTGCTGTGTCCGCACTATTGACTCCTTCTATCGTTAGCGCC

   sp_name
0     SP_0
1     SP_1
2     SP_2
3     SP_3
4     SP_4
5     SP_5
6     SP_6
7     SP_7
8     SP_8
9     SP_9
10   SP_10
11   SP_11
12   SP_12
13   SP_13
14   SP_14
15   SP_15
16   SP_16
17   SP_17
18   SP_18
19   SP_19
20   SP_20
21   SP_21
22   SP_22
23   SP_23
24   SP_24
25   SP_25
26   SP_26
27   SP_27
28   SP_28
29   SP_29
30   SP_30
31   SP_31
32   SP_32
33   SP_33
34   SP_34
35   SP_35
36   SP_36
37   SP_37
38   SP_38
39   SP_39
40   SP_40
41   SP_41
42   SP_42
43   SP_43
44   SP_44
45   SP_45
46   SP_46
47   SP_47
48   SP_48
49   SP_49
50   SP_50
51   SP_51
52   SP_52
53   SP_53
54   SP_54
55   SP_55
56   SP_56
57   SP_57
58   SP_58
59   SP_59
60   SP_60
61   SP_61
62   SP_62
63   SP_63
64   SP_64
65   SP_65
66   SP_66
67   SP_67
68   SP_68
69   SP_69
70   SP_70
71   SP_71
72   SP_72
73   SP_73
74   SP_74
75   SP_75
76   SP_76
77   SP_77
78   SP_78
79   SP_79
80   SP_80
81   SP_81
82   SP_82
83   SP_83

In [13]:
final_sample

,SecretoGen_ID,Sequence,Perplexity,Length,codon_optimized_sequences,sp_name
0,SP_997,MRPTLLALGVISFALTLHS,7.515804,19,ATGCGCCCTACTCTCCTTGCCCTAGGCGTCATCAGCTTCGCTCTGA...,SP_0
1,SP_944,MKFTLIILIIVILTIIFSPGALA,7.421489,23,ATGAAGTTCACCTTGATAATCCTCATTATCGTCATCCTTACTATTA...,SP_1
2,SP_948,MKVTLSLLAVFLAALSASAIPANG,7.179219,24,ATGAAGGTCACCCTGTCTCTATTGGCCGTGTTCCTCGCGGCCCTTA...,SP_2
3,SP_993,MKAIIILLLIILTLALTVQG,7.140379,20,ATGAAGGCTATAATTATCCTCTTACTGATCATTCTTACCCTAGCCT...,SP_3
4,SP_204,MRVFSATAILALSPLLIASASP,6.925975,22,ATGCGCGTCTTCTCCGCCACCGCCATTCTCGCTCTGTCGCCTTTGC...,SP_4
...,...,...,...,...,...,...
79,SP_952,MRVSTIPTALLGLSLSAVNA,3.271387,20,ATGCGCGTGAGCACCATCCCTACTGCTCTCTTGGGCCTTTCTCTGT...,SP_79
80,SP_659,MVRLNSITALASLLAVSLTAA,3.640410,21,ATGGTCCGCCTGAACTCCATCACCGCACTCGCTTCTCTTCTAGCGG...,SP_80
81,SP_576,MILSYRSLVVTTVALLGLSTPATA,3.873739,24,ATGATCCTGTCTTACCGCAGCCTTGTTGTGACAACTGTCGCTTTGC...,SP_81
82,SP_560,MVLLKPLLATALLASLTPAVA,3.045672,21,ATGGTGCTACTGAAGCCCCTTCTGGCTACTGCCCTCCTCGCATCCT...,SP_82
83,SP_256,MVHLKTLALAVSALLTPSIVSA,3.073488,22,ATGGTCCATCTGAAGACCCTCGCGCTTGCTGTGTCCGCACTATTGA...,SP_83

# GEnerating primers

In [14]:
RFP = Dseqrecord(SeqIO.read("../data/10_genetic_parts/parts/RFP_w_B_homolgy.fasta", "fasta"))
pTef = Dseqrecord(SeqIO.read("../data/10_genetic_parts/parts/pTEF_w_A_homology.fasta", "fasta"))
print(f'The lenght of RFP is {len(RFP)}')
print(f'The lenght of pTef is {len(pTef)}')

The lenght of RFP is 1977
The lenght of pTef is 1384

In [15]:
from pydna.amplify import pcr
from pydna.primer import Primer

In [16]:
generic_pTef_fwd = Primer('CGAGACAGCAGAATCACCG') # generic 
generic_pTef_rev = Primer('GGTGAAGGTTGTGTTATGTTTTGTGG') # martis

generic_rfp_fwd = Primer('GCCTCCTCCGAGGACG') # martis
generic_rfp_rev = Primer('GAGGAGAGTGGATGGATAGTCTGG') # generic

## generating the overhangs

In [17]:
reverse_ovh_list = []
forward_ovh_list = []

for index, row in final_sample.iterrows():
    # get the sequence
    seq = str(row['codon_optimized_sequences'])

    # make the overhangs like marti propose: 
    # Forward
    fwd_ovh = seq[-44:] + generic_rfp_fwd
    fwd_ovh.name= f"{str(row['sp_name'])}_fwd"
    fwd_ovh.id = f"{str(row['sp_name'])}_fwd"

    # reverse
    rev_ovh = Seq(seq[:-14]).reverse_complement()+ generic_pTef_rev 
    rev_ovh.name = f"{str(row['sp_name'])}_rev"
    rev_ovh.id = f"{str(row['sp_name'])}_rev"


    forward_ovh_list.append(fwd_ovh)
    reverse_ovh_list.append(rev_ovh)

Amplicons

In [18]:
from pydna.amplify import pcr
from pydna.primer import Primer

pTef_amplicons = []
for i in range(len(reverse_ovh_list)): 
    amplicon = pcr(generic_pTef_fwd, reverse_ovh_list[i], pTef)
    pTef_amplicons.append(amplicon)

In [19]:

RFP_amplicons = []
for i in range(len(forward_ovh_list)): 
    amplicon = pcr(forward_ovh_list[i], generic_rfp_rev, RFP)
    RFP_amplicons.append(amplicon)

# Testing the overlap

In [20]:
id_names= final_sample['sp_name'].to_list()

In [21]:
# changing the names of the amplicons
for i in range(len(pTef_amplicons)):
    pTef_amplicons[i].name =  f'pTef_{pTef_amplicons[i].name }_{id_names[i]}'
    
for i in range(len(RFP_amplicons)):
    RFP_amplicons[i].name =  f'RFP_{RFP_amplicons[i].name }_{id_names[i]}'

In [22]:
from pydna.assembly import Assembly

In [23]:
for i in range(len(RFP_amplicons)): 
    assemblyobj = Assembly([pTef_amplicons[i],RFP_amplicons[i]], limit = 18)
    contig = assemblyobj.assemble_linear()[0]

    print(contig.figure(), '\n')

pTef_929bp_PCR_prod_SP_0|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_0

pTef_941bp_PCR_prod_SP_1|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_1

pTef_944bp_PCR_prod_SP_2|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_2

pTef_932bp_PCR_prod_SP_3|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_3

pTef_938bp_PCR_prod_SP_4|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_4

pTef_929bp_PCR_prod_SP_5|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_5

pTef_941bp_PCR_prod_SP_6|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_6

pTef_932bp_PCR_prod_SP_7|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_7

pTef_932bp_PCR_prod_SP_8|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_8

pTef_947bp_PCR_prod_SP_9|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_9

pTef_938bp_PCR_prod_SP_10|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_10

pTef_935bp_PCR_prod_SP_11|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_11

pTef_926bp_PCR_prod_SP_12|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_12

pTef_923bp_PCR_prod_SP_13|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_13

pTef_938bp_PCR_prod_SP_14|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_14

pTef_929bp_PCR_prod_SP_15|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_15

pTef_935bp_PCR_prod_SP_16|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_16

pTef_935bp_PCR_prod_SP_17|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_17

pTef_929bp_PCR_prod_SP_18|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_18

pTef_923bp_PCR_prod_SP_19|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_19

pTef_929bp_PCR_prod_SP_20|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_20

pTef_956bp_PCR_prod_SP_21|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_21

pTef_938bp_PCR_prod_SP_22|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_22

pTef_926bp_PCR_prod_SP_23|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_23

pTef_932bp_PCR_prod_SP_24|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_24

pTef_935bp_PCR_prod_SP_25|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_25

pTef_929bp_PCR_prod_SP_26|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_26

pTef_926bp_PCR_prod_SP_27|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_27

pTef_932bp_PCR_prod_SP_28|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_28

pTef_932bp_PCR_prod_SP_29|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_29

pTef_938bp_PCR_prod_SP_30|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_30

pTef_929bp_PCR_prod_SP_31|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_31

pTef_929bp_PCR_prod_SP_32|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_32

pTef_935bp_PCR_prod_SP_33|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_33

pTef_944bp_PCR_prod_SP_34|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_34

pTef_938bp_PCR_prod_SP_35|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_35

pTef_923bp_PCR_prod_SP_36|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_36

pTef_935bp_PCR_prod_SP_37|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_37

pTef_935bp_PCR_prod_SP_38|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_38

pTef_935bp_PCR_prod_SP_39|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_39

pTef_926bp_PCR_prod_SP_40|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_40

pTef_932bp_PCR_prod_SP_41|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_41

pTef_938bp_PCR_prod_SP_42|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_42

pTef_932bp_PCR_prod_SP_43|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_43

pTef_944bp_PCR_prod_SP_44|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_44

pTef_932bp_PCR_prod_SP_45|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_45

pTef_935bp_PCR_prod_SP_46|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_46

pTef_938bp_PCR_prod_SP_47|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_47

pTef_929bp_PCR_prod_SP_48|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_48

pTef_932bp_PCR_prod_SP_49|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_49

pTef_932bp_PCR_prod_SP_50|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_50

pTef_935bp_PCR_prod_SP_51|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_51

pTef_932bp_PCR_prod_SP_52|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_52

pTef_935bp_PCR_prod_SP_53|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_53

pTef_944bp_PCR_prod_SP_54|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_54

pTef_935bp_PCR_prod_SP_55|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_55

pTef_938bp_PCR_prod_SP_56|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_56

pTef_929bp_PCR_prod_SP_57|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_57

pTef_929bp_PCR_prod_SP_58|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_58

pTef_944bp_PCR_prod_SP_59|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_59

pTef_938bp_PCR_prod_SP_60|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_60

pTef_935bp_PCR_prod_SP_61|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_61

pTef_932bp_PCR_prod_SP_62|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_62

pTef_932bp_PCR_prod_SP_63|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_63

pTef_929bp_PCR_prod_SP_64|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_64

pTef_938bp_PCR_prod_SP_65|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_65

pTef_938bp_PCR_prod_SP_66|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_66

pTef_938bp_PCR_prod_SP_67|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_67

pTef_935bp_PCR_prod_SP_68|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_68

pTef_932bp_PCR_prod_SP_69|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_69

pTef_941bp_PCR_prod_SP_70|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_70

pTef_929bp_PCR_prod_SP_71|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_71

pTef_929bp_PCR_prod_SP_72|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_72

pTef_938bp_PCR_prod_SP_73|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_73

pTef_920bp_PCR_prod_SP_74|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_74

pTef_932bp_PCR_prod_SP_75|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_75

pTef_932bp_PCR_prod_SP_76|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_76

pTef_926bp_PCR_prod_SP_77|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_77

pTef_935bp_PCR_prod_SP_78|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_78

pTef_932bp_PCR_prod_SP_79|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_79

pTef_935bp_PCR_prod_SP_80|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_80

pTef_944bp_PCR_prod_SP_81|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_81

pTef_935bp_PCR_prod_SP_82|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_82

pTef_938bp_PCR_prod_SP_83|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_83

In [24]:
# changing the names of the amplicons
forward_primers = []
reverse_primers = []

for i in range(len(RFP_amplicons)):
    forward_primers.append(str(RFP_amplicons[i].forward_primer.seq))

for i in range(len(pTef_amplicons)):
    
    reverse_primers.append(str(pTef_amplicons[i].reverse_primer.seq))

In [25]:
forward_ovh_list

[SP_0_fwd 60-mer:5'-TCCTTGCCCTAGGCG..ACG-3',
 SP_1_fwd 60-mer:5'-TTATCGTCATCCTTA..ACG-3',
 SP_2_fwd 60-mer:5'-TGTTCCTCGCGGCCC..ACG-3',
 SP_3_fwd 60-mer:5'-TCCTCTTACTGATCA..ACG-3',
 SP_4_fwd 60-mer:5'-CCATTCTCGCTCTGT..ACG-3',
 SP_5_fwd 60-mer:5'-CCCTCTTGACAATCC..ACG-3',
 SP_6_fwd 60-mer:5'-GCCTCGCCACCACGA..ACG-3',
 SP_7_fwd 60-mer:5'-TCTCTAGCATTATCC..ACG-3',
 SP_8_fwd 60-mer:5'-CTGCTTTTGTCTCCA..ACG-3',
 SP_9_fwd 60-mer:5'-TTTTGACCACTCTCA..ACG-3',
 SP_10_fwd 60-mer:5'-ACACTCTGTTAGTCT..ACG-3',
 SP_11_fwd 60-mer:5'-TCCTCCTTTCCGCTA..ACG-3',
 SP_12_fwd 60-mer:5'-TCCATCTTATTGTCC..ACG-3',
 SP_13_fwd 60-mer:5'-TTTCTGCAGCTTTCA..ACG-3',
 SP_14_fwd 60-mer:5'-TCTTCGGCCTGCTGG..ACG-3',
 SP_15_fwd 60-mer:5'-TACTTGCAGTGTTGT..ACG-3',
 SP_16_fwd 60-mer:5'-TGACCACAATTCTGG..ACG-3',
 SP_17_fwd 60-mer:5'-TTCTGGCAGTTGTAC..ACG-3',
 SP_18_fwd 60-mer:5'-CCTCCCTGATCATAA..ACG-3',
 SP_19_fwd 60-mer:5'-TGTCCCTCGGCTTCA..ACG-3',
 SP_20_fwd 60-mer:5'-TGTTTACCCTGATTG..ACG-3',
 SP_21_fwd 60-mer:5'-CTATTATCGGCTTGC..ACG-3',
 SP_22_fwd 60-mer:5'-TGCGCATCGCCCTAC..ACG-3',
 SP_23_fwd 60-mer:5'-CCTACTTCTTGATTG..ACG-3',
 SP_24_fwd 60-mer:5'-CCTTGGTCGGCATCC..ACG-3',
 SP_25_fwd 60-mer:5'-CTGCCCTCGCACTTG..ACG-3',
 SP_26_fwd 60-mer:5'-ACTTTGTCACAACTC..ACG-3',
 SP_27_fwd 60-mer:5'-GCTACTTGCTGACCG..ACG-3',
 SP_28_fwd 60-mer:5'-GCGTTCTTACTGCTC..ACG-3',
 SP_29_fwd 60-mer:5'-TAGCGGCACTGGTCG..ACG-3',
 SP_30_fwd 60-mer:5'-TCCTGGCAACCGCCC..ACG-3',
 SP_31_fwd 60-mer:5'-CCATCCTCGCTACCG..ACG-3',
 SP_32_fwd 60-mer:5'-AGTCCCTACTGGTGC..ACG-3',
 SP_33_fwd 60-mer:5'-TTCTTGTCGCTACTT..ACG-3',
 SP_34_fwd 60-mer:5'-TTTGCGCCGCACTAC..ACG-3',
 SP_35_fwd 60-mer:5'-CCGCCCTAGTCGTGC..ACG-3',
 SP_36_fwd 60-mer:5'-TTAGCATCCCTCTGA..ACG-3',
 SP_37_fwd 60-mer:5'-TGCTCTTGCTAACCG..ACG-3',
 SP_38_fwd 60-mer:5'-TCGCCACCGCGGTCC..ACG-3',
 SP_39_fwd 60-mer:5'-CCGCCCTCTTGCTCG..ACG-3',
 SP_40_fwd 60-mer:5'-TGGGCTTCTTTTCCC..ACG-3',
 SP_41_fwd 60-mer:5'-CGTCCCTGGCCCTTT..ACG-3',
 SP_42_fwd 60-mer:5'-TAACCGCAGCTCTCG..ACG-3',
 SP_43_fwd 60-mer:5'-ACCTTGCCCTCTTCG..ACG-3',
 SP_44_fwd 60-mer:5'-CCCTAGTCGCATTAG..ACG-3',
 SP_45_fwd 60-mer:5'-CTTTCGTCGCTCTTC..ACG-3',
 SP_46_fwd 60-mer:5'-TTCTGGCCACCGCTT..ACG-3',
 SP_47_fwd 60-mer:5'-CGACCTTACTGGCAT..ACG-3',
 SP_48_fwd 60-mer:5'-CCCTGCTTGCAAGCG..ACG-3',
 SP_49_fwd 60-mer:5'-TGAGCGTGCTATTTA..ACG-3',
 SP_50_fwd 60-mer:5'-TTGCAACCCTGGCTG..ACG-3',
 SP_51_fwd 60-mer:5'-TATCTTTGGCGACCA..ACG-3',
 SP_52_fwd 60-mer:5'-ATATCCTAACCGCCC..ACG-3',
 SP_53_fwd 60-mer:5'-TTAGCACTCTCCTAT..ACG-3',
 SP_54_fwd 60-mer:5'-TTGCAATCTCCTTGC..ACG-3',
 SP_55_fwd 60-mer:5'-CTCTCTTGTCCGTCG..ACG-3',
 SP_56_fwd 60-mer:5'-CGACTGTCGCTCTGC..ACG-3',
 SP_57_fwd 60-mer:5'-GGACCTTGGTCCTGC..ACG-3',
 SP_58_fwd 60-mer:5'-GCATCTCCACCTTGG..ACG-3',
 SP_59_fwd 60-mer:5'-TGCTCACGACCGTCA..ACG-3',
 SP_60_fwd 60-mer:5'-TCGCAGTGACAGCTA..ACG-3',
 SP_61_fwd 60-mer:5'-TGACTACCGTGGCAG..ACG-3',
 SP_62_fwd 60-mer:5'-GCTTCGTGACTGGCC..ACG-3',
 SP_63_fwd 60-mer:5'-ATCTAGTGGCCCTTG..ACG-3',
 SP_64_fwd 60-mer:5'-CGCTTATCGTCACTC..ACG-3',
 SP_65_fwd 60-mer:5'-CACTTCTAGCCATCG..ACG-3',
 SP_66_fwd 60-mer:5'-CTTTGCTGGTCACCA..ACG-3',
 SP_67_fwd 60-mer:5'-CACTGCTTGTCCTGG..ACG-3',
 SP_68_fwd 60-mer:5'-TCGCTCTCCTGTTAG..ACG-3',
 SP_69_fwd 60-mer:5'-TCGCACTATTGGTCA..ACG-3',
 SP_70_fwd 60-mer:5'-TCGTGGCTCTATTAA..ACG-3',
 SP_71_fwd 60-mer:5'-TGAAGGCCGCGCTCT..ACG-3',
 SP_72_fwd 60-mer:5'-AGTTCCTTCTAACTT..ACG-3',
 SP_73_fwd 60-mer:5'-TGGTGTCCTTACTCG..ACG-3',
 SP_74_fwd 60-mer:5'-GCTTCCTCGCCGTCG..ACG-3',
 SP_75_fwd 60-mer:5'-ATATTCTTACCACTG..ACG-3',
 SP_76_fwd 60-mer:5'-CCCTTGCTGTCGCCC..ACG-3',
 SP_77_fwd 60-mer:5'-CTCGCCTGTTCTACC..ACG-3',
 SP_78_fwd 60-mer:5'-TGGCCCTAGTCCTTT..ACG-3',
 SP_79_fwd 60-mer:5'-TCCCTACTGCTCTCT..ACG-3',
 SP_80_fwd 60-mer:5'-TCACCGCACTCGCTT..ACG-3',
 SP_81_fwd 60-mer:5'-TGACAACTGTCGCTT..ACG-3',
 SP_82_fwd 60-mer:5'-TTCTGGCTACTGCCC..ACG-3',
 SP_83_fwd 60-mer:5'-CGCTTGCTGTGTCCG..ACG-3']

In [26]:
reverse_ovh_list

[SP_0_rev 69-mer:5'-GAGCGAAGCTGATGA..TGG-3',
 SP_1_rev 81-mer:5'-GGGAAAAAATAATAG..TGG-3',
 SP_2_rev 84-mer:5'-TAGCGGAAGCGCTAA..TGG-3',
 SP_3_rev 72-mer:5'-AGGCTAGGGTAAGAA..TGG-3',
 SP_4_rev 78-mer:5'-CGATAAGCAAAGGCG..TGG-3',
 SP_5_rev 69-mer:5'-TAATAGCGGTGCCCA..TGG-3',
 SP_6_rev 81-mer:5'-TGATGGGGTTGAAGA..TGG-3',
 SP_7_rev 72-mer:5'-AGACGAGAGTCGTCA..TGG-3',
 SP_8_rev 72-mer:5'-CTGCGAAGCCGAGGA..TGG-3',
 SP_9_rev 87-mer:5'-AGGTGGAGAACAGGC..TGG-3',
 SP_10_rev 78-mer:5'-TGCCGAATAGAAGAG..TGG-3',
 SP_11_rev 75-mer:5'-AGGCCAAGGCAGTGA..TGG-3',
 SP_12_rev 66-mer:5'-ACAGCACAGTAGCGA..TGG-3',
 SP_13_rev 63-mer:5'-AGCTCAGGCCGAGGA..TGG-3',
 SP_14_rev 78-mer:5'-CGACGAGGGAGATTG..TGG-3',
 SP_15_rev 69-mer:5'-GGCCCAGAGCGATGG..TGG-3',
 SP_16_rev 75-mer:5'-ACACTAGGACTAAGG..TGG-3',
 SP_17_rev 75-mer:5'-CGACCACGCTCAATA..TGG-3',
 SP_18_rev 69-mer:5'-CAAGGAGGCTTGCAA..TGG-3',
 SP_19_rev 63-mer:5'-TCAAAGTACCAAGGA..TGG-3',
 SP_20_rev 69-mer:5'-GGAACAAGGAGAGGG..TGG-3',
 SP_21_rev 96-mer:5'-TATGAAGGCACAGGA..TGG-3',
 SP_22_rev 78-mer:5'-CCAATAAAAGTGCGA..TGG-3',
 SP_23_rev 66-mer:5'-ACAGTAATAGTGCCG..TGG-3',
 SP_24_rev 72-mer:5'-GGGCAAGGGTCAGTA..TGG-3',
 SP_25_rev 75-mer:5'-TGATCACCAAGGCGC..TGG-3',
 SP_26_rev 69-mer:5'-GGGTGGAAAGCACGA..TGG-3',
 SP_27_rev 66-mer:5'-CCACGGCGAGTACGA..TGG-3',
 SP_28_rev 72-mer:5'-TTGTGAGGGCTGCCA..TGG-3',
 SP_29_rev 72-mer:5'-TGCTGAGGCAGGCCA..TGG-3',
 SP_30_rev 78-mer:5'-CGGAAAGGCCGAGTA..TGG-3',
 SP_31_rev 69-mer:5'-TCGCCAAGCCCAGGA..TGG-3',
 SP_32_rev 69-mer:5'-CTGCGATAGTGCTAA..TGG-3',
 SP_33_rev 75-mer:5'-CGCTTAGGGCGGCCA..TGG-3',
 SP_34_rev 84-mer:5'-GCACCAGCGCTAACA..TGG-3',
 SP_35_rev 78-mer:5'-TGATGCAGCCCAACA..TGG-3',
 SP_36_rev 63-mer:5'-AGAGGACGGCAGTGA..TGG-3',
 SP_37_rev 75-mer:5'-TCAGGGACGCGAGGG..TGG-3',
 SP_38_rev 75-mer:5'-TAAGCAAGGATGCTA..TGG-3',
 SP_39_rev 75-mer:5'-TGGGTAGAAGTGCGC..TGG-3',
 SP_40_rev 66-mer:5'-GGATGGTAGCGAGAA..TGG-3',
 SP_41_rev 72-mer:5'-TGTTGGCGATAGCCA..TGG-3',
 SP_42_rev 78-mer:5'-TAATGCTAAGGGCGG..TGG-3',
 SP_43_rev 72-mer:5'-CCAACAGGGTAGTGA..TGG-3',
 SP_44_rev 84-mer:5'-TGAAAAGGCAGAGGG..TGG-3',
 SP_45_rev 72-mer:5'-TGGAAATAGTAGAGA..TGG-3',
 SP_46_rev 75-mer:5'-GGGATAGAGCTGCCA..TGG-3',
 SP_47_rev 78-mer:5'-CTGAGCTGAGAGACA..TGG-3',
 SP_48_rev 69-mer:5'-ACGCGACTAGGAGAG..TGG-3',
 SP_49_rev 72-mer:5'-TTGCGAATAAGACGG..TGG-3',
 SP_50_rev 72-mer:5'-GGGAGAGGCCCAAGA..TGG-3',
 SP_51_rev 75-mer:5'-TAGCCAGTGCAAGGA..TGG-3',
 SP_52_rev 72-mer:5'-GGGACAACGCTAAGA..TGG-3',
 SP_53_rev 75-mer:5'-ACAGGGATGCCGCCA..TGG-3',
 SP_54_rev 84-mer:5'-TAGATAGGCACGCGA..TGG-3',
 SP_55_rev 75-mer:5'-GTAGGGCAGCCAGGC..TGG-3',
 SP_56_rev 78-mer:5'-TAAGCAAGCTGGCTA..TGG-3',
 SP_57_rev 69-mer:5'-CAAGTAGAGCAGTGA..TGG-3',
 SP_58_rev 69-mer:5'-GTGCCAGAGCAAGGG..TGG-3',
 SP_59_rev 84-mer:5'-GGGCAGTGAAAAGGC..TGG-3',
 SP_60_rev 78-mer:5'-TCAGAAGGCTCGCGG..TGG-3',
 SP_61_rev 75-mer:5'-TCAAAAGAGAGAGAG..TGG-3',
 SP_62_rev 72-mer:5'-AAGCTGTTGCCAGGA..TGG-3',
 SP_63_rev 72-mer:5'-TGAACAGGCTAGCTG..TGG-3',
 SP_64_rev 69-mer:5'-CGGTGGAAGCTGCGA..TGG-3',
 SP_65_rev 78-mer:5'-AGGTCGCGCTCAGAG..TGG-3',
 SP_66_rev 78-mer:5'-CGATGTTTGCGAGAG..TGG-3',
 SP_67_rev 78-mer:5'-TGAACAAGGCGAGGC..TGG-3',
 SP_68_rev 75-mer:5'-AAAAAAGGCTGGTGC..TGG-3',
 SP_69_rev 72-mer:5'-TAGCGGACAGGCCGG..TGG-3',
 SP_70_rev 81-mer:5'-GTACGAGAAGAACGC..TGG-3',
 SP_71_rev 69-mer:5'-TCAGGAGTAGAGCGC..TGG-3',
 SP_72_rev 69-mer:5'-GCGCGGCGCCGAGCA..TGG-3',
 SP_73_rev 78-mer:5'-GGGCCAAAGAGGCTG..TGG-3',
 SP_74_rev 60-mer:5'-TAGCCAGAAGCGCTG..TGG-3',
 SP_75_rev 72-mer:5'-TCAGGATTGCCAAAG..TGG-3',
 SP_76_rev 72-mer:5'-GCAGCAATGCGCCTA..TGG-3',
 SP_77_rev 66-mer:5'-GGACGATGGCGCCGA..TGG-3',
 SP_78_rev 75-mer:5'-AGAACAAAGCAGTGG..TGG-3',
 SP_79_rev 72-mer:5'-ACAGAGAAAGGCCCA..TGG-3',
 SP_80_rev 75-mer:5'-TCACCGCTAGAAGAG..TGG-3',
 SP_81_rev 84-mer:5'-TGGAGAGGCCTAGCA..TGG-3',
 SP_82_rev 75-mer:5'-TCAAGGATGCGAGGA..TGG-3',
 SP_83_rev 78-mer:5'-AAGGAGTCAATAGTG..TGG-3']

In [27]:
final_sample['fwd_primers(5-3)']= forward_primers
final_sample['rev_primers(5-3)']= reverse_primers
final_sample

,SecretoGen_ID,Sequence,Perplexity,Length,codon_optimized_sequences,sp_name,fwd_primers(5-3),rev_primers(5-3)
0,SP_997,MRPTLLALGVISFALTLHS,7.515804,19,ATGCGCCCTACTCTCCTTGCCCTAGGCGTCATCAGCTTCGCTCTGA...,SP_0,TCCTTGCCCTAGGCGTCATCAGCTTCGCTCTGACCTTGCATTCCGC...,GAGCGAAGCTGATGACGCCTAGGGCAAGGAGAGTAGGGCGCATGGT...
1,SP_944,MKFTLIILIIVILTIIFSPGALA,7.421489,23,ATGAAGTTCACCTTGATAATCCTCATTATCGTCATCCTTACTATTA...,SP_1,TTATCGTCATCCTTACTATTATTTTTTCCCCTGGCGCCCTGGCTGC...,GGGAAAAAATAATAGTAAGGATGACGATAATGAGGATTATCAAGGT...
2,SP_948,MKVTLSLLAVFLAALSASAIPANG,7.179219,24,ATGAAGGTCACCCTGTCTCTATTGGCCGTGTTCCTCGCGGCCCTTA...,SP_2,TGTTCCTCGCGGCCCTTAGCGCTTCCGCTATCCCTGCAAACGGCGC...,TAGCGGAAGCGCTAAGGGCCGCGAGGAACACGGCCAATAGAGACAG...
3,SP_993,MKAIIILLLIILTLALTVQG,7.140379,20,ATGAAGGCTATAATTATCCTCTTACTGATCATTCTTACCCTAGCCT...,SP_3,TCCTCTTACTGATCATTCTTACCCTAGCCTTGACTGTCCAGGGCGC...,AGGCTAGGGTAAGAATGATCAGTAAGAGGATAATTATAGCCTTCAT...
4,SP_204,MRVFSATAILALSPLLIASASP,6.925975,22,ATGCGCGTCTTCTCCGCCACCGCCATTCTCGCTCTGTCGCCTTTGC...,SP_4,CCATTCTCGCTCTGTCGCCTTTGCTTATCGCGTCTGCAAGCCCCGC...,CGATAAGCAAAGGCGACAGAGCGAGAATGGCGGTGGCGGAGAAGAC...
...,...,...,...,...,...,...,...,...
79,SP_952,MRVSTIPTALLGLSLSAVNA,3.271387,20,ATGCGCGTGAGCACCATCCCTACTGCTCTCTTGGGCCTTTCTCTGT...,SP_79,TCCCTACTGCTCTCTTGGGCCTTTCTCTGTCCGCAGTCAACGCCGC...,ACAGAGAAAGGCCCAAGAGAGCAGTAGGGATGGTGCTCACGCGCAT...
80,SP_659,MVRLNSITALASLLAVSLTAA,3.640410,21,ATGGTCCGCCTGAACTCCATCACCGCACTCGCTTCTCTTCTAGCGG...,SP_80,TCACCGCACTCGCTTCTCTTCTAGCGGTGAGCTTGACTGCCGCCGC...,TCACCGCTAGAAGAGAAGCGAGTGCGGTGATGGAGTTCAGGCGGAC...
81,SP_576,MILSYRSLVVTTVALLGLSTPATA,3.873739,24,ATGATCCTGTCTTACCGCAGCCTTGTTGTGACAACTGTCGCTTTGC...,SP_81,TGACAACTGTCGCTTTGCTAGGCCTCTCCACGCCTGCCACCGCAGC...,TGGAGAGGCCTAGCAAAGCGACAGTTGTCACAACAAGGCTGCGGTA...
82,SP_560,MVLLKPLLATALLASLTPAVA,3.045672,21,ATGGTGCTACTGAAGCCCCTTCTGGCTACTGCCCTCCTCGCATCCT...,SP_82,TTCTGGCTACTGCCCTCCTCGCATCCTTGACCCCTGCCGTCGCGGC...,TCAAGGATGCGAGGAGGGCAGTAGCCAGAAGGGGCTTCAGTAGCAC...
83,SP_256,MVHLKTLALAVSALLTPSIVSA,3.073488,22,ATGGTCCATCTGAAGACCCTCGCGCTTGCTGTGTCCGCACTATTGA...,SP_83,CGCTTGCTGTGTCCGCACTATTGACTCCTTCTATCGTTAGCGCCGC...,AAGGAGTCAATAGTGCGGACACAGCAAGCGCGAGGGTCTTCAGATG...

For IDT:

In [28]:
fwd_name = [seq.name for seq in forward_ovh_list]
fwd_seq = [str(seq.seq) for seq in forward_ovh_list]

rev_name = [seq.name for seq in reverse_ovh_list]
rev_seq = [str(seq.seq) for seq in reverse_ovh_list]

In [29]:
forward_primers_well_plate = pd.read_excel('../data/example_plate-file-upload (1).xls')[:84]
forward_primers_well_plate['Name'] = fwd_name
forward_primers_well_plate['Sequence'] = fwd_seq

forward_primers_well_plate

   Well Position       Name                                           Sequence
0             A1   SP_0_fwd  TCCTTGCCCTAGGCGTCATCAGCTTCGCTCTGACCTTGCATTCCGC...
1             A2   SP_1_fwd  TTATCGTCATCCTTACTATTATTTTTTCCCCTGGCGCCCTGGCTGC...
2             A3   SP_2_fwd  TGTTCCTCGCGGCCCTTAGCGCTTCCGCTATCCCTGCAAACGGCGC...
3             A4   SP_3_fwd  TCCTCTTACTGATCATTCTTACCCTAGCCTTGACTGTCCAGGGCGC...
4             A5   SP_4_fwd  CCATTCTCGCTCTGTCGCCTTTGCTTATCGCGTCTGCAAGCCCCGC...
..           ...        ...                                                ...
79            G8  SP_79_fwd  TCCCTACTGCTCTCTTGGGCCTTTCTCTGTCCGCAGTCAACGCCGC...
80            G9  SP_80_fwd  TCACCGCACTCGCTTCTCTTCTAGCGGTGAGCTTGACTGCCGCCGC...
81           G10  SP_81_fwd  TGACAACTGTCGCTTTGCTAGGCCTCTCCACGCCTGCCACCGCAGC...
82           G11  SP_82_fwd  TTCTGGCTACTGCCCTCCTCGCATCCTTGACCCCTGCCGTCGCGGC...
83           G12  SP_83_fwd  CGCTTGCTGTGTCCGCACTATTGACTCCTTCTATCGTTAGCGCCGC...

[84 rows x 3 columns]

In [30]:
reverse_primers_well_plate = pd.read_excel('../data/example_plate-file-upload (1).xls')[:84]
reverse_primers_well_plate['Name'] = rev_name
reverse_primers_well_plate['Sequence'] = rev_seq

reverse_primers_well_plate

   Well Position       Name                                           Sequence
0             A1   SP_0_rev  GAGCGAAGCTGATGACGCCTAGGGCAAGGAGAGTAGGGCGCATGGT...
1             A2   SP_1_rev  GGGAAAAAATAATAGTAAGGATGACGATAATGAGGATTATCAAGGT...
2             A3   SP_2_rev  TAGCGGAAGCGCTAAGGGCCGCGAGGAACACGGCCAATAGAGACAG...
3             A4   SP_3_rev  AGGCTAGGGTAAGAATGATCAGTAAGAGGATAATTATAGCCTTCAT...
4             A5   SP_4_rev  CGATAAGCAAAGGCGACAGAGCGAGAATGGCGGTGGCGGAGAAGAC...
..           ...        ...                                                ...
79            G8  SP_79_rev  ACAGAGAAAGGCCCAAGAGAGCAGTAGGGATGGTGCTCACGCGCAT...
80            G9  SP_80_rev  TCACCGCTAGAAGAGAAGCGAGTGCGGTGATGGAGTTCAGGCGGAC...
81           G10  SP_81_rev  TGGAGAGGCCTAGCAAAGCGACAGTTGTCACAACAAGGCTGCGGTA...
82           G11  SP_82_rev  TCAAGGATGCGAGGAGGGCAGTAGCCAGAAGGGGCTTCAGTAGCAC...
83           G12  SP_83_rev  AAGGAGTCAATAGTGCGGACACAGCAAGCGCGAGGGTCTTCAGATG...

[84 rows x 3 columns]

In [31]:
forward_primers_well_plate.to_excel('../data/09_primers/forward_primers_2024_09_02.xlsx')
reverse_primers_well_plate.to_excel('../data/09_primers/reverse_primers_2024_09_02.xlsx')
final_sample.to_excel('../data/09_primers/full_dataframe_of_sampled_SPs_2024_09_02.xlsx')