In [90]:
import pandas as pd
from IPython.display import Image
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from pydna.dseqrecord import Dseqrecord

In [91]:
a_oryzae ={
    'F': {'TTT': 0.38, 'TTC': 0.62},
    'S': {'TCT': 0.18, 'TCC': 0.20, 'TCA': 0.14, 'TCG': 0.16, 'AGT': 0.13, 'AGC': 0.18},
    'Y': {'TAT': 0.47, 'TAC': 0.53},
    'C': {'TGT': 0.46, 'TGC': 0.54},
    '*': {'TAA': 0.33, 'TAG': 0.29, 'TGA': 0.38},
    'L': {'TTA': 0.07, 'TTG': 0.18, 'CTT': 0.19, 'CTC': 0.23, 'CTA': 0.11, 'CTG': 0.22},
    'W': {'TGG': 1.00},
    'P': {'CCT': 0.27, 'CCC': 0.26, 'CCA': 0.25, 'CCG': 0.22},
    'H': {'CAT': 0.53, 'CAC': 0.47},
    'Q': {'CAA': 0.43, 'CAG': 0.57},
    'R': {'CGT': 0.18, 'CGC': 0.23, 'CGA': 0.17, 'CGG': 0.18, 'AGA': 0.13, 'AGG': 0.12},
    'I': {'ATT': 0.36, 'ATC': 0.50, 'ATA': 0.14},
    'M': {'ATG': 1.00},
    'T': {'ACT': 0.24, 'ACC': 0.32, 'ACA': 0.23, 'ACG': 0.20},
    'N': {'AAT': 0.45, 'AAC': 0.55},
    'K': {'AAA': 0.36, 'AAG': 0.64},
    'V': {'GTT': 0.27, 'GTC': 0.33, 'GTA': 0.13, 'GTG': 0.27},
    'A': {'GCT': 0.27, 'GCC': 0.30, 'GCA': 0.23, 'GCG': 0.20},
    'D': {'GAT': 0.53, 'GAC': 0.47},
    'E': {'GAA': 0.44, 'GAG': 0.56},
    'G': {'GGT': 0.28, 'GGC': 0.31, 'GGA': 0.24, 'GGG': 0.17}
}

### SPs

In [92]:
sp_df = pd.read_csv('../data/15_SecretoGen/Best_signal_peptides_for_A_oryzae_RFP_his_tag_sorted.csv')
sp_df = sp_df.rename(columns={"SP_ID": "SecretoGen_ID"})

sp_df

    SecretoGen_ID                  Sequence  Perplexity
0          SP_997       MRPTLLALGVISFALTLHS    7.515804
1          SP_944   MKFTLIILIIVILTIIFSPGALA    7.421489
2          SP_948  MKVTLSLLAVFLAALSASAIPANG    7.179219
3          SP_993      MKAIIILLLIILTLALTVQG    7.140379
4          SP_204    MRVFSATAILALSPLLIASASP    6.925975
..            ...                       ...         ...
995        SP_656      MVLGILTITAIPTVTGLANA    1.597785
996        SP_696      MVLGLLTIAAIPTVTGVAQA    1.563614
997        SP_757   MVLGLLTIAAIPTVTGVGNAVSA    1.554127
998        SP_253      MVLGILTITAIPTVTGVAQA    1.535361
999         SP_13      MVLGILTITAIPTVTGVANA    1.530345

[1000 rows x 3 columns]

In [93]:
sp_df

    SecretoGen_ID                  Sequence  Perplexity
0          SP_997       MRPTLLALGVISFALTLHS    7.515804
1          SP_944   MKFTLIILIIVILTIIFSPGALA    7.421489
2          SP_948  MKVTLSLLAVFLAALSASAIPANG    7.179219
3          SP_993      MKAIIILLLIILTLALTVQG    7.140379
4          SP_204    MRVFSATAILALSPLLIASASP    6.925975
..            ...                       ...         ...
995        SP_656      MVLGILTITAIPTVTGLANA    1.597785
996        SP_696      MVLGLLTIAAIPTVTGVAQA    1.563614
997        SP_757   MVLGLLTIAAIPTVTGVGNAVSA    1.554127
998        SP_253      MVLGILTITAIPTVTGVAQA    1.535361
999         SP_13      MVLGILTITAIPTVTGVANA    1.530345

[1000 rows x 3 columns]

How many SPs are longer than 26?

In [94]:
# Adding the length of sequences to the dataframe
sp_df['Length'] = sp_df['Sequence'].apply(len)

# Removing sequences with length over 26
filtered_df = sp_df[sp_df['Length'] <= 26]
filtered_df

    SecretoGen_ID                  Sequence  Perplexity  Length
0          SP_997       MRPTLLALGVISFALTLHS    7.515804      19
1          SP_944   MKFTLIILIIVILTIIFSPGALA    7.421489      23
2          SP_948  MKVTLSLLAVFLAALSASAIPANG    7.179219      24
3          SP_993      MKAIIILLLIILTLALTVQG    7.140379      20
4          SP_204    MRVFSATAILALSPLLIASASP    6.925975      22
..            ...                       ...         ...     ...
995        SP_656      MVLGILTITAIPTVTGLANA    1.597785      20
996        SP_696      MVLGLLTIAAIPTVTGVAQA    1.563614      20
997        SP_757   MVLGLLTIAAIPTVTGVGNAVSA    1.554127      23
998        SP_253      MVLGILTITAIPTVTGVAQA    1.535361      20
999         SP_13      MVLGILTITAIPTVTGVANA    1.530345      20

[998 rows x 4 columns]

In [95]:

# Getting the top 30
top_30 = sp_df.head(30)
#bottom_23 = sp_df.tail(23)

# Sampling the remaining dataframe for a good mix
remaining_sample_size = 84 - 30
remaining_sample = sp_df.iloc[30:].sample(n=remaining_sample_size, random_state=1)

# Combining the top 30 with the remaining sample
final_sample = pd.concat([top_30, remaining_sample]).reset_index(drop=True)
final_sample

   SecretoGen_ID                  Sequence  Perplexity  Length
0         SP_997       MRPTLLALGVISFALTLHS    7.515804      19
1         SP_944   MKFTLIILIIVILTIIFSPGALA    7.421489      23
2         SP_948  MKVTLSLLAVFLAALSASAIPANG    7.179219      24
3         SP_993      MKAIIILLLIILTLALTVQG    7.140379      20
4         SP_204    MRVFSATAILALSPLLIASASP    6.925975      22
..           ...                       ...         ...     ...
79        SP_952      MRVSTIPTALLGLSLSAVNA    3.271387      20
80        SP_659     MVRLNSITALASLLAVSLTAA    3.640410      21
81        SP_576  MILSYRSLVVTTVALLGLSTPATA    3.873739      24
82        SP_560     MVLLKPLLATALLASLTPAVA    3.045672      21
83        SP_256    MVHLKTLALAVSALLTPSIVSA    3.073488      22

[84 rows x 4 columns]

In [96]:
list_already_made_sequences = final_sample['Sequence'].to_list()
list_already_made_sequences

['MRPTLLALGVISFALTLHS',
 'MKFTLIILIIVILTIIFSPGALA',
 'MKVTLSLLAVFLAALSASAIPANG',
 'MKAIIILLLIILTLALTVQG',
 'MRVFSATAILALSPLLIASASP',
 'MRLVSLLTILGTAITTASA',
 'MRPLAITLGLATTIFNPITTASL',
 'MRVLGISSIILTTLVSTTLA',
 'MRPTSSAFVSILGFAAIATA',
 'MKIPFLLSAALLTTLSLFSTSTTLA',
 'MLTTLIQYTLLVSLLFGSPAAS',
 'MKTILPVLLSAITALASPAFA',
 'MRLFHLIVLATVLSLTIA',
 'MRLSAAFILGLSSTVIA',
 'MLPTLLRLFGLLAISLVAVAIA',
 'MRFSLLAVLSIALGLLVQA',
 'MRLITFLTTILALVLVSLCQA',
 'MRSFAFLLAVVLLSVVGLASA',
 'MRFFASLIIIASLLAATIA',
 'MRLSLGFILGTLTLVNA',
 'MKLILFTLIALSLFQLSLA',
 'MLSSSARWAFLLTTIIGLLLCLHNPIVA',
 'MLSSSVLLRIALLALLLALCVG',
 'MILTYFLIAALLLSLTAA',
 'MRSFISLVGILLTLALYVHS',
 'MRFTSLSALALGALVITSVAA',
 'MKLSNFVTTLVLSTPFASA',
 'MLLRYLLTVVLAVGLVLS',
 'MRFFSSVLTALAALTTSVVG',
 'MIPYTLAALVVACLSTLSLA',
 'MVLTKLSVLATALLGLSAQAIA',
 'MRPVSILATVLGLANLATA',
 'MVLTKSLLVLSTIAAQALA',
 'MILSNTILVATLAALSGLAHA',
 'MIFTRLIQLLCAALLLALVLQVQA',
 'MRSSALLTALVVLLGCISNAAA',
 'MRISIPLITAVLSTASA',
 'MVALQKLLLLTALASLSPTVA',
 'MVHFKALATAVLASLLSPTLA',
 'MLVPKLSALLLGALLPTVVSA',
 'MVRLGFFSLLATIPLALS',
 'MRFTLASLALLAIANTVVSA',
 'MVAIKSLLTAALAALSITPALA',
 'MVSIKNLALFVTTLLGCSQA',
 'MILSRILSATLVALALCLFNQATA',
 'MKTFIPFVALLSTISSLCAA',
 'MVHIKPLLATALAALSPLATA',
 'MLVKSIVSTLLALSLSSGLANA',
 'MVRLSLLASALLVASSTLA',
 'MRSLLLSVLFTVLFAILATA',
 'MLIRSIATLAVLGLSQTALS',
 'MVSQKLLSLATILALASLGQA',
 'MVALKHILTALLALSPLATA',
 'MIVTRFLSTLLLAASLSAANA',
 'MVLGITSKALAISLLACLSTPSTA',
 'MLLPTVTLLSVGLAALQPALA',
 'MVHIKPFATVALLASLLTPSLA',
 'MILRWTLVLLTALLALAYQ',
 'MVRIGISTLALALAHLVTS',
 'MRIIPSIGTLLTTVSLFTAHGTAA',
 'MVQLKSFLAVTATASLLTLSNA',
 'MILSKLLTTVAALSLLTPSVA',
 'MVHIKSFVTGLLATASTVTA',
 'MVQLTHLVALAASLFTLSVA',
 'MLFSSLIVTLAASTALSSA',
 'MILPHITTLLAIALSATSSALP',
 'MVSFKQIALLVTTLANIGLSTA',
 'MILSRISALLVLGLALFTQSLA',
 'MVQLKSFALLLGTSLFSSALA',
 'MVLPKIALLVTGLSATLANA',
 'MLPKIIHLLVALLSVLLVQLSVA',
 'MLSILKAALCALLLTPSLA',
 'MVSTKFLLTLLGAAPLALA',
 'MVAIKSLLVSLLAASLAPLATA',
 'MRFLAVAALLATTASA',
 'MVRLSHILTTALAILSPAVA',
 'MVHIKSLAVALGALLPTALA',
 'MLLPRLFYLGAIVPTVLS',
 'MVQIKSLALVLSTALFSSTLA',
 'MRVSTIPTALLGLSLSAVNA',
 'MVRLNSITALASLLAVSLTAA',
 'MILSYRSLVVTTVALLGLSTPATA',
 'MVLLKPLLATALLASLTPAVA',
 'MVHLKTLALAVSALLTPSIVSA']

In [97]:

# Step 1: Filter out sequences that are already in the exclusion list
filtered_df = filtered_df[~filtered_df['Sequence'].isin(list_already_made_sequences)]

# Step 2: Sort the filtered DataFrame by 'Perplexity' in ascending order
sorted_df = filtered_df.sort_values(by='Perplexity', ascending=False)

# Step 3: Select the top `n` rows
selected_rows = sorted_df.tail(23).reset_index(drop=True)

selected_rows

   SecretoGen_ID                  Sequence  Perplexity  Length
0         SP_462       MVAIKSLLLTALLATQAWA    2.045515      19
1         SP_201   MVQIKSFAVLATAISLLSTPAAA    2.045189      23
2          SP_58     MVHIKSLATALLASLAPFATA    2.038901      21
3         SP_182    MVHIKSLATAVLATSFLSPALA    2.015560      22
4         SP_269     MVQITQFLSVALAALSPLATA    2.012376      21
5          SP_45       MVAIKSLLVSGLLTTASLA    1.935643      19
6         SP_108       MVAIKSLLLSGLLATQAWA    1.925576      19
7         SP_105       MVLGLITIAIPTITGLAQA    1.912110      19
8         SP_978     MVLIKPLLTTALAVSAPLAQA    1.898729      21
9         SP_423  MVLIKPLLTTALLASASLLSPATA    1.860671      24
10        SP_521   MVQIKSFAVLATAISLLSPLATA    1.860139      23
11        SP_429    MVLIKPLLATALASLFSSQGLA    1.856135      22
12        SP_765  MVLIKPLVTAALAGLSLLTSHATA    1.841506      24
13        SP_925  MVLIKPFVTAALAGLSLLSSHVAA    1.834244      24
14        SP_231      MVLGLLTIAIIPTITGLAQA    1.732299      20
15        SP_438      MVLGILTIAIAPTITGLAQA    1.705283      20
16        SP_727      MVLGILTIAITPTVIGTAEA    1.666517      20
17        SP_701      MVLGILTIAITPTVIGTAEA    1.666517      20
18        SP_656      MVLGILTITAIPTVTGLANA    1.597785      20
19        SP_696      MVLGLLTIAAIPTVTGVAQA    1.563614      20
20        SP_757   MVLGLLTIAAIPTVTGVGNAVSA    1.554127      23
21        SP_253      MVLGILTITAIPTVTGVAQA    1.535361      20
22         SP_13      MVLGILTITAIPTVTGVANA    1.530345      20

In [98]:
# gettine the sps with lowest perplexity

# Back-translate

In [99]:
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio import SeqIO
from pydna.dseq import Dseq

# Simplified back-translation codon table
back_translation_code = {
        'A': ['GCA', 'GCC', 'GCG', 'GCT'],
        'C': ['TGT', 'TGC'],
        'D': ['GAC', 'GAT'],
        'E': ['GAG', 'GAA'],
        'F': ['TTT', 'TTC'],
        'G': ['GGT', 'GGG', 'GGA', 'GGC'],
        'H': ['CAT', 'CAC'],
        'I': ['ATC', 'ATA', 'ATT'],
        'K': ['AAG', 'AAA'],
        'L': ['CTT', 'CTG', 'CTA', 'CTC', 'TTA', 'TTG'],
        'M': ['ATG'],
        'N': ['AAC', 'AAT'],
        'P': ['CCT', 'CCG', 'CCA', 'CCC'],
        'Q': ['CAA', 'CAG'],
        'R': ['AGG', 'AGA', 'CGA', 'CGC', 'CGG', 'CGT'],
        'S': ['AGC', 'AGT', 'TCT', 'TCG', 'TCC', 'TCA'],
        'T': ['ACA', 'ACG', 'ACT', 'ACC'],
        'V': ['GTA', 'GTC', 'GTG', 'GTT'],
        'W': ['TGG'],
        'Y': ['TAT', 'TAC'],
        '*': ['TAA', 'TGA', 'TAG']
    }


def back_translate(protein_sequence):
    return ''.join([back_translation_code[aa][0] for aa in protein_sequence])

In [100]:

seq_records = []
for index, row in final_sample.iterrows():
    dna_sequence = back_translate(row['Sequence'])
    dseq_obj = Dseq(dna_sequence)
    dseqrecord = Dseqrecord(dseq_obj, name=row['SecretoGen_ID'], description=f"Perplexity: {row['Perplexity']}, Length: {row['Length']}")
    seq_records.append(dseqrecord)

seq_records

[Dseqrecord(-57),
 Dseqrecord(-69),
 Dseqrecord(-72),
 Dseqrecord(-60),
 Dseqrecord(-66),
 Dseqrecord(-57),
 Dseqrecord(-69),
 Dseqrecord(-60),
 Dseqrecord(-60),
 Dseqrecord(-75),
 Dseqrecord(-66),
 Dseqrecord(-63),
 Dseqrecord(-54),
 Dseqrecord(-51),
 Dseqrecord(-66),
 Dseqrecord(-57),
 Dseqrecord(-63),
 Dseqrecord(-63),
 Dseqrecord(-57),
 Dseqrecord(-51),
 Dseqrecord(-57),
 Dseqrecord(-84),
 Dseqrecord(-66),
 Dseqrecord(-54),
 Dseqrecord(-60),
 Dseqrecord(-63),
 Dseqrecord(-57),
 Dseqrecord(-54),
 Dseqrecord(-60),
 Dseqrecord(-60),
 Dseqrecord(-66),
 Dseqrecord(-57),
 Dseqrecord(-57),
 Dseqrecord(-63),
 Dseqrecord(-72),
 Dseqrecord(-66),
 Dseqrecord(-51),
 Dseqrecord(-63),
 Dseqrecord(-63),
 Dseqrecord(-63),
 Dseqrecord(-54),
 Dseqrecord(-60),
 Dseqrecord(-66),
 Dseqrecord(-60),
 Dseqrecord(-72),
 Dseqrecord(-60),
 Dseqrecord(-63),
 Dseqrecord(-66),
 Dseqrecord(-57),
 Dseqrecord(-60),
 Dseqrecord(-60),
 Dseqrecord(-63),
 Dseqrecord(-60),
 Dseqrecord(-63),
 Dseqrecord(-72),
 Dseqrecord(-63),
 Dseqrecord(-66),
 Dseqrecord(-57),
 Dseqrecord(-57),
 Dseqrecord(-72),
 Dseqrecord(-66),
 Dseqrecord(-63),
 Dseqrecord(-60),
 Dseqrecord(-60),
 Dseqrecord(-57),
 Dseqrecord(-66),
 Dseqrecord(-66),
 Dseqrecord(-66),
 Dseqrecord(-63),
 Dseqrecord(-60),
 Dseqrecord(-69),
 Dseqrecord(-57),
 Dseqrecord(-57),
 Dseqrecord(-66),
 Dseqrecord(-48),
 Dseqrecord(-60),
 Dseqrecord(-60),
 Dseqrecord(-54),
 Dseqrecord(-63),
 Dseqrecord(-60),
 Dseqrecord(-63),
 Dseqrecord(-72),
 Dseqrecord(-63),
 Dseqrecord(-66)]

In [101]:
print(seq_records[0].seq)

ATGAGGCCTACACTTCTTGCACTTGGTGTAATCAGCTTTGCACTTACACTTCATAGC

### Codon optimize the sequences:

A. oryzae tax id : 5062

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=5062&lvl=3&lin=f&keep=1&srchmode=1&unlock

In [102]:
# to make the codon optimization reproducible we can initialize a random seed
import numpy as np
np.random.seed(2)

In [103]:
from dnachisel import DnaOptimizationProblem, CodonOptimize, EnforceTranslation, EnforceGCContent

# Codon optimization for Aspergillus oryzae
codon_optimized_records = []
codon_optimized_records_str = []
taxonomy_id = 5062 # a oryzae

for seq in seq_records:
    problem = DnaOptimizationProblem(
        sequence=str(seq.seq),
        constraints=[
            EnforceGCContent(mini=0.3, maxi=0.7, window=len(seq)),
            EnforceTranslation(location=(0, len(seq)))
        ],
        #objectives=[CodonOptimize(codon_usage_table=a_oryzae, method='match_codon_usage')], 
        objectives=[CodonOptimize(species=taxonomy_id, method='match_codon_usage')], 
    )
    problem.resolve_constraints()
    
    problem.optimize()
    # PRINT SUMMARIES TO CHECK THAT CONSTRAINTS PASS
    print(problem.constraints_text_summary())
    print(problem.objectives_text_summary())

    # Save the sequences
    optimized_dna_sequence = str(problem.sequence)
    
    dseq_obj = Dseq(optimized_dna_sequence)
    dseqrecord = Dseqrecord(dseq_obj, name=row['SecretoGen_ID'], description=f"Perplexity: {row['Perplexity']}, Length: {row['Length']}")
    codon_optimized_records.append(dseqrecord)
    codon_optimized_records_str.append(str(dseqrecord.seq))
    
final_sample['codon_optimized_sequences']= codon_optimized_records_str

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -15.55
    -15.55 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.55E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-69](mini:0.30, maxi:0.70, window:69)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-69(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.87
    -12.87 ┍ MatchTargetCodonUsage[0-69](5062)
           │ Codon opt. on window 0-69 scored -1.29E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-72](mini:0.30, maxi:0.70, window:72)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-72(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -14.14
    -14.14 ┍ MatchTargetCodonUsage[0-72](5062)
           │ Codon opt. on window 0-72 scored -1.41E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -10.6
     -10.6 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.06E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.08
    -12.08 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.21E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.53
    -10.53 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.05E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-69](mini:0.30, maxi:0.70, window:69)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-69(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.45
    -12.45 ┍ MatchTargetCodonUsage[0-69](5062)
           │ Codon opt. on window 0-69 scored -1.25E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.58
    -11.58 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.66
    -13.66 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.37E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-75](mini:0.30, maxi:0.70, window:75)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-75(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.97
     -9.97 ┍ MatchTargetCodonUsage[0-75](5062)
           │ Codon opt. on window 0-75 scored -9.97E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -15.14
    -15.14 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.51E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -11.9
     -11.9 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.19E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-54](mini:0.30, maxi:0.70, window:54)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-54(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.66
    -11.66 ┍ MatchTargetCodonUsage[0-54](5062)
           │ Codon opt. on window 0-54 scored -1.17E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.91
    -12.91 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.29E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.97
    -12.97 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.30E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.65
    -12.65 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.26E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.63
    -12.63 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.26E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -8.74
     -8.74 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -8.74E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.88
     -9.88 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -9.88E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.12
    -13.12 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.31E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.31
    -10.31 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.03E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-84](mini:0.30, maxi:0.70, window:84)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-84(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -17.96
    -17.96 ┍ MatchTargetCodonUsage[0-84](5062)
           │ Codon opt. on window 0-84 scored -1.80E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.64
    -11.64 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-54](mini:0.30, maxi:0.70, window:54)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-54(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -7.99
     -7.99 ┍ MatchTargetCodonUsage[0-54](5062)
           │ Codon opt. on window 0-54 scored -7.99E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -14.29
    -14.29 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.43E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.08
    -13.08 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.31E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.88
    -12.88 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.29E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-54](mini:0.30, maxi:0.70, window:54)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-54(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.33
    -11.33 ┍ MatchTargetCodonUsage[0-54](5062)
           │ Codon opt. on window 0-54 scored -1.13E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.39
    -11.39 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.14E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.88
    -11.88 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.19E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.60
    -12.60 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.26E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.22
    -13.22 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.32E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.14
    -10.14 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.01E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.52
    -11.52 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.15E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-72](mini:0.30, maxi:0.70, window:72)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-72(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.80
     -9.80 ┍ MatchTargetCodonUsage[0-72](5062)
           │ Codon opt. on window 0-72 scored -9.80E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.51
    -13.51 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.35E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -13.1
     -13.1 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.31E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.56
    -11.56 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.88
    -11.88 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.19E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.93
    -11.93 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.19E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-54](mini:0.30, maxi:0.70, window:54)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-54(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.94
    -13.94 ┍ MatchTargetCodonUsage[0-54](5062)
           │ Codon opt. on window 0-54 scored -1.39E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.45
    -12.45 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.24E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.48
    -10.48 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.05E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -15.5
     -15.5 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.55E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-72](mini:0.30, maxi:0.70, window:72)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-72(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.93
    -13.93 ┍ MatchTargetCodonUsage[0-72](5062)
           │ Codon opt. on window 0-72 scored -1.39E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.19
    -13.19 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.32E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.57
    -11.57 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.34
    -11.34 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.13E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.10
     -9.10 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -9.10E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.87
    -11.87 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.19E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.44
    -12.44 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.24E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.08
    -11.08 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.11E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.63
    -11.63 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -12.1
     -12.1 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.21E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-72](mini:0.30, maxi:0.70, window:72)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-72(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.57
    -11.57 ┍ MatchTargetCodonUsage[0-72](5062)
           │ Codon opt. on window 0-72 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.77
    -11.77 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.18E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.86
    -12.86 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.29E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.79
    -10.79 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.08E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.87
    -12.87 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.29E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-72](mini:0.30, maxi:0.70, window:72)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-72(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -15.26
    -15.26 ┍ MatchTargetCodonUsage[0-72](5062)
           │ Codon opt. on window 0-72 scored -1.53E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.44
    -10.44 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.04E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.66
    -11.66 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.17E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.04
    -12.04 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.20E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.30
     -9.30 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -9.30E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -8.19
     -8.19 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -8.19E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.42
     -9.42 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -9.42E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.11
    -13.11 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.31E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.77
    -13.77 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.38E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.37
    -11.37 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.14E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.15
    -12.15 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.21E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-69](mini:0.30, maxi:0.70, window:69)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-69(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.60
    -11.60 ┍ MatchTargetCodonUsage[0-69](5062)
           │ Codon opt. on window 0-69 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.63
    -10.63 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.06E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.39
    -11.39 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.14E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.74
    -11.74 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.17E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-48](mini:0.30, maxi:0.70, window:48)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-48(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.30
    -10.30 ┍ MatchTargetCodonUsage[0-48](5062)
           │ Codon opt. on window 0-48 scored -1.03E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.31
    -12.31 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.23E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.24
    -12.24 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.22E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-54](mini:0.30, maxi:0.70, window:54)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-54(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -14.65
    -14.65 ┍ MatchTargetCodonUsage[0-54](5062)
           │ Codon opt. on window 0-54 scored -1.47E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.28
    -11.28 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.13E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -14.88
    -14.88 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.49E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.60
    -11.60 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-72](mini:0.30, maxi:0.70, window:72)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-72(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.72
    -12.72 ┍ MatchTargetCodonUsage[0-72](5062)
           │ Codon opt. on window 0-72 scored -1.27E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.69
    -10.69 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.07E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.01
    -11.01 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.10E+01

## Final sample with sp_name

In [104]:
final_sample['sp_name'] = [f'SP_{i+1}' for i in range(len(final_sample['SecretoGen_ID'].to_list())) ]

In [105]:
with pd.option_context('display.max_rows', None,
                       'display.max_columns', None,
                       'display.precision', 3,
                       'display.width', None,
                       'display.max_colwidth', 1000
                       ):
    print(final_sample)

   SecretoGen_ID                      Sequence  Perplexity  Length  \
0         SP_997           MRPTLLALGVISFALTLHS       7.516      19
1         SP_944       MKFTLIILIIVILTIIFSPGALA       7.421      23
2         SP_948      MKVTLSLLAVFLAALSASAIPANG       7.179      24
3         SP_993          MKAIIILLLIILTLALTVQG       7.140      20
4         SP_204        MRVFSATAILALSPLLIASASP       6.926      22
5         SP_281           MRLVSLLTILGTAITTASA       6.789      19
6         SP_945       MRPLAITLGLATTIFNPITTASL       6.691      23
7         SP_914          MRVLGISSIILTTLVSTTLA       6.568      20
8         SP_662          MRPTSSAFVSILGFAAIATA       6.221      20
9         SP_849     MKIPFLLSAALLTTLSLFSTSTTLA       6.168      25
10        SP_337        MLTTLIQYTLLVSLLFGSPAAS       6.111      22
11        SP_249         MKTILPVLLSAITALASPAFA       6.103      21
12        SP_989            MRLFHLIVLATVLSLTIA       6.005      18
13        SP_847             MRLSAAFILGLSSTVIA       5.995      17
14        SP_549        MLPTLLRLFGLLAISLVAVAIA       5.975      22
15        SP_117           MRFSLLAVLSIALGLLVQA       5.955      19
16        SP_745         MRLITFLTTILALVLVSLCQA       5.886      21
17        SP_906         MRSFAFLLAVVLLSVVGLASA       5.863      21
18        SP_457           MRFFASLIIIASLLAATIA       5.837      19
19        SP_219             MRLSLGFILGTLTLVNA       5.741      17
20        SP_882           MKLILFTLIALSLFQLSLA       5.728      19
21        SP_410  MLSSSARWAFLLTTIIGLLLCLHNPIVA       5.683      28
22        SP_942        MLSSSVLLRIALLALLLALCVG       5.675      22
23        SP_663            MILTYFLIAALLLSLTAA       5.611      18
24        SP_502          MRSFISLVGILLTLALYVHS       5.543      20
25        SP_425         MRFTSLSALALGALVITSVAA       5.536      21
26        SP_668           MKLSNFVTTLVLSTPFASA       5.516      19
27         SP_33            MLLRYLLTVVLAVGLVLS       5.483      18
28        SP_946          MRFFSSVLTALAALTTSVVG       5.471      20
29         SP_41          MIPYTLAALVVACLSTLSLA       5.436      20
30        SP_459        MVLTKLSVLATALLGLSAQAIA       2.673      22
31        SP_811           MRPVSILATVLGLANLATA       2.846      19
32        SP_741           MVLTKSLLVLSTIAAQALA       2.589      19
33        SP_982         MILSNTILVATLAALSGLAHA       3.497      21
34        SP_472      MIFTRLIQLLCAALLLALVLQVQA       3.092      24
35         SP_97        MRSSALLTALVVLLGCISNAAA       4.877      22
36         SP_71             MRISIPLITAVLSTASA       4.322      17
37         SP_40         MVALQKLLLLTALASLSPTVA       2.655      21
38        SP_121         MVHFKALATAVLASLLSPTLA       2.521      21
39        SP_998         MLVPKLSALLLGALLPTVVSA       2.777      21
40        SP_172            MVRLGFFSLLATIPLALS       3.246      18
41        SP_297          MRFTLASLALLAIANTVVSA       4.072      20
42        SP_137        MVAIKSLLTAALAALSITPALA       2.357      22
43        SP_259          MVSIKNLALFVTTLLGCSQA       2.484      20
44         SP_20      MILSRILSATLVALALCLFNQATA       3.280      24
45        SP_412          MKTFIPFVALLSTISSLCAA       4.954      20
46        SP_227         MVHIKPLLATALAALSPLATA       2.205      21
47        SP_798        MLVKSIVSTLLALSLSSGLANA       3.848      22
48        SP_644           MVRLSLLASALLVASSTLA       3.057      19
49        SP_365          MRSLLLSVLFTVLFAILATA       4.172      20
50        SP_409          MLIRSIATLAVLGLSQTALS       3.160      20
51        SP_426         MVSQKLLSLATILALASLGQA       3.344      21
52        SP_316          MVALKHILTALLALSPLATA       2.439      20
53        SP_298         MIVTRFLSTLLLAASLSAANA       4.404      21
54        SP_653      MVLGITSKALAISLLACLSTPSTA       2.280      24
55        SP_173         MLLPTVTLLSVGLAALQPALA       3.490      21
56        SP_375        MVHIKPFATVALLASLLTPSLA       2.566      22
57          SP_1           MILRWTLVLLTALLALAYQ       3.764      19
58        SP_961           MVRIGISTLALALAHLVTS       3.623      19
59        SP_591      MRIIPSIGTLLTTVSLFTAHGTAA       4.951      24
60        SP_621        MVQLKSFLAVTATASLLTLSNA       2.840      22
61        SP_176         MILSKLLTTVAALSLLTPSVA       3.153      21
62        SP_721          MVHIKSFVTGLLATASTVTA       2.376      20
63        SP_163          MVQLTHLVALAASLFTLSVA       2.739      20
64        SP_148           MLFSSLIVTLAASTALSSA       4.387      19
65        SP_593        MILPHITTLLAIALSATSSALP       5.195      22
66        SP_932        MVSFKQIALLVTTLANIGLSTA       2.780      22
67        SP_131        MILSRISALLVLGLALFTQSLA       3.121      22
68        SP_592         MVQLKSFALLLGTSLFSSALA       3.095      21
69        SP_692          MVLPKIALLVTGLSATLANA       2.180      20
70        SP_703       MLPKIIHLLVALLSVLLVQLSVA       3.150      23
71        SP_255           MLSILKAALCALLLTPSLA       3.511      19
72        SP_388           MVSTKFLLTLLGAAPLALA       2.789      19
73        SP_815        MVAIKSLLVSLLAASLAPLATA       1.961      22
74        SP_857              MRFLAVAALLATTASA       3.476      16
75        SP_819          MVRLSHILTTALAILSPAVA       3.001      20
76        SP_270          MVHIKSLAVALGALLPTALA       2.241      20
77        SP_382            MLLPRLFYLGAIVPTVLS       4.459      18
78        SP_357         MVQIKSLALVLSTALFSSTLA       2.679      21
79        SP_952          MRVSTIPTALLGLSLSAVNA       3.271      20
80        SP_659         MVRLNSITALASLLAVSLTAA       3.640      21
81        SP_576      MILSYRSLVVTTVALLGLSTPATA       3.874      24
82        SP_560         MVLLKPLLATALLASLTPAVA       3.046      21
83        SP_256        MVHLKTLALAVSALLTPSIVSA       3.073      22

                                                               codon_optimized_sequences  \
0                              ATGCGCCCTACTCTCCTGGCCTTGGGCGTCATCTCCTTCGCTCTAACCCTTCATAGC
1                  ATGAAGTTTACCTTGATCATACTCATCATTGTCATTCTGACTATTATCTTCTCCCCTGGCGCCCTTGCT
2               ATGAAGGTGACCCTATCCCTTCTCGCTGTCTTCTTGGCTGCCCTGTCTGCGAGCGCCATCCCTGCAAACGGC
3                           ATGAAGGCCATCATAATTTTGCTACTGATCATTCTCACTCTTGCTTTAACCGTCCAGGGC
4                     ATGCGCGTCTTCAGCGCCACCGCTATTCTGGCACTCTCCCCCTTGCTTATCGCGTCGGCCTCTCCT
5                              ATGCGCCTGGTCAGCCTCTTGACAATTCTTGGCACTGCAATCACCACGGCTTCCGCC
6                  ATGCGCCCCCTGGCCATCACCCTTGGCCTCGCAACGACTATCTTCAACCCTATTACCACAGCTTCCTTG
7                           ATGCGCGTGCTCGGCATTTCTTCCATCATCCTGACAACGCTTGTCAGCACTACCTTGGCC
8                           ATGCGCCCTACTAGCTCCGCCTTTGTCTCTATTCTCGGCTTCGCCGCGATCGCTACCGCA
9            ATGAAGATCCCTTTTCTCCTGTCGGCAGCTTTGCTGACCACTCTCAGCCTTTTCTCCACATCTACCACGCTAGCC
10                    ATGCTTACAACTTTAATCCAGTACACCCTACTGGTCAGCCTCTTGTTCGGCTCTCCTGCTGCCTCC
11                       ATGAAGACTATTTTGCCCGTCCTTCTGTCCGCAATCACCGCCCTCGCGAGCCCTGCTTTCGCC
12                                ATGCGCCTTTTCCATCTGATTGTGTTGGCCACTGTCCTATCCCTCACCATCGCT
13                                   ATGCGCCTCTCCGCAGCTTTCATTCTTGGCCTGTCTAGCACCGTCATCGCC
14                    ATGCTCCCTACCTTGCTACGCCTTTTCGGCCTCCTGGCTATTTCCCTGGTGGCGGTCGCCATCGCA
15                             ATGCGCTTCTCCCTGCTCGCCGTGCTAAGCATCGCTTTGGGCTTACTTGTCCAGGCA
16                       ATGCGCTTAATCACATTCTTGACCACTATTCTCGCTCTTGTCCTAGTGTCCCTGTGCCAGGCC
17                       ATGCGCTCCTTCGCTTTTCTCCTGGCGGTCGTGTTGCTTAGCGTTGTAGGCCTAGCATCTGCC
18                             ATGCGCTTTTTCGCCTCCCTCATAATCATTGCCAGCCTGCTTGCGGCAACCATCGCT
19                                   ATGCGCCTATCCCTCGGTTTCATCCTGGGCACTCTTACCTTGGTCAACGCC
20                             ATGAAGCTCATTCTGTTCACCCTCATCGCCCTTTCCTTGTTTCAGCTAAGCCTGGCT
21  ATGCTCAGCTCCTCTGCACGCTGGGCTTTCCTGTTGACTACCATCATTGGCCTTCTGCTCTGCCTACATAACCCTATCGTCGCC
22                    ATGCTCTCTTCCAGCGTCCTCCTGCGCATCGCTCTGTTAGCCCTTTTGCTTGCACTATGCGTGGGC
23                                ATGATCCTAACCTACTTCCTCATTGCCGCGTTACTTCTGTCCTTGACTGCTGCA
24                          ATGCGCTCCTTCATTTCTCTTGTGGGCATCCTGCTCACCTTGGCCCTATACGTCCATAGC
25                       ATGCGCTTCACCTCCCTCAGCGCATTGGCGCTTGGCGCCCTGGTCATCACTTCTGTGGCTGCC
26                             ATGAAGCTGAGCAACTTCGTCACAACTCTTGTGCTCTCCACCCCTTTTGCTTCTGCC
27                                ATGCTACTGCGCTACCTGCTCACCGTAGTCCTTGCCGTTGGCCTCGTGTTGTCC
28                          ATGCGCTTTTTCTCCAGCGTTCTTACTGCACTGGCCGCTCTCACAACCTCTGTGGTCGGC
29                          ATGATCCCTTACACTTTGGCTGCCCTTGTGGTCGCATGCCTGTCCACCCTAAGCCTCGCG
30                    ATGGTCCTTACCAAGTTATCCGTGCTAGCCACTGCCCTCTTGGGCCTGAGCGCGCAGGCAATCGCT
31                             ATGCGCCCTGTCTCCATCCTTGCAACCGTGCTGGGCCTCGCCAACTTGGCTACTGCG
32                             ATGGTCCTAACCAAGTCCCTCTTGGTGCTGAGCACTATCGCCGCGCAGGCACTTGCT
33                       ATGATCCTAAGCAACACTATTCTGGTCGCAACCTTGGCGGCCCTCTCCGGCCTTGCCCATGCT
34              ATGATTTTCACCCGCCTCATCCAACTCTTATGCGCTGCCTTGCTACTGGCACTGGTCCTTCAGGTGCAGGCG
35                    ATGCGCTCCAGCGCTTTGCTCACCGCCCTTGTCGTGCTGCTAGGCTGCATCTCTAACGCGGCAGCC
36                                   ATGCGCATCTCCATCCCTCTGATTACCGCCGTCCTCAGCACTGCATCTGCT
37                       ATGGTCGCTCTGCAGAAGCTCTTGCTTCTGACCGCACTCGCGTCCCTAAGCCCTACTGTGGCC
38                       ATGGTCCATTTCAAGGCACTTGCTACTGCGGTGCTCGCCAGCCTATTGTCCCCTACCCTGGCC
39                       ATGCTCGTCCCTAAGCTATCCGCTCTGCTCTTGGGCGCACTGCTTCCCACCGTTGTGAGCGCC
40                                ATGGTCCGCCTTGGCTTCTTTAGCCTCCTAGCCACCATCCCTTTGGCTCTGTCC
41                          ATGCGCTTCACCCTCGCGAGCCTGGCCCTTTTGGCTATCGCAAACACTGTCGTGTCCGCC
42                    ATGGTCGCCATCAAGAGCCTACTTACCGCTGCATTGGCTGCCCTGTCCATTACTCCTGCACTCGCG
43                          ATGGTCTCCATCAAGAACCTTGCCCTGTTCGTGACCACTTTGCTCGGCTGCAGCCAGGCT
44              ATGATTCTTTCCCGCATCCTGAGCGCCACCCTCGTCGCGTTGGCTCTATGCTTATTCAACCAGGCCACTGCA
45                          ATGAAGACCTTCATTCCTTTTGTCGCACTTCTCAGCACTATCTCCTCTCTGTGCGCTGCC
46                       ATGGTCCATATCAAGCCCTTGCTAGCGACCGCTCTGGCAGCCCTTTCCCCTCTCGCTACTGCC
47                    ATGTTGGTCAAGTCGATCGTGTCCACCCTCTTAGCCCTGTCACTATCTAGCGGCCTTGCAAACGCT
48                             ATGGTGCGCTTGTCCCTACTCGCCTCGGCGTTACTTGTCGCTAGCTCTACCCTGGCA
49                          ATGCGCAGCTTGCTTCTATCCGTCCTCTTTACTGTGTTATTCGCAATCCTGGCCACCGCT
50                          ATGCTCATCCGCAGCATTGCAACTCTTGCCGTCCTGGGCTTGTCCCAGACCGCTCTATCT
51                       ATGGTCTCCCAAAAGCTACTCAGCTTAGCCACCATCCTTGCTCTGGCGTCTTTGGGCCAGGCA
52                          ATGGTCGCACTTAAGCATATCCTCACTGCTCTGTTAGCGCTATCCCCTTTGGCCACCGCC
53                       ATGATCGTCACCCGCTTCTTGTCTACTCTACTGCTCGCTGCCAGCCTTTCCGCCGCAAACGCG
54              ATGGTCCTCGGCATTACATCCAAGGCTCTGGCCATCTCGTTGCTAGCGTGCCTTAGCACTCCTTCTACCGCA
55                       ATGTTGCTCCCCACTGTGACCCTTCTGTCCGTCGGCCTCGCGGCACTGCAGCCTGCCCTAGCT
56                    ATGGTGCATATCAAGCCCTTCGCCACCGTCGCGCTACTGGCATCCCTTCTCACTCCTAGCTTGGCT
57                             ATGATCTTGCGCTGGACTCTCGTCCTTCTAACCGCCCTGCTGGCACTCGCTTACCAG
58                             ATGGTGCGCATTGGCATCTCCACTTTGGCCCTTGCTCTCGCACATCTGGTCACCAGC
59              ATGCGCATCATTCCTTCCATCGGTACGCTTCTCACAACCGTCAGCCTGTTCACTGCCCATGGCACCGCTGCA
60                    ATGGTCCAGCTAAAGAGCTTCCTCGCGGTGACAGCCACTGCTTCTCTGTTGACCCTTTCCAACGCA
61                       ATGATCCTAAGCAAGTTGCTGACTACCGTCGCAGCTCTCTCCTTACTTACACCTTCTGTGGCC
62                          ATGGTCCATATCAAGTCCTTCGTTACCGGCCTCCTGGCCACTGCAAGCACGGTGACAGCT
63                          ATGGTGCAGCTAACCCATCTTGTCGCTCTCGCGGCAAGCCTGTTCACTTTGTCCGTTGCC
64                             ATGCTCTTCTCGTCCTTGATCGTCACCCTTGCTGCGAGCACTGCCCTGTCATCTGCA
65                    ATGATTCTCCCCCATATCACTACCCTGTTGGCGATCGCTCTATCCGCAACATCTAGCGCCCTTCCT
66                    ATGGTCTCCTTCAAGCAGATTGCTCTGCTTGTGACTACACTCGCAAACATCGGCTTGAGCACCGCC
67                    ATGATTCTGAGCCGCATCTCTGCACTTCTCGTCCTAGGCTTGGCCCTCTTCACCCAGTCCCTGGCT
68                       ATGGTCCAGCTGAAGAGCTTTGCTTTGCTTCTAGGCACCTCGCTCTTCTCTTCCGCCTTAGCA
69                          ATGGTGCTTCCTAAGATCGCGTTGCTGGTCACTGGCCTCTCCGCCACCCTAGCTAACGCA
70                 ATGCTCCCTAAGATCATTCATCTGCTTGTTGCCCTGCTATCCGTATTGTTAGTCCAGCTCAGCGTGGCT
71                             ATGCTTAGCATCCTGAAGGCAGCCCTCTGCGCTCTCCTGCTAACCCCTTCCTTGGCG
72                             ATGGTCTCCACCAAGTTCCTGTTGACTCTATTAGGCGCAGCGCCTCTCGCTCTTGCC
73                    ATGGTCGCTATCAAGTCCCTCCTTGTGAGCTTGCTGGCAGCCTCTTTAGCTCCTCTAGCCACCGCG
74                                      ATGCGCTTCCTGGCTGTCGCTGCCCTTCTCGCCACCACTGCGTCCGCA
75                          ATGGTCCGCTTGTCCCATATTCTCACCACTGCGCTGGCTATCCTTAGCCCTGCCGTGGCA
76                          ATGGTCCATATCAAGTCCCTTGCTGTGGCACTCGGCGCGCTATTGCCTACCGCCCTGGCC
77                                ATGCTGCTTCCTCGCCTCTTCTACTTGGGCGCCATCGTGCCCACCGTCCTATCC
78                       ATGGTCCAGATCAAGTCGCTGGCATTGGTGCTCTCCACCGCTCTTTTCAGCTCTACTCTAGCC
79                          ATGCGCGTCTCTACCATCCCTACTGCCTTGCTCGGCCTTTCCCTGAGCGCAGTGAACGCT
80                       ATGGTCCGCCTCAACAGCATCACTGCATTGGCCTCCCTACTTGCGGTGTCTCTGACCGCTGCC
81              ATGATCCTCAGCTACCGCTCTCTGGTGGTTACAACGGTCGCTCTACTTGGCTTGTCCACTCCTGCAACCGCC
82                       ATGGTGCTCCTCAAGCCCCTTTTGGCAACCGCGCTACTGGCCTCCCTGACTCCTGCTGTCGCC
83                    ATGGTGCATCTTAAGACTTTGGCACTAGCTGTTTCTGCCCTCCTGACCCCTAGCATCGTCTCCGCG

   sp_name
0     SP_1
1     SP_2
2     SP_3
3     SP_4
4     SP_5
5     SP_6
6     SP_7
7     SP_8
8     SP_9
9    SP_10
10   SP_11
11   SP_12
12   SP_13
13   SP_14
14   SP_15
15   SP_16
16   SP_17
17   SP_18
18   SP_19
19   SP_20
20   SP_21
21   SP_22
22   SP_23
23   SP_24
24   SP_25
25   SP_26
26   SP_27
27   SP_28
28   SP_29
29   SP_30
30   SP_31
31   SP_32
32   SP_33
33   SP_34
34   SP_35
35   SP_36
36   SP_37
37   SP_38
38   SP_39
39   SP_40
40   SP_41
41   SP_42
42   SP_43
43   SP_44
44   SP_45
45   SP_46
46   SP_47
47   SP_48
48   SP_49
49   SP_50
50   SP_51
51   SP_52
52   SP_53
53   SP_54
54   SP_55
55   SP_56
56   SP_57
57   SP_58
58   SP_59
59   SP_60
60   SP_61
61   SP_62
62   SP_63
63   SP_64
64   SP_65
65   SP_66
66   SP_67
67   SP_68
68   SP_69
69   SP_70
70   SP_71
71   SP_72
72   SP_73
73   SP_74
74   SP_75
75   SP_76
76   SP_77
77   SP_78
78   SP_79
79   SP_80
80   SP_81
81   SP_82
82   SP_83
83   SP_84

In [106]:
final_sample

,SecretoGen_ID,Sequence,Perplexity,Length,codon_optimized_sequences,sp_name
0,SP_997,MRPTLLALGVISFALTLHS,7.515804,19,ATGCGCCCTACTCTCCTGGCCTTGGGCGTCATCTCCTTCGCTCTAA...,SP_1
1,SP_944,MKFTLIILIIVILTIIFSPGALA,7.421489,23,ATGAAGTTTACCTTGATCATACTCATCATTGTCATTCTGACTATTA...,SP_2
2,SP_948,MKVTLSLLAVFLAALSASAIPANG,7.179219,24,ATGAAGGTGACCCTATCCCTTCTCGCTGTCTTCTTGGCTGCCCTGT...,SP_3
3,SP_993,MKAIIILLLIILTLALTVQG,7.140379,20,ATGAAGGCCATCATAATTTTGCTACTGATCATTCTCACTCTTGCTT...,SP_4
4,SP_204,MRVFSATAILALSPLLIASASP,6.925975,22,ATGCGCGTCTTCAGCGCCACCGCTATTCTGGCACTCTCCCCCTTGC...,SP_5
...,...,...,...,...,...,...
79,SP_952,MRVSTIPTALLGLSLSAVNA,3.271387,20,ATGCGCGTCTCTACCATCCCTACTGCCTTGCTCGGCCTTTCCCTGA...,SP_80
80,SP_659,MVRLNSITALASLLAVSLTAA,3.640410,21,ATGGTCCGCCTCAACAGCATCACTGCATTGGCCTCCCTACTTGCGG...,SP_81
81,SP_576,MILSYRSLVVTTVALLGLSTPATA,3.873739,24,ATGATCCTCAGCTACCGCTCTCTGGTGGTTACAACGGTCGCTCTAC...,SP_82
82,SP_560,MVLLKPLLATALLASLTPAVA,3.045672,21,ATGGTGCTCCTCAAGCCCCTTTTGGCAACCGCGCTACTGGCCTCCC...,SP_83
83,SP_256,MVHLKTLALAVSALLTPSIVSA,3.073488,22,ATGGTGCATCTTAAGACTTTGGCACTAGCTGTTTCTGCCCTCCTGA...,SP_84

In [107]:
duplicate_mask = final_sample.duplicated(subset=['Sequence'], keep=False)

# Step 2: Extract duplicate rows
duplicates = final_sample[duplicate_mask]

# Step 3: Check if any duplicates exist and display results
if not duplicates.empty:
    print("Duplicate Sequences found:")
    print(duplicates)
    print("\n")

    # Optional: Get a list of unique duplicate sequences
    duplicate_sequences = duplicates['Sequence'].unique()
    print("List of duplicated sequences:")
    for seq in duplicate_sequences:
        print(seq)
    print("\n")

    # Optional: Count the number of duplicates for each sequence
    duplicate_counts = duplicates['Sequence'].value_counts()
    print("Number of duplicates for each sequence:")
    print(duplicate_counts)
else:
    print("No duplicate sequences found.")

No duplicate sequences found.

# GEnerating primers

In [108]:
RFP = Dseqrecord(SeqIO.read("../data/10_genetic_parts/parts/RFP_w_B_homolgy.fasta", "fasta"))
pTef = Dseqrecord(SeqIO.read("../data/10_genetic_parts/parts/pTEF_w_A_homology.fasta", "fasta"))
print(f'The lenght of RFP is {len(RFP)}')
print(f'The lenght of pTef is {len(pTef)}')

The lenght of RFP is 1977
The lenght of pTef is 1384

In [109]:
from pydna.amplify import pcr
from pydna.primer import Primer

In [110]:
generic_pTef_fwd = Primer('CGAGACAGCAGAATCACCG') # generic 
generic_pTef_rev = Primer('GGTGAAGGTTGTGTTATGTTTTGTGG') # martis

generic_rfp_fwd = Primer('GCCTCCTCCGAGGACG') # martis
generic_rfp_rev = Primer('GAGGAGAGTGGATGGATAGTCTGG') # generic

## generating the overhangs

In [111]:
reverse_ovh_list = []
forward_ovh_list = []

for index, row in final_sample.iterrows():
    # get the sequence
    seq = str(row['codon_optimized_sequences'])

    # make the overhangs like marti propose: 
    # Forward
    fwd_ovh = seq[-44:] + generic_rfp_fwd
    fwd_ovh.name= f"{str(row['sp_name'])}_fwd"
    fwd_ovh.id = f"{str(row['sp_name'])}_fwd"

    # reverse
    rev_ovh = Seq(seq[:-14]).reverse_complement()+ generic_pTef_rev 
    rev_ovh.name = f"{str(row['sp_name'])}_rev"
    rev_ovh.id = f"{str(row['sp_name'])}_rev"


    forward_ovh_list.append(fwd_ovh)
    reverse_ovh_list.append(rev_ovh)

Amplicons

In [112]:
from pydna.amplify import pcr
from pydna.primer import Primer

pTef_amplicons = []
for i in range(len(reverse_ovh_list)): 
    amplicon = pcr(generic_pTef_fwd, reverse_ovh_list[i], pTef)
    pTef_amplicons.append(amplicon)

In [113]:

RFP_amplicons = []
for i in range(len(forward_ovh_list)): 
    amplicon = pcr(forward_ovh_list[i], generic_rfp_rev, RFP)
    RFP_amplicons.append(amplicon)

# Testing the overlap

In [114]:
id_names= final_sample['sp_name'].to_list()

In [115]:
# changing the names of the amplicons
for i in range(len(pTef_amplicons)):
    pTef_amplicons[i].name =  f'pTef_{pTef_amplicons[i].name }_{id_names[i]}'
    
for i in range(len(RFP_amplicons)):
    RFP_amplicons[i].name =  f'RFP_{RFP_amplicons[i].name }_{id_names[i]}'

In [116]:
from pydna.assembly import Assembly

In [117]:
for i in range(len(RFP_amplicons)): 
    assemblyobj = Assembly([pTef_amplicons[i],RFP_amplicons[i]], limit = 18)
    contig = assemblyobj.assemble_linear()[0]

    print(contig.figure(), '\n')

pTef_929bp_PCR_prod_SP_1|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_1

pTef_941bp_PCR_prod_SP_2|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_2

pTef_944bp_PCR_prod_SP_3|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_3

pTef_932bp_PCR_prod_SP_4|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_4

pTef_938bp_PCR_prod_SP_5|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_5

pTef_929bp_PCR_prod_SP_6|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_6

pTef_941bp_PCR_prod_SP_7|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_7

pTef_932bp_PCR_prod_SP_8|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_8

pTef_932bp_PCR_prod_SP_9|30
                         \/
                         /\
                         30|RFP_2021bp_PCR_prod_SP_9

pTef_947bp_PCR_prod_SP_10|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_10

pTef_938bp_PCR_prod_SP_11|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_11

pTef_935bp_PCR_prod_SP_12|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_12

pTef_926bp_PCR_prod_SP_13|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_13

pTef_923bp_PCR_prod_SP_14|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_14

pTef_938bp_PCR_prod_SP_15|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_15

pTef_929bp_PCR_prod_SP_16|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_16

pTef_935bp_PCR_prod_SP_17|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_17

pTef_935bp_PCR_prod_SP_18|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_18

pTef_929bp_PCR_prod_SP_19|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_19

pTef_923bp_PCR_prod_SP_20|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_20

pTef_929bp_PCR_prod_SP_21|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_21

pTef_956bp_PCR_prod_SP_22|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_22

pTef_938bp_PCR_prod_SP_23|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_23

pTef_926bp_PCR_prod_SP_24|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_24

pTef_932bp_PCR_prod_SP_25|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_25

pTef_935bp_PCR_prod_SP_26|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_26

pTef_929bp_PCR_prod_SP_27|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_27

pTef_926bp_PCR_prod_SP_28|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_28

pTef_932bp_PCR_prod_SP_29|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_29

pTef_932bp_PCR_prod_SP_30|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_30

pTef_938bp_PCR_prod_SP_31|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_31

pTef_929bp_PCR_prod_SP_32|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_32

pTef_929bp_PCR_prod_SP_33|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_33

pTef_935bp_PCR_prod_SP_34|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_34

pTef_944bp_PCR_prod_SP_35|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_35

pTef_938bp_PCR_prod_SP_36|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_36

pTef_923bp_PCR_prod_SP_37|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_37

pTef_935bp_PCR_prod_SP_38|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_38

pTef_935bp_PCR_prod_SP_39|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_39

pTef_935bp_PCR_prod_SP_40|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_40

pTef_926bp_PCR_prod_SP_41|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_41

pTef_932bp_PCR_prod_SP_42|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_42

pTef_938bp_PCR_prod_SP_43|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_43

pTef_932bp_PCR_prod_SP_44|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_44

pTef_944bp_PCR_prod_SP_45|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_45

pTef_932bp_PCR_prod_SP_46|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_46

pTef_935bp_PCR_prod_SP_47|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_47

pTef_938bp_PCR_prod_SP_48|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_48

pTef_929bp_PCR_prod_SP_49|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_49

pTef_932bp_PCR_prod_SP_50|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_50

pTef_932bp_PCR_prod_SP_51|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_51

pTef_935bp_PCR_prod_SP_52|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_52

pTef_932bp_PCR_prod_SP_53|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_53

pTef_935bp_PCR_prod_SP_54|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_54

pTef_944bp_PCR_prod_SP_55|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_55

pTef_935bp_PCR_prod_SP_56|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_56

pTef_938bp_PCR_prod_SP_57|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_57

pTef_929bp_PCR_prod_SP_58|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_58

pTef_929bp_PCR_prod_SP_59|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_59

pTef_944bp_PCR_prod_SP_60|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_60

pTef_938bp_PCR_prod_SP_61|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_61

pTef_935bp_PCR_prod_SP_62|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_62

pTef_932bp_PCR_prod_SP_63|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_63

pTef_932bp_PCR_prod_SP_64|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_64

pTef_929bp_PCR_prod_SP_65|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_65

pTef_938bp_PCR_prod_SP_66|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_66

pTef_938bp_PCR_prod_SP_67|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_67

pTef_938bp_PCR_prod_SP_68|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_68

pTef_935bp_PCR_prod_SP_69|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_69

pTef_932bp_PCR_prod_SP_70|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_70

pTef_941bp_PCR_prod_SP_71|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_71

pTef_929bp_PCR_prod_SP_72|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_72

pTef_929bp_PCR_prod_SP_73|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_73

pTef_938bp_PCR_prod_SP_74|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_74

pTef_920bp_PCR_prod_SP_75|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_75

pTef_932bp_PCR_prod_SP_76|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_76

pTef_932bp_PCR_prod_SP_77|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_77

pTef_926bp_PCR_prod_SP_78|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_78

pTef_935bp_PCR_prod_SP_79|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_79

pTef_932bp_PCR_prod_SP_80|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_80

pTef_935bp_PCR_prod_SP_81|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_81

pTef_944bp_PCR_prod_SP_82|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_82

pTef_935bp_PCR_prod_SP_83|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_83

pTef_938bp_PCR_prod_SP_84|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_84

In [118]:
# changing the names of the amplicons
forward_primers = []
reverse_primers = []

for i in range(len(RFP_amplicons)):
    forward_primers.append(str(RFP_amplicons[i].forward_primer.seq))

for i in range(len(pTef_amplicons)):
    
    reverse_primers.append(str(pTef_amplicons[i].reverse_primer.seq))

In [119]:
forward_ovh_list

[SP_1_fwd 60-mer:5'-TCCTGGCCTTGGGCG..ACG-3',
 SP_2_fwd 60-mer:5'-TCATTGTCATTCTGA..ACG-3',
 SP_3_fwd 60-mer:5'-TCTTCTTGGCTGCCC..ACG-3',
 SP_4_fwd 60-mer:5'-TTTTGCTACTGATCA..ACG-3',
 SP_5_fwd 60-mer:5'-CTATTCTGGCACTCT..ACG-3',
 SP_6_fwd 60-mer:5'-GCCTCTTGACAATTC..ACG-3',
 SP_7_fwd 60-mer:5'-GCCTCGCAACGACTA..ACG-3',
 SP_8_fwd 60-mer:5'-TTTCTTCCATCATCC..ACG-3',
 SP_9_fwd 60-mer:5'-CCGCCTTTGTCTCTA..ACG-3',
 SP_10_fwd 60-mer:5'-TGCTGACCACTCTCA..ACG-3',
 SP_11_fwd 60-mer:5'-ACACCCTACTGGTCA..ACG-3',
 SP_12_fwd 60-mer:5'-TCCTTCTGTCCGCAA..ACG-3',
 SP_13_fwd 60-mer:5'-TCCATCTGATTGTGT..ACG-3',
 SP_14_fwd 60-mer:5'-TCTCCGCAGCTTTCA..ACG-3',
 SP_15_fwd 60-mer:5'-TTTTCGGCCTCCTGG..ACG-3',
 SP_16_fwd 60-mer:5'-TGCTCGCCGTGCTAA..ACG-3',
 SP_17_fwd 60-mer:5'-TGACCACTATTCTCG..ACG-3',
 SP_18_fwd 60-mer:5'-TCCTGGCGGTCGTGT..ACG-3',
 SP_19_fwd 60-mer:5'-CCTCCCTCATAATCA..ACG-3',
 SP_20_fwd 60-mer:5'-TATCCCTCGGTTTCA..ACG-3',
 SP_21_fwd 60-mer:5'-TGTTCACCCTCATCG..ACG-3',
 SP_22_fwd 60-mer:5'-CCATCATTGGCCTTC..ACG-3',
 SP_23_fwd 60-mer:5'-TGCGCATCGCTCTGT..ACG-3',
 SP_24_fwd 60-mer:5'-CCTACTTCCTCATTG..ACG-3',
 SP_25_fwd 60-mer:5'-CTCTTGTGGGCATCC..ACG-3',
 SP_26_fwd 60-mer:5'-GCGCATTGGCGCTTG..ACG-3',
 SP_27_fwd 60-mer:5'-ACTTCGTCACAACTC..ACG-3',
 SP_28_fwd 60-mer:5'-GCTACCTGCTCACCG..ACG-3',
 SP_29_fwd 60-mer:5'-GCGTTCTTACTGCAC..ACG-3',
 SP_30_fwd 60-mer:5'-TGGCTGCCCTTGTGG..ACG-3',
 SP_31_fwd 60-mer:5'-TGCTAGCCACTGCCC..ACG-3',
 SP_32_fwd 60-mer:5'-CCATCCTTGCAACCG..ACG-3',
 SP_33_fwd 60-mer:5'-AGTCCCTCTTGGTGC..ACG-3',
 SP_34_fwd 60-mer:5'-TTCTGGTCGCAACCT..ACG-3',
 SP_35_fwd 60-mer:5'-TATGCGCTGCCTTGC..ACG-3',
 SP_36_fwd 60-mer:5'-CCGCCCTTGTCGTGC..ACG-3',
 SP_37_fwd 60-mer:5'-TCTCCATCCCTCTGA..ACG-3',
 SP_38_fwd 60-mer:5'-TCTTGCTTCTGACCG..ACG-3',
 SP_39_fwd 60-mer:5'-TTGCTACTGCGGTGC..ACG-3',
 SP_40_fwd 60-mer:5'-CCGCTCTGCTCTTGG..ACG-3',
 SP_41_fwd 60-mer:5'-TTGGCTTCTTTAGCC..ACG-3',
 SP_42_fwd 60-mer:5'-CGAGCCTGGCCCTTT..ACG-3',
 SP_43_fwd 60-mer:5'-TTACCGCTGCATTGG..ACG-3',
 SP_44_fwd 60-mer:5'-ACCTTGCCCTGTTCG..ACG-3',
 SP_45_fwd 60-mer:5'-CCCTCGTCGCGTTGG..ACG-3',
 SP_46_fwd 60-mer:5'-CTTTTGTCGCACTTC..ACG-3',
 SP_47_fwd 60-mer:5'-TGCTAGCGACCGCTC..ACG-3',
 SP_48_fwd 60-mer:5'-CCACCCTCTTAGCCC..ACG-3',
 SP_49_fwd 60-mer:5'-CCCTACTCGCCTCGG..ACG-3',
 SP_50_fwd 60-mer:5'-TATCCGTCCTCTTTA..ACG-3',
 SP_51_fwd 60-mer:5'-TTGCAACTCTTGCCG..ACG-3',
 SP_52_fwd 60-mer:5'-TCAGCTTAGCCACCA..ACG-3',
 SP_53_fwd 60-mer:5'-ATATCCTCACTGCTC..ACG-3',
 SP_54_fwd 60-mer:5'-TGTCTACTCTACTGC..ACG-3',
 SP_55_fwd 60-mer:5'-TGGCCATCTCGTTGC..ACG-3',
 SP_56_fwd 60-mer:5'-CCCTTCTGTCCGTCG..ACG-3',
 SP_57_fwd 60-mer:5'-CCACCGTCGCGCTAC..ACG-3',
 SP_58_fwd 60-mer:5'-GGACTCTCGTCCTTC..ACG-3',
 SP_59_fwd 60-mer:5'-GCATCTCCACTTTGG..ACG-3',
 SP_60_fwd 60-mer:5'-TTCTCACAACCGTCA..ACG-3',
 SP_61_fwd 60-mer:5'-TCGCGGTGACAGCCA..ACG-3',
 SP_62_fwd 60-mer:5'-TGACTACCGTCGCAG..ACG-3',
 SP_63_fwd 60-mer:5'-CCTTCGTTACCGGCC..ACG-3',
 SP_64_fwd 60-mer:5'-ATCTTGTCGCTCTCG..ACG-3',
 SP_65_fwd 60-mer:5'-CCTTGATCGTCACCC..ACG-3',
 SP_66_fwd 60-mer:5'-CCCTGTTGGCGATCG..ACG-3',
 SP_67_fwd 60-mer:5'-CTCTGCTTGTGACTA..ACG-3',
 SP_68_fwd 60-mer:5'-CACTTCTCGTCCTAG..ACG-3',
 SP_69_fwd 60-mer:5'-TTGCTTTGCTTCTAG..ACG-3',
 SP_70_fwd 60-mer:5'-TCGCGTTGCTGGTCA..ACG-3',
 SP_71_fwd 60-mer:5'-TTGTTGCCCTGCTAT..ACG-3',
 SP_72_fwd 60-mer:5'-TGAAGGCAGCCCTCT..ACG-3',
 SP_73_fwd 60-mer:5'-AGTTCCTGTTGACTC..ACG-3',
 SP_74_fwd 60-mer:5'-TTGTGAGCTTGCTGG..ACG-3',
 SP_75_fwd 60-mer:5'-GCTTCCTGGCTGTCG..ACG-3',
 SP_76_fwd 60-mer:5'-ATATTCTCACCACTG..ACG-3',
 SP_77_fwd 60-mer:5'-CCCTTGCTGTGGCAC..ACG-3',
 SP_78_fwd 60-mer:5'-CTCGCCTCTTCTACT..ACG-3',
 SP_79_fwd 60-mer:5'-TGGCATTGGTGCTCT..ACG-3',
 SP_80_fwd 60-mer:5'-TCCCTACTGCCTTGC..ACG-3',
 SP_81_fwd 60-mer:5'-TCACTGCATTGGCCT..ACG-3',
 SP_82_fwd 60-mer:5'-TTACAACGGTCGCTC..ACG-3',
 SP_83_fwd 60-mer:5'-TTTTGGCAACCGCGC..ACG-3',
 SP_84_fwd 60-mer:5'-CACTAGCTGTTTCTG..ACG-3']

In [120]:
reverse_ovh_list

[SP_1_rev 69-mer:5'-GAGCGAAGGAGATGA..TGG-3',
 SP_2_rev 81-mer:5'-GGGAGAAGATAATAG..TGG-3',
 SP_3_rev 84-mer:5'-TGGCGCTCGCAGACA..TGG-3',
 SP_4_rev 72-mer:5'-AAGCAAGAGTGAGAA..TGG-3',
 SP_5_rev 78-mer:5'-CGATAAGCAAGGGGG..TGG-3',
 SP_6_rev 69-mer:5'-TGATTGCAGTGCCAA..TGG-3',
 SP_7_rev 81-mer:5'-TAATAGGGTTGAAGA..TGG-3',
 SP_8_rev 72-mer:5'-TGACAAGCGTTGTCA..TGG-3',
 SP_9_rev 72-mer:5'-CGGCGAAGCCGAGAA..TGG-3',
 SP_10_rev 87-mer:5'-ATGTGGAGAAAAGGC..TGG-3',
 SP_11_rev 78-mer:5'-AGCCGAACAAGAGGC..TGG-3',
 SP_12_rev 75-mer:5'-TCGCGAGGGCGGTGA..TGG-3',
 SP_13_rev 66-mer:5'-ATAGGACAGTGGCCA..TGG-3',
 SP_14_rev 63-mer:5'-TAGACAGGCCAAGAA..TGG-3',
 SP_15_rev 78-mer:5'-CCACCAGGGAAATAG..TGG-3',
 SP_16_rev 69-mer:5'-AGCCCAAAGCGATGC..TGG-3',
 SP_17_rev 75-mer:5'-ACACTAGGACAAGAG..TGG-3',
 SP_18_rev 75-mer:5'-CTACAACGCTAAGCA..TGG-3',
 SP_19_rev 69-mer:5'-CAAGCAGGCTGGCAA..TGG-3',
 SP_20_rev 63-mer:5'-TAAGAGTGCCCAGGA..TGG-3',
 SP_21_rev 69-mer:5'-GAAACAAGGAAAGGG..TGG-3',
 SP_22_rev 96-mer:5'-TATGTAGGCAGAGCA..TGG-3',
 SP_23_rev 78-mer:5'-CAAGCAAAAGGGCTA..TGG-3',
 SP_24_rev 66-mer:5'-ACAGAAGTAACGCGG..TGG-3',
 SP_25_rev 72-mer:5'-GGGCCAAGGTGAGCA..TGG-3',
 SP_26_rev 75-mer:5'-TGATGACCAGGGCGC..TGG-3',
 SP_27_rev 69-mer:5'-GGGTGGAGAGCACAA..TGG-3',
 SP_28_rev 66-mer:5'-CAACGGCAAGGACTA..TGG-3',
 SP_29_rev 72-mer:5'-TTGTGAGAGCGGCCA..TGG-3',
 SP_30_rev 72-mer:5'-TGGACAGGCATGCGA..TGG-3',
 SP_31_rev 78-mer:5'-CGCTCAGGCCCAAGA..TGG-3',
 SP_32_rev 69-mer:5'-TGGCGAGGCCCAGCA..TGG-3',
 SP_33_rev 69-mer:5'-CGGCGATAGTGCTCA..TGG-3',
 SP_34_rev 75-mer:5'-CGGAGAGGGCCGCCA..TGG-3',
 SP_35_rev 84-mer:5'-GGACCAGTGCCAGTA..TGG-3',
 SP_36_rev 78-mer:5'-AGATGCAGCCTAGCA..TGG-3',
 SP_37_rev 63-mer:5'-TGAGGACGGCGGTAA..TGG-3',
 SP_38_rev 75-mer:5'-TTAGGGACGCGAGTG..TGG-3',
 SP_39_rev 75-mer:5'-ACAATAGGCTGGCGA..TGG-3',
 SP_40_rev 75-mer:5'-TGGGAAGCAGTGCGC..TGG-3',
 SP_41_rev 66-mer:5'-GGATGGTGGCTAGGA..TGG-3',
 SP_42_rev 72-mer:5'-TGTTTGCGATAGCCA..TGG-3',
 SP_43_rev 78-mer:5'-TAATGGACAGGGCAG..TGG-3',
 SP_44_rev 72-mer:5'-CGAGCAAAGTGGTCA..TGG-3',
 SP_45_rev 84-mer:5'-TGAATAAGCATAGAG..TGG-3',
 SP_46_rev 72-mer:5'-AGGAGATAGTGCTGA..TGG-3',
 SP_47_rev 75-mer:5'-GGGAAAGGGCTGCCA..TGG-3',
 SP_48_rev 78-mer:5'-CGCTAGATAGTGACA..TGG-3',
 SP_49_rev 69-mer:5'-TAGCGACAAGTAACG..TGG-3',
 SP_50_rev 72-mer:5'-TTGCGAATAACACAG..TGG-3',
 SP_51_rev 72-mer:5'-GGGACAAGCCCAGGA..TGG-3',
 SP_52_rev 75-mer:5'-ACGCCAGAGCAAGGA..TGG-3',
 SP_53_rev 72-mer:5'-GGGATAGCGCTAACA..TGG-3',
 SP_54_rev 75-mer:5'-AAAGGCTGGCAGCGA..TGG-3',
 SP_55_rev 84-mer:5'-TGCTAAGGCACGCTA..TGG-3',
 SP_56_rev 75-mer:5'-GCAGTGCCGCGAGGC..TGG-3',
 SP_57_rev 78-mer:5'-TGAGAAGGGATGCCA..TGG-3',
 SP_58_rev 69-mer:5'-CCAGCAGGGCGGTTA..TGG-3',
 SP_59_rev 69-mer:5'-GTGCGAGAGCAAGGG..TGG-3',
 SP_60_rev 84-mer:5'-GGGCAGTGAACAGGC..TGG-3',
 SP_61_rev 78-mer:5'-TCAACAGAGAAGCAG..TGG-3',
 SP_62_rev 75-mer:5'-TAAGTAAGGAGAGAG..TGG-3',
 SP_63_rev 72-mer:5'-TTGCAGTGGCCAGGA..TGG-3',
 SP_64_rev 72-mer:5'-TGAACAGGCTTGCCG..TGG-3',
 SP_65_rev 69-mer:5'-CAGTGCTCGCAGCAA..TGG-3',
 SP_66_rev 78-mer:5'-ATGTTGCGGATAGAG..TGG-3',
 SP_67_rev 78-mer:5'-CGATGTTTGCGAGTG..TGG-3',
 SP_68_rev 78-mer:5'-TGAAGAGGGCCAAGC..TGG-3',
 SP_69_rev 75-mer:5'-AGAAGAGCGAGGTGC..TGG-3',
 SP_70_rev 72-mer:5'-TGGCGGAGAGGCCAG..TGG-3',
 SP_71_rev 81-mer:5'-GGACTAACAATACGG..TGG-3',
 SP_72_rev 69-mer:5'-TTAGCAGGAGAGCGC..TGG-3',
 SP_73_rev 69-mer:5'-GCGCTGCGCCTAATA..TGG-3',
 SP_74_rev 78-mer:5'-GAGCTAAAGAGGCTG..TGG-3',
 SP_75_rev 60-mer:5'-TGGCGAGAAGGGCAG..TGG-3',
 SP_76_rev 72-mer:5'-TAAGGATAGCCAGCG..TGG-3',
 SP_77_rev 72-mer:5'-GCAATAGCGCGCCGA..TGG-3',
 SP_78_rev 66-mer:5'-GCACGATGGCGCCCA..TGG-3',
 SP_79_rev 75-mer:5'-TGAAAAGAGCGGTGG..TGG-3',
 SP_80_rev 72-mer:5'-TCAGGGAAAGGCCGA..TGG-3',
 SP_81_rev 75-mer:5'-ACACCGCAAGTAGGG..TGG-3',
 SP_82_rev 84-mer:5'-TGGACAAGCCAAGTA..TGG-3',
 SP_83_rev 75-mer:5'-TCAGGGAGGCCAGTA..TGG-3',
 SP_84_rev 78-mer:5'-TAGGGGTCAGGAGGG..TGG-3']

In [121]:
final_sample['fwd_primers(5-3)']= forward_primers
final_sample['rev_primers(5-3)']= reverse_primers
final_sample

,SecretoGen_ID,Sequence,Perplexity,Length,codon_optimized_sequences,sp_name,fwd_primers(5-3),rev_primers(5-3)
0,SP_997,MRPTLLALGVISFALTLHS,7.515804,19,ATGCGCCCTACTCTCCTGGCCTTGGGCGTCATCTCCTTCGCTCTAA...,SP_1,TCCTGGCCTTGGGCGTCATCTCCTTCGCTCTAACCCTTCATAGCGC...,GAGCGAAGGAGATGACGCCCAAGGCCAGGAGAGTAGGGCGCATGGT...
1,SP_944,MKFTLIILIIVILTIIFSPGALA,7.421489,23,ATGAAGTTTACCTTGATCATACTCATCATTGTCATTCTGACTATTA...,SP_2,TCATTGTCATTCTGACTATTATCTTCTCCCCTGGCGCCCTTGCTGC...,GGGAGAAGATAATAGTCAGAATGACAATGATGAGTATGATCAAGGT...
2,SP_948,MKVTLSLLAVFLAALSASAIPANG,7.179219,24,ATGAAGGTGACCCTATCCCTTCTCGCTGTCTTCTTGGCTGCCCTGT...,SP_3,TCTTCTTGGCTGCCCTGTCTGCGAGCGCCATCCCTGCAAACGGCGC...,TGGCGCTCGCAGACAGGGCAGCCAAGAAGACAGCGAGAAGGGATAG...
3,SP_993,MKAIIILLLIILTLALTVQG,7.140379,20,ATGAAGGCCATCATAATTTTGCTACTGATCATTCTCACTCTTGCTT...,SP_4,TTTTGCTACTGATCATTCTCACTCTTGCTTTAACCGTCCAGGGCGC...,AAGCAAGAGTGAGAATGATCAGTAGCAAAATTATGATGGCCTTCAT...
4,SP_204,MRVFSATAILALSPLLIASASP,6.925975,22,ATGCGCGTCTTCAGCGCCACCGCTATTCTGGCACTCTCCCCCTTGC...,SP_5,CTATTCTGGCACTCTCCCCCTTGCTTATCGCGTCGGCCTCTCCTGC...,CGATAAGCAAGGGGGAGAGTGCCAGAATAGCGGTGGCGCTGAAGAC...
...,...,...,...,...,...,...,...,...
79,SP_952,MRVSTIPTALLGLSLSAVNA,3.271387,20,ATGCGCGTCTCTACCATCCCTACTGCCTTGCTCGGCCTTTCCCTGA...,SP_80,TCCCTACTGCCTTGCTCGGCCTTTCCCTGAGCGCAGTGAACGCTGC...,TCAGGGAAAGGCCGAGCAAGGCAGTAGGGATGGTAGAGACGCGCAT...
80,SP_659,MVRLNSITALASLLAVSLTAA,3.640410,21,ATGGTCCGCCTCAACAGCATCACTGCATTGGCCTCCCTACTTGCGG...,SP_81,TCACTGCATTGGCCTCCCTACTTGCGGTGTCTCTGACCGCTGCCGC...,ACACCGCAAGTAGGGAGGCCAATGCAGTGATGCTGTTGAGGCGGAC...
81,SP_576,MILSYRSLVVTTVALLGLSTPATA,3.873739,24,ATGATCCTCAGCTACCGCTCTCTGGTGGTTACAACGGTCGCTCTAC...,SP_82,TTACAACGGTCGCTCTACTTGGCTTGTCCACTCCTGCAACCGCCGC...,TGGACAAGCCAAGTAGAGCGACCGTTGTAACCACCAGAGAGCGGTA...
82,SP_560,MVLLKPLLATALLASLTPAVA,3.045672,21,ATGGTGCTCCTCAAGCCCCTTTTGGCAACCGCGCTACTGGCCTCCC...,SP_83,TTTTGGCAACCGCGCTACTGGCCTCCCTGACTCCTGCTGTCGCCGC...,TCAGGGAGGCCAGTAGCGCGGTTGCCAAAAGGGGCTTGAGGAGCAC...
83,SP_256,MVHLKTLALAVSALLTPSIVSA,3.073488,22,ATGGTGCATCTTAAGACTTTGGCACTAGCTGTTTCTGCCCTCCTGA...,SP_84,CACTAGCTGTTTCTGCCCTCCTGACCCCTAGCATCGTCTCCGCGGC...,TAGGGGTCAGGAGGGCAGAAACAGCTAGTGCCAAAGTCTTAAGATG...

For IDT:

In [122]:
fwd_name = [seq.name for seq in forward_ovh_list]
fwd_seq = [str(seq.seq) for seq in forward_ovh_list]

rev_name = [seq.name for seq in reverse_ovh_list]
rev_seq = [str(seq.seq) for seq in reverse_ovh_list]

In [123]:
forward_primers_well_plate = pd.read_excel('../data/example_plate-file-upload (1).xls')[:84]
forward_primers_well_plate['Name'] = fwd_name
forward_primers_well_plate['Sequence'] = fwd_seq

forward_primers_well_plate

   Well Position       Name                                           Sequence
0             A1   SP_1_fwd  TCCTGGCCTTGGGCGTCATCTCCTTCGCTCTAACCCTTCATAGCGC...
1             A2   SP_2_fwd  TCATTGTCATTCTGACTATTATCTTCTCCCCTGGCGCCCTTGCTGC...
2             A3   SP_3_fwd  TCTTCTTGGCTGCCCTGTCTGCGAGCGCCATCCCTGCAAACGGCGC...
3             A4   SP_4_fwd  TTTTGCTACTGATCATTCTCACTCTTGCTTTAACCGTCCAGGGCGC...
4             A5   SP_5_fwd  CTATTCTGGCACTCTCCCCCTTGCTTATCGCGTCGGCCTCTCCTGC...
..           ...        ...                                                ...
79            G8  SP_80_fwd  TCCCTACTGCCTTGCTCGGCCTTTCCCTGAGCGCAGTGAACGCTGC...
80            G9  SP_81_fwd  TCACTGCATTGGCCTCCCTACTTGCGGTGTCTCTGACCGCTGCCGC...
81           G10  SP_82_fwd  TTACAACGGTCGCTCTACTTGGCTTGTCCACTCCTGCAACCGCCGC...
82           G11  SP_83_fwd  TTTTGGCAACCGCGCTACTGGCCTCCCTGACTCCTGCTGTCGCCGC...
83           G12  SP_84_fwd  CACTAGCTGTTTCTGCCCTCCTGACCCCTAGCATCGTCTCCGCGGC...

[84 rows x 3 columns]

In [124]:
reverse_primers_well_plate = pd.read_excel('../data/example_plate-file-upload (1).xls')[:84]
reverse_primers_well_plate['Name'] = rev_name
reverse_primers_well_plate['Sequence'] = rev_seq

reverse_primers_well_plate

   Well Position       Name                                           Sequence
0             A1   SP_1_rev  GAGCGAAGGAGATGACGCCCAAGGCCAGGAGAGTAGGGCGCATGGT...
1             A2   SP_2_rev  GGGAGAAGATAATAGTCAGAATGACAATGATGAGTATGATCAAGGT...
2             A3   SP_3_rev  TGGCGCTCGCAGACAGGGCAGCCAAGAAGACAGCGAGAAGGGATAG...
3             A4   SP_4_rev  AAGCAAGAGTGAGAATGATCAGTAGCAAAATTATGATGGCCTTCAT...
4             A5   SP_5_rev  CGATAAGCAAGGGGGAGAGTGCCAGAATAGCGGTGGCGCTGAAGAC...
..           ...        ...                                                ...
79            G8  SP_80_rev  TCAGGGAAAGGCCGAGCAAGGCAGTAGGGATGGTAGAGACGCGCAT...
80            G9  SP_81_rev  ACACCGCAAGTAGGGAGGCCAATGCAGTGATGCTGTTGAGGCGGAC...
81           G10  SP_82_rev  TGGACAAGCCAAGTAGAGCGACCGTTGTAACCACCAGAGAGCGGTA...
82           G11  SP_83_rev  TCAGGGAGGCCAGTAGCGCGGTTGCCAAAAGGGGCTTGAGGAGCAC...
83           G12  SP_84_rev  TAGGGGTCAGGAGGGCAGAAACAGCTAGTGCCAAAGTCTTAAGATG...

[84 rows x 3 columns]

In [125]:
#forward_primers_well_plate.to_excel('../data/09_primers/forward_primers_2024_09_03.xlsx')
#reverse_primers_well_plate.to_excel('../data/09_primers/reverse_primers_2024_09_03.xlsx')
#final_sample.to_excel('../data/09_primers/full_dataframe_of_sampled_SPs_2024_09_03.xlsx')

In [126]:
final_sample

,SecretoGen_ID,Sequence,Perplexity,Length,codon_optimized_sequences,sp_name,fwd_primers(5-3),rev_primers(5-3)
0,SP_997,MRPTLLALGVISFALTLHS,7.515804,19,ATGCGCCCTACTCTCCTGGCCTTGGGCGTCATCTCCTTCGCTCTAA...,SP_1,TCCTGGCCTTGGGCGTCATCTCCTTCGCTCTAACCCTTCATAGCGC...,GAGCGAAGGAGATGACGCCCAAGGCCAGGAGAGTAGGGCGCATGGT...
1,SP_944,MKFTLIILIIVILTIIFSPGALA,7.421489,23,ATGAAGTTTACCTTGATCATACTCATCATTGTCATTCTGACTATTA...,SP_2,TCATTGTCATTCTGACTATTATCTTCTCCCCTGGCGCCCTTGCTGC...,GGGAGAAGATAATAGTCAGAATGACAATGATGAGTATGATCAAGGT...
2,SP_948,MKVTLSLLAVFLAALSASAIPANG,7.179219,24,ATGAAGGTGACCCTATCCCTTCTCGCTGTCTTCTTGGCTGCCCTGT...,SP_3,TCTTCTTGGCTGCCCTGTCTGCGAGCGCCATCCCTGCAAACGGCGC...,TGGCGCTCGCAGACAGGGCAGCCAAGAAGACAGCGAGAAGGGATAG...
3,SP_993,MKAIIILLLIILTLALTVQG,7.140379,20,ATGAAGGCCATCATAATTTTGCTACTGATCATTCTCACTCTTGCTT...,SP_4,TTTTGCTACTGATCATTCTCACTCTTGCTTTAACCGTCCAGGGCGC...,AAGCAAGAGTGAGAATGATCAGTAGCAAAATTATGATGGCCTTCAT...
4,SP_204,MRVFSATAILALSPLLIASASP,6.925975,22,ATGCGCGTCTTCAGCGCCACCGCTATTCTGGCACTCTCCCCCTTGC...,SP_5,CTATTCTGGCACTCTCCCCCTTGCTTATCGCGTCGGCCTCTCCTGC...,CGATAAGCAAGGGGGAGAGTGCCAGAATAGCGGTGGCGCTGAAGAC...
...,...,...,...,...,...,...,...,...
79,SP_952,MRVSTIPTALLGLSLSAVNA,3.271387,20,ATGCGCGTCTCTACCATCCCTACTGCCTTGCTCGGCCTTTCCCTGA...,SP_80,TCCCTACTGCCTTGCTCGGCCTTTCCCTGAGCGCAGTGAACGCTGC...,TCAGGGAAAGGCCGAGCAAGGCAGTAGGGATGGTAGAGACGCGCAT...
80,SP_659,MVRLNSITALASLLAVSLTAA,3.640410,21,ATGGTCCGCCTCAACAGCATCACTGCATTGGCCTCCCTACTTGCGG...,SP_81,TCACTGCATTGGCCTCCCTACTTGCGGTGTCTCTGACCGCTGCCGC...,ACACCGCAAGTAGGGAGGCCAATGCAGTGATGCTGTTGAGGCGGAC...
81,SP_576,MILSYRSLVVTTVALLGLSTPATA,3.873739,24,ATGATCCTCAGCTACCGCTCTCTGGTGGTTACAACGGTCGCTCTAC...,SP_82,TTACAACGGTCGCTCTACTTGGCTTGTCCACTCCTGCAACCGCCGC...,TGGACAAGCCAAGTAGAGCGACCGTTGTAACCACCAGAGAGCGGTA...
82,SP_560,MVLLKPLLATALLASLTPAVA,3.045672,21,ATGGTGCTCCTCAAGCCCCTTTTGGCAACCGCGCTACTGGCCTCCC...,SP_83,TTTTGGCAACCGCGCTACTGGCCTCCCTGACTCCTGCTGTCGCCGC...,TCAGGGAGGCCAGTAGCGCGGTTGCCAAAAGGGGCTTGAGGAGCAC...
83,SP_256,MVHLKTLALAVSALLTPSIVSA,3.073488,22,ATGGTGCATCTTAAGACTTTGGCACTAGCTGTTTCTGCCCTCCTGA...,SP_84,CACTAGCTGTTTCTGCCCTCCTGACCCCTAGCATCGTCTCCGCGGC...,TAGGGGTCAGGAGGGCAGAAACAGCTAGTGCCAAAGTCTTAAGATG...

In [127]:
# Check for final sample and random seed is the same

old_df = pd.read_excel('../data/09_primers/full_dataframe_of_sampled_SPs_2024_08_02.xlsx')
old_df

,Unnamed: 0,SecretoGen_ID,Sequence,Perplexity,Length,codon_optimized_sequences,sp_name,fwd_primers(5-3),rev_primers(5-3)
0,0,SP_997,MRPTLLALGVISFALTLHS,7.515804,19,ATGCGCCCTACTCTCCTGGCCCTAGGCGTCATCTCCTTCGCTTTGA...,SP_0,TCCTGGCCCTAGGCGTCATCTCCTTCGCTTTGACCCTTCATAGCGC...,AAGCGAAGGAGATGACGCCTAGGGCCAGGAGAGTAGGGCGCATGGT...
1,1,SP_944,MKFTLIILIIVILTIIFSPGALA,7.421489,23,ATGAAGTTTACTCTCATTATCTTGATCATCGTCATACTGACCATTA...,SP_1,TCATCGTCATACTGACCATTATTTTCTCCCCTGGCGCCCTTGCTGC...,GGGAGAAAATAATGGTCAGTATGACGATGATCAAGATAATGAGAGT...
2,2,SP_948,MKVTLSLLAVFLAALSASAIPANG,7.179219,24,ATGAAGGTCACCCTTTCTCTGCTCGCTGTGTTCCTAGCTGCATTGA...,SP_2,TGTTCCTAGCTGCATTGAGCGCGTCCGCCATCCCTGCCAACGGCGC...,TGGCGGACGCGCTCAATGCAGCTAGGAACACAGCGAGCAGAGAAAG...
3,3,SP_993,MKAIIILLLIILTLALTVQG,7.140379,20,ATGAAGGCCATCATTATCCTGCTCCTTATAATTTTAACTCTAGCTT...,SP_3,TCCTGCTCCTTATAATTTTAACTCTAGCTTTGACCGTCCAGGGCGC...,AAGCTAGAGTTAAAATTATAAGGAGCAGGATAATGATGGCCTTCAT...
4,4,SP_204,MRVFSATAILALSPLLIASASP,6.925975,22,ATGCGCGTCTTCAGCGCGACCGCAATCCTGGCTCTTTCTCCCTTGC...,SP_4,CAATCCTGGCTCTTTCTCCCTTGCTCATTGCCTCCGCCTCGCCTGC...,CAATGAGCAAGGGAGAAAGAGCCAGGATTGCGGTCGCGCTGAAGAC...
...,...,...,...,...,...,...,...,...,...
79,79,SP_952,MRVSTIPTALLGLSLSAVNA,3.271387,20,ATGCGCGTCAGCACCATCCCTACTGCATTGCTCGGCCTGTCCCTTT...,SP_79,TCCCTACTGCATTGCTCGGCCTGTCCCTTTCTGCTGTGAACGCCGC...,AAAGGGACAGGCCGAGCAATGCAGTAGGGATGGTGCTGACGCGCAT...
80,80,SP_659,MVRLNSITALASLLAVSLTAA,3.640410,21,ATGGTCCGCCTAAACTCTATCACTGCCCTGGCATCCTTGCTCGCCG...,SP_80,TCACTGCCCTGGCATCCTTGCTCGCCGTGAGCCTTACCGCGGCTGC...,TCACGGCGAGCAAGGATGCCAGGGCAGTGATAGAGTTTAGGCGGAC...
81,81,SP_576,MILSYRSLVVTTVALLGLSTPATA,3.873739,24,ATGATCCTGAGCTACCGCTCTCTCGTTGTCACAACCGTGGCCCTAC...,SP_81,TCACAACCGTGGCCCTACTTGGCTTGTCCACTCCTGCTACGGCAGC...,TGGACAAGCCAAGTAGGGCCACGGTTGTGACAACGAGAGAGCGGTA...
82,82,SP_560,MVLLKPLLATALLASLTPAVA,3.045672,21,ATGGTGCTTCTGAAGCCTTTGCTAGCTACCGCGCTCCTGGCCTCCC...,SP_82,TGCTAGCTACCGCGCTCCTGGCCTCCCTCACTCCCGCCGTCGCAGC...,TGAGGGAGGCCAGGAGCGCGGTAGCTAGCAAAGGCTTCAGAAGCAC...
83,83,SP_256,MVHLKTLALAVSALLTPSIVSA,3.073488,22,ATGGTGCATTTGAAGACCCTTGCACTCGCCGTCTCCGCGCTACTGA...,SP_83,CACTCGCCGTCTCCGCGCTACTGACTCCTAGCATCGTTTCTGCTGC...,TAGGAGTCAGTAGCGCGGAGACGGCGAGTGCAAGGGTCTTCAAATG...

In [128]:
# Function to find differences in a specific column between two DataFrames
def find_column_differences(df1, df2, column_name):
    # Check if the specified column exists in both DataFrames
    if column_name not in df1.columns or column_name not in df2.columns:
        print(f"Column '{column_name}' does not exist in both DataFrames.")
        return
    
    # Check if both DataFrames have the same number of rows
    if len(df1) != len(df2):
        print("DataFrames do not have the same number of rows. Exiting comparison.")
        return
    
    # Create a DataFrame to store differences
    diff_df = pd.DataFrame(index=df1.index)
    
    # Find where values differ in the specified column
    mask = df1[column_name] != df2[column_name]
    
    # Store differences in the diff_df
    diff_df[column_name] = df1[column_name].where(mask, other=f"{df1[column_name]} (same)")
    diff_df['Difference'] = df2[column_name].where(mask, other='(same)')
    
    # Remove rows with no differences (all values are marked as 'same')
    diff_df = diff_df[mask]
    
    return diff_df

# Finding and displaying differences in the 'codon_optimized_sequences' column
column_name = 'codon_optimized_sequences'
differences = find_column_differences(final_sample, old_df, column_name)
print(f"Differences in column '{column_name}':")
print(differences)

Differences in column 'codon_optimized_sequences':
                            codon_optimized_sequences  \
0   ATGCGCCCTACTCTCCTGGCCTTGGGCGTCATCTCCTTCGCTCTAA...
1   ATGAAGTTTACCTTGATCATACTCATCATTGTCATTCTGACTATTA...
2   ATGAAGGTGACCCTATCCCTTCTCGCTGTCTTCTTGGCTGCCCTGT...
3   ATGAAGGCCATCATAATTTTGCTACTGATCATTCTCACTCTTGCTT...
4   ATGCGCGTCTTCAGCGCCACCGCTATTCTGGCACTCTCCCCCTTGC...
..                                                ...
79  ATGCGCGTCTCTACCATCCCTACTGCCTTGCTCGGCCTTTCCCTGA...
80  ATGGTCCGCCTCAACAGCATCACTGCATTGGCCTCCCTACTTGCGG...
81  ATGATCCTCAGCTACCGCTCTCTGGTGGTTACAACGGTCGCTCTAC...
82  ATGGTGCTCCTCAAGCCCCTTTTGGCAACCGCGCTACTGGCCTCCC...
83  ATGGTGCATCTTAAGACTTTGGCACTAGCTGTTTCTGCCCTCCTGA...

                                           Difference
0   ATGCGCCCTACTCTCCTGGCCCTAGGCGTCATCTCCTTCGCTTTGA...
1   ATGAAGTTTACTCTCATTATCTTGATCATCGTCATACTGACCATTA...
2   ATGAAGGTCACCCTTTCTCTGCTCGCTGTGTTCCTAGCTGCATTGA...
3   ATGAAGGCCATCATTATCCTGCTCCTTATAATTTTAACTCTAGCTT...
4   ATGCGCGTCTTCAGCGCGACCGCAATCCTGGCTCTTTCTCCCTTGC...
..                                                ...
79  ATGCGCGTCAGCACCATCCCTACTGCATTGCTCGGCCTGTCCCTTT...
80  ATGGTCCGCCTAAACTCTATCACTGCCCTGGCATCCTTGCTCGCCG...
81  ATGATCCTGAGCTACCGCTCTCTCGTTGTCACAACCGTGGCCCTAC...
82  ATGGTGCTTCTGAAGCCTTTGCTAGCTACCGCGCTCCTGGCCTCCC...
83  ATGGTGCATTTGAAGACCCTTGCACTCGCCGTCTCCGCGCTACTGA...

[84 rows x 2 columns]

In [129]:
differences

,codon_optimized_sequences,Difference
0,ATGCGCCCTACTCTCCTGGCCTTGGGCGTCATCTCCTTCGCTCTAA...,ATGCGCCCTACTCTCCTGGCCCTAGGCGTCATCTCCTTCGCTTTGA...
1,ATGAAGTTTACCTTGATCATACTCATCATTGTCATTCTGACTATTA...,ATGAAGTTTACTCTCATTATCTTGATCATCGTCATACTGACCATTA...
2,ATGAAGGTGACCCTATCCCTTCTCGCTGTCTTCTTGGCTGCCCTGT...,ATGAAGGTCACCCTTTCTCTGCTCGCTGTGTTCCTAGCTGCATTGA...
3,ATGAAGGCCATCATAATTTTGCTACTGATCATTCTCACTCTTGCTT...,ATGAAGGCCATCATTATCCTGCTCCTTATAATTTTAACTCTAGCTT...
4,ATGCGCGTCTTCAGCGCCACCGCTATTCTGGCACTCTCCCCCTTGC...,ATGCGCGTCTTCAGCGCGACCGCAATCCTGGCTCTTTCTCCCTTGC...
...,...,...
79,ATGCGCGTCTCTACCATCCCTACTGCCTTGCTCGGCCTTTCCCTGA...,ATGCGCGTCAGCACCATCCCTACTGCATTGCTCGGCCTGTCCCTTT...
80,ATGGTCCGCCTCAACAGCATCACTGCATTGGCCTCCCTACTTGCGG...,ATGGTCCGCCTAAACTCTATCACTGCCCTGGCATCCTTGCTCGCCG...
81,ATGATCCTCAGCTACCGCTCTCTGGTGGTTACAACGGTCGCTCTAC...,ATGATCCTGAGCTACCGCTCTCTCGTTGTCACAACCGTGGCCCTAC...
82,ATGGTGCTCCTCAAGCCCCTTTTGGCAACCGCGCTACTGGCCTCCC...,ATGGTGCTTCTGAAGCCTTTGCTAGCTACCGCGCTCCTGGCCTCCC...
83,ATGGTGCATCTTAAGACTTTGGCACTAGCTGTTTCTGCCCTCCTGA...,ATGGTGCATTTGAAGACCCTTGCACTCGCCGTCTCCGCGCTACTGA...

### We want to sample the top of the dataframe as well so we will take get the top primers from there below

In [130]:
list_already_made_sequences = final_sample['Sequence'].to_list()
list_already_made_sequences

['MRPTLLALGVISFALTLHS',
 'MKFTLIILIIVILTIIFSPGALA',
 'MKVTLSLLAVFLAALSASAIPANG',
 'MKAIIILLLIILTLALTVQG',
 'MRVFSATAILALSPLLIASASP',
 'MRLVSLLTILGTAITTASA',
 'MRPLAITLGLATTIFNPITTASL',
 'MRVLGISSIILTTLVSTTLA',
 'MRPTSSAFVSILGFAAIATA',
 'MKIPFLLSAALLTTLSLFSTSTTLA',
 'MLTTLIQYTLLVSLLFGSPAAS',
 'MKTILPVLLSAITALASPAFA',
 'MRLFHLIVLATVLSLTIA',
 'MRLSAAFILGLSSTVIA',
 'MLPTLLRLFGLLAISLVAVAIA',
 'MRFSLLAVLSIALGLLVQA',
 'MRLITFLTTILALVLVSLCQA',
 'MRSFAFLLAVVLLSVVGLASA',
 'MRFFASLIIIASLLAATIA',
 'MRLSLGFILGTLTLVNA',
 'MKLILFTLIALSLFQLSLA',
 'MLSSSARWAFLLTTIIGLLLCLHNPIVA',
 'MLSSSVLLRIALLALLLALCVG',
 'MILTYFLIAALLLSLTAA',
 'MRSFISLVGILLTLALYVHS',
 'MRFTSLSALALGALVITSVAA',
 'MKLSNFVTTLVLSTPFASA',
 'MLLRYLLTVVLAVGLVLS',
 'MRFFSSVLTALAALTTSVVG',
 'MIPYTLAALVVACLSTLSLA',
 'MVLTKLSVLATALLGLSAQAIA',
 'MRPVSILATVLGLANLATA',
 'MVLTKSLLVLSTIAAQALA',
 'MILSNTILVATLAALSGLAHA',
 'MIFTRLIQLLCAALLLALVLQVQA',
 'MRSSALLTALVVLLGCISNAAA',
 'MRISIPLITAVLSTASA',
 'MVALQKLLLLTALASLSPTVA',
 'MVHFKALATAVLASLLSPTLA',
 'MLVPKLSALLLGALLPTVVSA',
 'MVRLGFFSLLATIPLALS',
 'MRFTLASLALLAIANTVVSA',
 'MVAIKSLLTAALAALSITPALA',
 'MVSIKNLALFVTTLLGCSQA',
 'MILSRILSATLVALALCLFNQATA',
 'MKTFIPFVALLSTISSLCAA',
 'MVHIKPLLATALAALSPLATA',
 'MLVKSIVSTLLALSLSSGLANA',
 'MVRLSLLASALLVASSTLA',
 'MRSLLLSVLFTVLFAILATA',
 'MLIRSIATLAVLGLSQTALS',
 'MVSQKLLSLATILALASLGQA',
 'MVALKHILTALLALSPLATA',
 'MIVTRFLSTLLLAASLSAANA',
 'MVLGITSKALAISLLACLSTPSTA',
 'MLLPTVTLLSVGLAALQPALA',
 'MVHIKPFATVALLASLLTPSLA',
 'MILRWTLVLLTALLALAYQ',
 'MVRIGISTLALALAHLVTS',
 'MRIIPSIGTLLTTVSLFTAHGTAA',
 'MVQLKSFLAVTATASLLTLSNA',
 'MILSKLLTTVAALSLLTPSVA',
 'MVHIKSFVTGLLATASTVTA',
 'MVQLTHLVALAASLFTLSVA',
 'MLFSSLIVTLAASTALSSA',
 'MILPHITTLLAIALSATSSALP',
 'MVSFKQIALLVTTLANIGLSTA',
 'MILSRISALLVLGLALFTQSLA',
 'MVQLKSFALLLGTSLFSSALA',
 'MVLPKIALLVTGLSATLANA',
 'MLPKIIHLLVALLSVLLVQLSVA',
 'MLSILKAALCALLLTPSLA',
 'MVSTKFLLTLLGAAPLALA',
 'MVAIKSLLVSLLAASLAPLATA',
 'MRFLAVAALLATTASA',
 'MVRLSHILTTALAILSPAVA',
 'MVHIKSLAVALGALLPTALA',
 'MLLPRLFYLGAIVPTVLS',
 'MVQIKSLALVLSTALFSSTLA',
 'MRVSTIPTALLGLSLSAVNA',
 'MVRLNSITALASLLAVSLTAA',
 'MILSYRSLVVTTVALLGLSTPATA',
 'MVLLKPLLATALLASLTPAVA',
 'MVHLKTLALAVSALLTPSIVSA']

In [131]:

# Step 1: Filter out sequences that are already in the exclusion list
filtered_df = filtered_df[~filtered_df['Sequence'].isin(list_already_made_sequences)]

# Step 2: Sort the filtered DataFrame by 'Perplexity' in ascending order
sorted_df = filtered_df.sort_values(by='Perplexity', ascending=False)

# Step 3: Select the top `n` rows
selected_rows = sorted_df.tail(23).reset_index(drop=True)

selected_rows

   SecretoGen_ID                  Sequence  Perplexity  Length
0         SP_462       MVAIKSLLLTALLATQAWA    2.045515      19
1         SP_201   MVQIKSFAVLATAISLLSTPAAA    2.045189      23
2          SP_58     MVHIKSLATALLASLAPFATA    2.038901      21
3         SP_182    MVHIKSLATAVLATSFLSPALA    2.015560      22
4         SP_269     MVQITQFLSVALAALSPLATA    2.012376      21
5          SP_45       MVAIKSLLVSGLLTTASLA    1.935643      19
6         SP_108       MVAIKSLLLSGLLATQAWA    1.925576      19
7         SP_105       MVLGLITIAIPTITGLAQA    1.912110      19
8         SP_978     MVLIKPLLTTALAVSAPLAQA    1.898729      21
9         SP_423  MVLIKPLLTTALLASASLLSPATA    1.860671      24
10        SP_521   MVQIKSFAVLATAISLLSPLATA    1.860139      23
11        SP_429    MVLIKPLLATALASLFSSQGLA    1.856135      22
12        SP_765  MVLIKPLVTAALAGLSLLTSHATA    1.841506      24
13        SP_925  MVLIKPFVTAALAGLSLLSSHVAA    1.834244      24
14        SP_231      MVLGLLTIAIIPTITGLAQA    1.732299      20
15        SP_438      MVLGILTIAIAPTITGLAQA    1.705283      20
16        SP_727      MVLGILTIAITPTVIGTAEA    1.666517      20
17        SP_701      MVLGILTIAITPTVIGTAEA    1.666517      20
18        SP_656      MVLGILTITAIPTVTGLANA    1.597785      20
19        SP_696      MVLGLLTIAAIPTVTGVAQA    1.563614      20
20        SP_757   MVLGLLTIAAIPTVTGVGNAVSA    1.554127      23
21        SP_253      MVLGILTITAIPTVTGVAQA    1.535361      20
22         SP_13      MVLGILTITAIPTVTGVANA    1.530345      20

In [132]:

seq_records1 = []
for index, row in selected_rows.iterrows():
    dna_sequence = back_translate(row['Sequence'])
    dseq_obj = Dseq(dna_sequence)
    dseqrecord = Dseqrecord(dseq_obj, name=row['SecretoGen_ID'], description=f"Perplexity: {row['Perplexity']}, Length: {row['Length']}")
    seq_records1.append(dseqrecord)

seq_records1

[Dseqrecord(-57),
 Dseqrecord(-69),
 Dseqrecord(-63),
 Dseqrecord(-66),
 Dseqrecord(-63),
 Dseqrecord(-57),
 Dseqrecord(-57),
 Dseqrecord(-57),
 Dseqrecord(-63),
 Dseqrecord(-72),
 Dseqrecord(-69),
 Dseqrecord(-66),
 Dseqrecord(-72),
 Dseqrecord(-72),
 Dseqrecord(-60),
 Dseqrecord(-60),
 Dseqrecord(-60),
 Dseqrecord(-60),
 Dseqrecord(-60),
 Dseqrecord(-60),
 Dseqrecord(-69),
 Dseqrecord(-60),
 Dseqrecord(-60)]

In [133]:

# Codon optimization for Aspergillus oryzae
codon_optimized_records1 = []
codon_optimized_records_str1 = []
taxonomy_id = 5062 # a oryzae

print()
for seq in seq_records1:
    problem = DnaOptimizationProblem(
        sequence=str(seq.seq),
        constraints=[
            EnforceGCContent(mini=0.3, maxi=0.7, window=len(seq)),
            EnforceTranslation(location=(0, len(seq)))
        ],
        #objectives=[CodonOptimize(codon_usage_table=a_oryzae, method='match_codon_usage')], 
        objectives=[CodonOptimize(species=taxonomy_id, method='match_codon_usage')], 
    )
    problem.resolve_constraints()
    
    problem.optimize()
    # PRINT SUMMARIES TO CHECK THAT CONSTRAINTS PASS
    print(problem.constraints_text_summary())
    print(problem.objectives_text_summary())

    # Save the sequences
    optimized_dna_sequence = str(problem.sequence)
    
    dseq_obj = Dseq(optimized_dna_sequence)
    dseqrecord = Dseqrecord(dseq_obj, name=seq.name, description=seq.description)
    codon_optimized_records1.append(dseqrecord)
    codon_optimized_records_str1.append(str(dseqrecord.seq))
    
selected_rows['codon_optimized_sequences']= codon_optimized_records_str1

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.45
     -9.45 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -9.45E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-69](mini:0.30, maxi:0.70, window:69)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-69(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.63
    -13.63 ┍ MatchTargetCodonUsage[0-69](5062)
           │ Codon opt. on window 0-69 scored -1.36E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.02
    -13.02 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.30E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.27
    -13.27 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.33E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.74
    -11.74 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.17E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.45
    -11.45 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.14E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.87
    -10.87 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.09E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-57](mini:0.30, maxi:0.70, window:57)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-57(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.77
    -10.77 ┍ MatchTargetCodonUsage[0-57](5062)
           │ Codon opt. on window 0-57 scored -1.08E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-63](mini:0.30, maxi:0.70, window:63)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-63(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.59
    -11.59 ┍ MatchTargetCodonUsage[0-63](5062)
           │ Codon opt. on window 0-63 scored -1.16E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-72](mini:0.30, maxi:0.70, window:72)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-72(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.94
    -11.94 ┍ MatchTargetCodonUsage[0-72](5062)
           │ Codon opt. on window 0-72 scored -1.19E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-69](mini:0.30, maxi:0.70, window:69)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-69(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.75
    -12.75 ┍ MatchTargetCodonUsage[0-69](5062)
           │ Codon opt. on window 0-69 scored -1.28E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.88
    -13.88 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -1.39E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-72](mini:0.30, maxi:0.70, window:72)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-72(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -13.63
    -13.63 ┍ MatchTargetCodonUsage[0-72](5062)
           │ Codon opt. on window 0-72 scored -1.36E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-72](mini:0.30, maxi:0.70, window:72)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-72(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -13.2
     -13.2 ┍ MatchTargetCodonUsage[0-72](5062)
           │ Codon opt. on window 0-72 scored -1.32E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.05
    -10.05 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.00E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.13
    -10.13 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.01E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.46
    -10.46 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.05E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.46
    -10.46 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.05E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.56
    -10.56 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -1.06E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.25
     -9.25 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -9.25E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-69](mini:0.30, maxi:0.70, window:69)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-69(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.44
    -10.44 ┍ MatchTargetCodonUsage[0-69](5062)
           │ Codon opt. on window 0-69 scored -1.04E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.74
     -9.74 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -9.74E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-60](mini:0.30, maxi:0.70, window:60)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-60(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.78
     -9.78 ┍ MatchTargetCodonUsage[0-60](5062)
           │ Codon opt. on window 0-60 scored -9.78E+00

In [134]:
selected_rows

,SecretoGen_ID,Sequence,Perplexity,Length,codon_optimized_sequences
0,SP_462,MVAIKSLLLTALLATQAWA,2.045515,19,ATGGTCGCGATCAAGTCCCTCCTACTGACTGCATTGCTTGCTACCC...
1,SP_201,MVQIKSFAVLATAISLLSTPAAA,2.045189,23,ATGGTCCAGATTAAGAGCTTCGCGGTGCTCGCCACTGCCATCTCTC...
2,SP_58,MVHIKSLATALLASLAPFATA,2.038901,21,ATGGTCCATATCAAGAGCTTGGCTACCGCACTCCTGGCGTCCCTTG...
3,SP_182,MVHIKSLATAVLATSFLSPALA,2.015560,22,ATGGTCCATATCAAGTCCCTGGCAACTGCGGTGTTGGCCACCTCTT...
4,SP_269,MVQITQFLSVALAALSPLATA,2.012376,21,ATGGTGCAAATCACCCAGTTCCTGAGCGTCGCACTCGCGGCCCTTT...
5,SP_45,MVAIKSLLVSGLLTTASLA,1.935643,19,ATGGTGGCTATCAAGTCCCTCCTGGTCAGCGGCTTGCTAACCACTG...
6,SP_108,MVAIKSLLLSGLLATQAWA,1.925576,19,ATGGTCGCCATCAAGTCCCTACTGCTTAGCGGCCTCTTGGCTACCC...
7,SP_105,MVLGLITIAIPTITGLAQA,1.912110,19,ATGGTCCTTGGTCTGATCACCATAGCTATCCCTACAATTACTGGCC...
8,SP_978,MVLIKPLLTTALAVSAPLAQA,1.898729,21,ATGGTGCTTATCAAGCCCCTCCTGACCACTGCCCTAGCAGTCTCCG...
9,SP_423,MVLIKPLLTTALLASASLLSPATA,1.860671,24,ATGGTCTTGATCAAGCCTCTTCTGACTACAGCGCTGCTCGCATCCG...
10,SP_521,MVQIKSFAVLATAISLLSPLATA,1.860139,23,ATGGTCCAGATCAAGTCTTTCGCGGTGCTTGCTACTGCAATTTCCC...
11,SP_429,MVLIKPLLATALASLFSSQGLA,1.856135,22,ATGGTCCTTATCAAGCCTCTGCTAGCGACCGCCTTAGCTTCCCTCT...
12,SP_765,MVLIKPLVTAALAGLSLLTSHATA,1.841506,24,ATGGTGCTGATCAAGCCTCTAGTCACTGCCGCACTCGCTGGCCTTT...
13,SP_925,MVLIKPFVTAALAGLSLLSSHVAA,1.834244,24,ATGGTGCTTATCAAGCCTTTCGTCACCGCCGCTCTGGCCGGCTTGT...
14,SP_231,MVLGLLTIAIIPTITGLAQA,1.732299,20,ATGGTCCTCGGCTTGCTTACTATCGCTATAATTCCTACCATCACAG...
15,SP_438,MVLGILTIAIAPTITGLAQA,1.705283,20,ATGGTCCTCGGCATACTGACAATCGCAATCGCTCCTACTATTACCG...
16,SP_727,MVLGILTIAITPTVIGTAEA,1.666517,20,ATGGTGCTGGGCATCCTCACTATTGCAATCACGCCTACCGTCATAG...
17,SP_701,MVLGILTIAITPTVIGTAEA,1.666517,20,ATGGTGCTGGGTATCCTCACTATAGCCATTACACCTACGGTCATCG...
18,SP_656,MVLGILTITAIPTVTGLANA,1.597785,20,ATGGTGCTCGGTATCCTTACTATCACGGCAATTCCTACAGTCACCG...
19,SP_696,MVLGLLTIAAIPTVTGVAQA,1.563614,20,ATGGTTCTTGGTCTCCTGACAATCGCCGCGATTCCTACCGTCACTG...
20,SP_757,MVLGLLTIAAIPTVTGVGNAVSA,1.554127,23,ATGGTCCTTGGACTGCTCACTATTGCTGCCATCCCTACAGTTACCG...
21,SP_253,MVLGILTITAIPTVTGVAQA,1.535361,20,ATGGTGCTGGGTATCCTCACCATCACTGCTATTCCTACAGTCACGG...
22,SP_13,MVLGILTITAIPTVTGVANA,1.530345,20,ATGGTTCTCGGCATCCTGACAATTACTGCCATCCCTACGGTCACCG...

In [135]:
# giving them new numbers
selected_rows['sp_name'] = [f'SP_{i+85}' for i in range(len(selected_rows['SecretoGen_ID'].to_list())) ]
selected_rows

,SecretoGen_ID,Sequence,Perplexity,Length,codon_optimized_sequences,sp_name
0,SP_462,MVAIKSLLLTALLATQAWA,2.045515,19,ATGGTCGCGATCAAGTCCCTCCTACTGACTGCATTGCTTGCTACCC...,SP_85
1,SP_201,MVQIKSFAVLATAISLLSTPAAA,2.045189,23,ATGGTCCAGATTAAGAGCTTCGCGGTGCTCGCCACTGCCATCTCTC...,SP_86
2,SP_58,MVHIKSLATALLASLAPFATA,2.038901,21,ATGGTCCATATCAAGAGCTTGGCTACCGCACTCCTGGCGTCCCTTG...,SP_87
3,SP_182,MVHIKSLATAVLATSFLSPALA,2.015560,22,ATGGTCCATATCAAGTCCCTGGCAACTGCGGTGTTGGCCACCTCTT...,SP_88
4,SP_269,MVQITQFLSVALAALSPLATA,2.012376,21,ATGGTGCAAATCACCCAGTTCCTGAGCGTCGCACTCGCGGCCCTTT...,SP_89
5,SP_45,MVAIKSLLVSGLLTTASLA,1.935643,19,ATGGTGGCTATCAAGTCCCTCCTGGTCAGCGGCTTGCTAACCACTG...,SP_90
6,SP_108,MVAIKSLLLSGLLATQAWA,1.925576,19,ATGGTCGCCATCAAGTCCCTACTGCTTAGCGGCCTCTTGGCTACCC...,SP_91
7,SP_105,MVLGLITIAIPTITGLAQA,1.912110,19,ATGGTCCTTGGTCTGATCACCATAGCTATCCCTACAATTACTGGCC...,SP_92
8,SP_978,MVLIKPLLTTALAVSAPLAQA,1.898729,21,ATGGTGCTTATCAAGCCCCTCCTGACCACTGCCCTAGCAGTCTCCG...,SP_93
9,SP_423,MVLIKPLLTTALLASASLLSPATA,1.860671,24,ATGGTCTTGATCAAGCCTCTTCTGACTACAGCGCTGCTCGCATCCG...,SP_94
10,SP_521,MVQIKSFAVLATAISLLSPLATA,1.860139,23,ATGGTCCAGATCAAGTCTTTCGCGGTGCTTGCTACTGCAATTTCCC...,SP_95
11,SP_429,MVLIKPLLATALASLFSSQGLA,1.856135,22,ATGGTCCTTATCAAGCCTCTGCTAGCGACCGCCTTAGCTTCCCTCT...,SP_96
12,SP_765,MVLIKPLVTAALAGLSLLTSHATA,1.841506,24,ATGGTGCTGATCAAGCCTCTAGTCACTGCCGCACTCGCTGGCCTTT...,SP_97
13,SP_925,MVLIKPFVTAALAGLSLLSSHVAA,1.834244,24,ATGGTGCTTATCAAGCCTTTCGTCACCGCCGCTCTGGCCGGCTTGT...,SP_98
14,SP_231,MVLGLLTIAIIPTITGLAQA,1.732299,20,ATGGTCCTCGGCTTGCTTACTATCGCTATAATTCCTACCATCACAG...,SP_99
15,SP_438,MVLGILTIAIAPTITGLAQA,1.705283,20,ATGGTCCTCGGCATACTGACAATCGCAATCGCTCCTACTATTACCG...,SP_100
16,SP_727,MVLGILTIAITPTVIGTAEA,1.666517,20,ATGGTGCTGGGCATCCTCACTATTGCAATCACGCCTACCGTCATAG...,SP_101
17,SP_701,MVLGILTIAITPTVIGTAEA,1.666517,20,ATGGTGCTGGGTATCCTCACTATAGCCATTACACCTACGGTCATCG...,SP_102
18,SP_656,MVLGILTITAIPTVTGLANA,1.597785,20,ATGGTGCTCGGTATCCTTACTATCACGGCAATTCCTACAGTCACCG...,SP_103
19,SP_696,MVLGLLTIAAIPTVTGVAQA,1.563614,20,ATGGTTCTTGGTCTCCTGACAATCGCCGCGATTCCTACCGTCACTG...,SP_104
20,SP_757,MVLGLLTIAAIPTVTGVGNAVSA,1.554127,23,ATGGTCCTTGGACTGCTCACTATTGCTGCCATCCCTACAGTTACCG...,SP_105
21,SP_253,MVLGILTITAIPTVTGVAQA,1.535361,20,ATGGTGCTGGGTATCCTCACCATCACTGCTATTCCTACAGTCACGG...,SP_106
22,SP_13,MVLGILTITAIPTVTGVANA,1.530345,20,ATGGTTCTCGGCATCCTGACAATTACTGCCATCCCTACGGTCACCG...,SP_107

In [136]:
### generate promers
RFP = Dseqrecord(SeqIO.read("../data/10_genetic_parts/parts/RFP_w_B_homolgy.fasta", "fasta"))
pTef = Dseqrecord(SeqIO.read("../data/10_genetic_parts/parts/pTEF_w_A_homology.fasta", "fasta"))
print(f'The lenght of RFP is {len(RFP)}')
print(f'The lenght of pTef is {len(pTef)}')

# generic overhangs
generic_pTef_fwd = Primer('CGAGACAGCAGAATCACCG') # generic 
generic_pTef_rev = Primer('GGTGAAGGTTGTGTTATGTTTTGTGG') # martis

generic_rfp_fwd = Primer('GCCTCCTCCGAGGACG') # martis
generic_rfp_rev = Primer('GAGGAGAGTGGATGGATAGTCTGG') # generic

The lenght of RFP is 1977
The lenght of pTef is 1384

In [137]:
reverse_ovh_list1 = []
forward_ovh_list1 = []

for index, row in selected_rows.iterrows():
    # get the sequence
    seq = str(row['codon_optimized_sequences'])

    # make the overhangs like marti propose: 
    # Forward
    fwd_ovh = seq[-44:] + generic_rfp_fwd
    fwd_ovh.name= f"{str(row['sp_name'])}_fwd"
    fwd_ovh.id = f"{str(row['sp_name'])}_fwd"

    # reverse
    rev_ovh = Seq(seq[:-14]).reverse_complement()+ generic_pTef_rev 
    rev_ovh.name = f"{str(row['sp_name'])}_rev"
    rev_ovh.id = f"{str(row['sp_name'])}_rev"


    forward_ovh_list1.append(fwd_ovh)
    reverse_ovh_list1.append(rev_ovh)

In [138]:
#Amplicons
pTef_amplicons = []
for i in range(len(reverse_ovh_list1)): 
    amplicon = pcr(generic_pTef_fwd, reverse_ovh_list1[i], pTef)
    pTef_amplicons.append(amplicon)

RFP_amplicons = []
for i in range(len(forward_ovh_list1)): 
    amplicon = pcr(forward_ovh_list1[i], generic_rfp_rev, RFP)
    RFP_amplicons.append(amplicon)

print(f'lenght of amplicons {len(pTef_amplicons), len(RFP_amplicons)}')

lenght of amplicons (23, 23)

In [139]:
id_names= selected_rows['sp_name'].to_list()
# changing the names of the amplicons
for i in range(len(pTef_amplicons)):
    pTef_amplicons[i].name =  f'pTef_{pTef_amplicons[i].name }_{id_names[i]}'
    
for i in range(len(RFP_amplicons)):
    RFP_amplicons[i].name =  f'RFP_{RFP_amplicons[i].name }_{id_names[i]}'

In [140]:
for i in range(len(RFP_amplicons)): 
    assemblyobj = Assembly([pTef_amplicons[i],RFP_amplicons[i]], limit = 18)
    contig = assemblyobj.assemble_linear()[0]

    print(contig.figure(), '\n')

pTef_929bp_PCR_prod_SP_85|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_85

pTef_941bp_PCR_prod_SP_86|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_86

pTef_935bp_PCR_prod_SP_87|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_87

pTef_938bp_PCR_prod_SP_88|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_88

pTef_935bp_PCR_prod_SP_89|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_89

pTef_929bp_PCR_prod_SP_90|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_90

pTef_929bp_PCR_prod_SP_91|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_91

pTef_929bp_PCR_prod_SP_92|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_92

pTef_935bp_PCR_prod_SP_93|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_93

pTef_944bp_PCR_prod_SP_94|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_94

pTef_941bp_PCR_prod_SP_95|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_95

pTef_938bp_PCR_prod_SP_96|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_96

pTef_944bp_PCR_prod_SP_97|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_97

pTef_944bp_PCR_prod_SP_98|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_98

pTef_932bp_PCR_prod_SP_99|30
                          \/
                          /\
                          30|RFP_2021bp_PCR_prod_SP_99

pTef_932bp_PCR_prod_SP_100|30
                           \/
                           /\
                           30|RFP_2021bp_PCR_prod_SP_100

pTef_932bp_PCR_prod_SP_101|30
                           \/
                           /\
                           30|RFP_2021bp_PCR_prod_SP_101

pTef_932bp_PCR_prod_SP_102|30
                           \/
                           /\
                           30|RFP_2021bp_PCR_prod_SP_102

pTef_932bp_PCR_prod_SP_103|30
                           \/
                           /\
                           30|RFP_2021bp_PCR_prod_SP_103

pTef_932bp_PCR_prod_SP_104|30
                           \/
                           /\
                           30|RFP_2021bp_PCR_prod_SP_104

pTef_941bp_PCR_prod_SP_105|30
                           \/
                           /\
                           30|RFP_2021bp_PCR_prod_SP_105

pTef_932bp_PCR_prod_SP_106|30
                           \/
                           /\
                           30|RFP_2021bp_PCR_prod_SP_106

pTef_932bp_PCR_prod_SP_107|30
                           \/
                           /\
                           30|RFP_2021bp_PCR_prod_SP_107

In [141]:
# changing the names of the amplicons
forward_primers = []
reverse_primers = []

for i in range(len(RFP_amplicons)):
    forward_primers.append(str(RFP_amplicons[i].forward_primer.seq))

for i in range(len(pTef_amplicons)):
    
    reverse_primers.append(str(pTef_amplicons[i].reverse_primer.seq))

In [142]:
selected_rows['fwd_primers(5-3)']= forward_primers
selected_rows['rev_primers(5-3)']= reverse_primers
selected_rows

,SecretoGen_ID,Sequence,Perplexity,Length,codon_optimized_sequences,sp_name,fwd_primers(5-3),rev_primers(5-3)
0,SP_462,MVAIKSLLLTALLATQAWA,2.045515,19,ATGGTCGCGATCAAGTCCCTCCTACTGACTGCATTGCTTGCTACCC...,SP_85,AGTCCCTCCTACTGACTGCATTGCTTGCTACCCAGGCCTGGGCCGC...,TAGCAAGCAATGCAGTCAGTAGGAGGGACTTGATCGCGACCATGGT...
1,SP_201,MVQIKSFAVLATAISLLSTPAAA,2.045189,23,ATGGTCCAGATTAAGAGCTTCGCGGTGCTCGCCACTGCCATCTCTC...,SP_86,TGCTCGCCACTGCCATCTCTCTTCTGTCCACCCCTGCAGCTGCTGC...,TGGACAGAAGAGAGATGGCAGTGGCGAGCACCGCGAAGCTCTTAAT...
2,SP_58,MVHIKSLATALLASLAPFATA,2.038901,21,ATGGTCCATATCAAGAGCTTGGCTACCGCACTCCTGGCGTCCCTTG...,SP_87,TGGCTACCGCACTCCTGGCGTCCCTTGCTCCTTTCGCCACTGCCGC...,GAGCAAGGGACGCCAGGAGTGCGGTAGCCAAGCTCTTGATATGGAC...
3,SP_182,MVHIKSLATAVLATSFLSPALA,2.015560,22,ATGGTCCATATCAAGTCCCTGGCAACTGCGGTGTTGGCCACCTCTT...,SP_88,CAACTGCGGTGTTGGCCACCTCTTTCCTCAGCCCTGCCCTTGCTGC...,TGAGGAAAGAGGTGGCCAACACCGCAGTTGCCAGGGACTTGATATG...
4,SP_269,MVQITQFLSVALAALSPLATA,2.012376,21,ATGGTGCAAATCACCCAGTTCCTGAGCGTCGCACTCGCGGCCCTTT...,SP_89,TCCTGAGCGTCGCACTCGCGGCCCTTTCCCCTTTGGCTACTGCCGC...,GGGAAAGGGCCGCGAGTGCGACGCTCAGGAACTGGGTGATTTGCAC...
5,SP_45,MVAIKSLLVSGLLTTASLA,1.935643,19,ATGGTGGCTATCAAGTCCCTCCTGGTCAGCGGCTTGCTAACCACTG...,SP_90,AGTCCCTCCTGGTCAGCGGCTTGCTAACCACTGCATCTCTTGCCGC...,TGGTTAGCAAGCCGCTGACCAGGAGGGACTTGATAGCCACCATGGT...
6,SP_108,MVAIKSLLLSGLLATQAWA,1.925576,19,ATGGTCGCCATCAAGTCCCTACTGCTTAGCGGCCTCTTGGCTACCC...,SP_91,AGTCCCTACTGCTTAGCGGCCTCTTGGCTACCCAGGCGTGGGCAGC...,TAGCCAAGAGGCCGCTAAGCAGTAGGGACTTGATGGCGACCATGGT...
7,SP_105,MVLGLITIAIPTITGLAQA,1.912110,19,ATGGTCCTTGGTCTGATCACCATAGCTATCCCTACAATTACTGGCC...,SP_92,TGATCACCATAGCTATCCCTACAATTACTGGCCTCGCCCAGGCAGC...,CAGTAATTGTAGGGATAGCTATGGTGATCAGACCAAGGACCATGGT...
8,SP_978,MVLIKPLLTTALAVSAPLAQA,1.898729,21,ATGGTGCTTATCAAGCCCCTCCTGACCACTGCCCTAGCAGTCTCCG...,SP_93,TCCTGACCACTGCCCTAGCAGTCTCCGCTCCTTTGGCCCAGGCGGC...,GAGCGGAGACTGCTAGGGCAGTGGTCAGGAGGGGCTTGATAAGCAC...
9,SP_423,MVLIKPLLTTALLASASLLSPATA,1.860671,24,ATGGTCTTGATCAAGCCTCTTCTGACTACAGCGCTGCTCGCATCCG...,SP_94,CAGCGCTGCTCGCATCCGCTTCTCTACTCAGCCCCGCCACCGCCGC...,TGAGTAGAGAAGCGGATGCGAGCAGCGCTGTAGTCAGAAGAGGCTT...
10,SP_521,MVQIKSFAVLATAISLLSPLATA,1.860139,23,ATGGTCCAGATCAAGTCTTTCGCGGTGCTTGCTACTGCAATTTCCC...,SP_95,TGCTTGCTACTGCAATTTCCCTCTTGAGCCCTCTGGCCACCGCCGC...,GGCTCAAGAGGGAAATTGCAGTAGCAAGCACCGCGAAAGACTTGAT...
11,SP_429,MVLIKPLLATALASLFSSQGLA,1.856135,22,ATGGTCCTTATCAAGCCTCTGCTAGCGACCGCCTTAGCTTCCCTCT...,SP_96,TAGCGACCGCCTTAGCTTCCCTCTTCAGCTCTCAGGGCTTGGCAGC...,AGCTGAAGAGGGAAGCTAAGGCGGTCGCTAGCAGAGGCTTGATAAG...
12,SP_765,MVLIKPLVTAALAGLSLLTSHATA,1.841506,24,ATGGTGCTGATCAAGCCTCTAGTCACTGCCGCACTCGCTGGCCTTT...,SP_97,CCGCACTCGCTGGCCTTTCCTTATTGACCAGCCATGCGACAGCCGC...,TGGTCAATAAGGAAAGGCCAGCGAGTGCGGCAGTGACTAGAGGCTT...
13,SP_925,MVLIKPFVTAALAGLSLLSSHVAA,1.834244,24,ATGGTGCTTATCAAGCCTTTCGTCACCGCCGCTCTGGCCGGCTTGT...,SP_98,CCGCTCTGGCCGGCTTGTCCCTCCTAAGCTCTCATGTTGCGGCAGC...,AGCTTAGGAGGGACAAGCCGGCCAGAGCGGCGGTGACGAAAGGCTT...
14,SP_231,MVLGLLTIAIIPTITGLAQA,1.732299,20,ATGGTCCTCGGCTTGCTTACTATCGCTATAATTCCTACCATCACAG...,SP_99,TTACTATCGCTATAATTCCTACCATCACAGGTCTGGCCCAGGCAGC...,CTGTGATGGTAGGAATTATAGCGATAGTAAGCAAGCCGAGGACCAT...
15,SP_438,MVLGILTIAIAPTITGLAQA,1.705283,20,ATGGTCCTCGGCATACTGACAATCGCAATCGCTCCTACTATTACCG...,SP_100,TGACAATCGCAATCGCTCCTACTATTACCGGTCTTGCGCAGGCCGC...,CGGTAATAGTAGGAGCGATTGCGATTGTCAGTATGCCGAGGACCAT...
16,SP_727,MVLGILTIAITPTVIGTAEA,1.666517,20,ATGGTGCTGGGCATCCTCACTATTGCAATCACGCCTACCGTCATAG...,SP_101,TCACTATTGCAATCACGCCTACCGTCATAGGTACAGCTGAGGCCGC...,CTATGACGGTAGGCGTGATTGCAATAGTGAGGATGCCCAGCACCAT...
17,SP_701,MVLGILTIAITPTVIGTAEA,1.666517,20,ATGGTGCTGGGTATCCTCACTATAGCCATTACACCTACGGTCATCG...,SP_102,TCACTATAGCCATTACACCTACGGTCATCGGCACCGCAGAGGCTGC...,CGATGACCGTAGGTGTAATGGCTATAGTGAGGATACCCAGCACCAT...
18,SP_656,MVLGILTITAIPTVTGLANA,1.597785,20,ATGGTGCTCGGTATCCTTACTATCACGGCAATTCCTACAGTCACCG...,SP_103,TTACTATCACGGCAATTCCTACAGTCACCGGCCTGGCTAACGCCGC...,CGGTGACTGTAGGAATTGCCGTGATAGTAAGGATACCGAGCACCAT...
19,SP_696,MVLGLLTIAAIPTVTGVAQA,1.563614,20,ATGGTTCTTGGTCTCCTGACAATCGCCGCGATTCCTACCGTCACTG...,SP_104,TGACAATCGCCGCGATTCCTACCGTCACTGGCGTGGCACAGGCTGC...,CAGTGACGGTAGGAATCGCGGCGATTGTCAGGAGACCAAGAACCAT...
20,SP_757,MVLGLLTIAAIPTVTGVGNAVSA,1.554127,23,ATGGTCCTTGGACTGCTCACTATTGCTGCCATCCCTACAGTTACCG...,SP_105,CTGCCATCCCTACAGTTACCGGCGTAGGTAACGCGGTGTCCGCAGC...,TACCTACGCCGGTAACTGTAGGGATGGCAGCAATAGTGAGCAGTCC...
21,SP_253,MVLGILTITAIPTVTGVAQA,1.535361,20,ATGGTGCTGGGTATCCTCACCATCACTGCTATTCCTACAGTCACGG...,SP_106,TCACCATCACTGCTATTCCTACAGTCACGGGCGTTGCACAGGCCGC...,CCGTGACTGTAGGAATAGCAGTGATGGTGAGGATACCCAGCACCAT...
22,SP_13,MVLGILTITAIPTVTGVANA,1.530345,20,ATGGTTCTCGGCATCCTGACAATTACTGCCATCCCTACGGTCACCG...,SP_107,TGACAATTACTGCCATCCCTACGGTCACCGGTGTGGCAAACGCTGC...,CGGTGACCGTAGGGATGGCAGTAATTGTCAGGATGCCGAGAACCAT...

In [143]:
forward_ovh_list1

[SP_85_fwd 60-mer:5'-AGTCCCTCCTACTGA..ACG-3',
 SP_86_fwd 60-mer:5'-TGCTCGCCACTGCCA..ACG-3',
 SP_87_fwd 60-mer:5'-TGGCTACCGCACTCC..ACG-3',
 SP_88_fwd 60-mer:5'-CAACTGCGGTGTTGG..ACG-3',
 SP_89_fwd 60-mer:5'-TCCTGAGCGTCGCAC..ACG-3',
 SP_90_fwd 60-mer:5'-AGTCCCTCCTGGTCA..ACG-3',
 SP_91_fwd 60-mer:5'-AGTCCCTACTGCTTA..ACG-3',
 SP_92_fwd 60-mer:5'-TGATCACCATAGCTA..ACG-3',
 SP_93_fwd 60-mer:5'-TCCTGACCACTGCCC..ACG-3',
 SP_94_fwd 60-mer:5'-CAGCGCTGCTCGCAT..ACG-3',
 SP_95_fwd 60-mer:5'-TGCTTGCTACTGCAA..ACG-3',
 SP_96_fwd 60-mer:5'-TAGCGACCGCCTTAG..ACG-3',
 SP_97_fwd 60-mer:5'-CCGCACTCGCTGGCC..ACG-3',
 SP_98_fwd 60-mer:5'-CCGCTCTGGCCGGCT..ACG-3',
 SP_99_fwd 60-mer:5'-TTACTATCGCTATAA..ACG-3',
 SP_100_fwd 60-mer:5'-TGACAATCGCAATCG..ACG-3',
 SP_101_fwd 60-mer:5'-TCACTATTGCAATCA..ACG-3',
 SP_102_fwd 60-mer:5'-TCACTATAGCCATTA..ACG-3',
 SP_103_fwd 60-mer:5'-TTACTATCACGGCAA..ACG-3',
 SP_104_fwd 60-mer:5'-TGACAATCGCCGCGA..ACG-3',
 SP_105_fwd 60-mer:5'-CTGCCATCCCTACAG..ACG-3',
 SP_106_fwd 60-mer:5'-TCACCATCACTGCTA..ACG-3',
 SP_107_fwd 60-mer:5'-TGACAATTACTGCCA..ACG-3']

In [144]:
reverse_ovh_list1

[SP_85_rev 69-mer:5'-TAGCAAGCAATGCAG..TGG-3',
 SP_86_rev 81-mer:5'-TGGACAGAAGAGAGA..TGG-3',
 SP_87_rev 75-mer:5'-GAGCAAGGGACGCCA..TGG-3',
 SP_88_rev 78-mer:5'-TGAGGAAAGAGGTGG..TGG-3',
 SP_89_rev 75-mer:5'-GGGAAAGGGCCGCGA..TGG-3',
 SP_90_rev 69-mer:5'-TGGTTAGCAAGCCGC..TGG-3',
 SP_91_rev 69-mer:5'-TAGCCAAGAGGCCGC..TGG-3',
 SP_92_rev 69-mer:5'-CAGTAATTGTAGGGA..TGG-3',
 SP_93_rev 75-mer:5'-GAGCGGAGACTGCTA..TGG-3',
 SP_94_rev 84-mer:5'-TGAGTAGAGAAGCGG..TGG-3',
 SP_95_rev 81-mer:5'-GGCTCAAGAGGGAAA..TGG-3',
 SP_96_rev 78-mer:5'-AGCTGAAGAGGGAAG..TGG-3',
 SP_97_rev 84-mer:5'-TGGTCAATAAGGAAA..TGG-3',
 SP_98_rev 84-mer:5'-AGCTTAGGAGGGACA..TGG-3',
 SP_99_rev 72-mer:5'-CTGTGATGGTAGGAA..TGG-3',
 SP_100_rev 72-mer:5'-CGGTAATAGTAGGAG..TGG-3',
 SP_101_rev 72-mer:5'-CTATGACGGTAGGCG..TGG-3',
 SP_102_rev 72-mer:5'-CGATGACCGTAGGTG..TGG-3',
 SP_103_rev 72-mer:5'-CGGTGACTGTAGGAA..TGG-3',
 SP_104_rev 72-mer:5'-CAGTGACGGTAGGAA..TGG-3',
 SP_105_rev 81-mer:5'-TACCTACGCCGGTAA..TGG-3',
 SP_106_rev 72-mer:5'-CCGTGACTGTAGGAA..TGG-3',
 SP_107_rev 72-mer:5'-CGGTGACCGTAGGGA..TGG-3']

In [145]:
fwd_name = [seq.name for seq in forward_ovh_list1]
fwd_seq = [str(seq.seq) for seq in forward_ovh_list1]

rev_name = [seq.name for seq in reverse_ovh_list1]
rev_seq = [str(seq.seq) for seq in reverse_ovh_list1]

In [146]:
forward_primers_well_plate = pd.read_excel('../data/example_plate-file-upload (1).xls')[:23]
forward_primers_well_plate['Name'] = fwd_name
forward_primers_well_plate['Sequence'] = fwd_seq


reverse_primers_well_plate = pd.read_excel('../data/example_plate-file-upload (1).xls')[:23]
reverse_primers_well_plate['Name'] = rev_name
reverse_primers_well_plate['Sequence'] = rev_seq

reverse_primers_well_plate

,Well Position,Name,Sequence
0,A1,SP_85_rev,TAGCAAGCAATGCAGTCAGTAGGAGGGACTTGATCGCGACCATGGT...
1,A2,SP_86_rev,TGGACAGAAGAGAGATGGCAGTGGCGAGCACCGCGAAGCTCTTAAT...
2,A3,SP_87_rev,GAGCAAGGGACGCCAGGAGTGCGGTAGCCAAGCTCTTGATATGGAC...
3,A4,SP_88_rev,TGAGGAAAGAGGTGGCCAACACCGCAGTTGCCAGGGACTTGATATG...
4,A5,SP_89_rev,GGGAAAGGGCCGCGAGTGCGACGCTCAGGAACTGGGTGATTTGCAC...
5,A6,SP_90_rev,TGGTTAGCAAGCCGCTGACCAGGAGGGACTTGATAGCCACCATGGT...
6,A7,SP_91_rev,TAGCCAAGAGGCCGCTAAGCAGTAGGGACTTGATGGCGACCATGGT...
7,A8,SP_92_rev,CAGTAATTGTAGGGATAGCTATGGTGATCAGACCAAGGACCATGGT...
8,A9,SP_93_rev,GAGCGGAGACTGCTAGGGCAGTGGTCAGGAGGGGCTTGATAAGCAC...
9,A10,SP_94_rev,TGAGTAGAGAAGCGGATGCGAGCAGCGCTGTAGTCAGAAGAGGCTT...
10,A11,SP_95_rev,GGCTCAAGAGGGAAATTGCAGTAGCAAGCACCGCGAAAGACTTGAT...
11,A12,SP_96_rev,AGCTGAAGAGGGAAGCTAAGGCGGTCGCTAGCAGAGGCTTGATAAG...
12,B1,SP_97_rev,TGGTCAATAAGGAAAGGCCAGCGAGTGCGGCAGTGACTAGAGGCTT...
13,B2,SP_98_rev,AGCTTAGGAGGGACAAGCCGGCCAGAGCGGCGGTGACGAAAGGCTT...
14,B3,SP_99_rev,CTGTGATGGTAGGAATTATAGCGATAGTAAGCAAGCCGAGGACCAT...
15,B4,SP_100_rev,CGGTAATAGTAGGAGCGATTGCGATTGTCAGTATGCCGAGGACCAT...
16,B5,SP_101_rev,CTATGACGGTAGGCGTGATTGCAATAGTGAGGATGCCCAGCACCAT...
17,B6,SP_102_rev,CGATGACCGTAGGTGTAATGGCTATAGTGAGGATACCCAGCACCAT...
18,B7,SP_103_rev,CGGTGACTGTAGGAATTGCCGTGATAGTAAGGATACCGAGCACCAT...
19,B8,SP_104_rev,CAGTGACGGTAGGAATCGCGGCGATTGTCAGGAGACCAAGAACCAT...
20,B9,SP_105_rev,TACCTACGCCGGTAACTGTAGGGATGGCAGCAATAGTGAGCAGTCC...
21,B10,SP_106_rev,CCGTGACTGTAGGAATAGCAGTGATGGTGAGGATACCCAGCACCAT...
22,B11,SP_107_rev,CGGTGACCGTAGGGATGGCAGTAATTGTCAGGATGCCGAGAACCAT...

In [147]:
forward_primers_well_plate.to_excel('../data/09_primers/forward_primers_2024_14_11.xlsx')
reverse_primers_well_plate.to_excel('../data/09_primers/reverse_primers_2024_14_11.xlsx')
selected_rows.to_excel('../data/09_primers/full_dataframe_of_sampled_SPs_2024_14_11.xlsx')

In [152]:
selected_rows

,SecretoGen_ID,Sequence,Perplexity,Length,codon_optimized_sequences,sp_name,fwd_primers(5-3),rev_primers(5-3)
0,SP_462,MVAIKSLLLTALLATQAWA,2.045515,19,ATGGTCGCGATCAAGTCCCTCCTACTGACTGCATTGCTTGCTACCC...,SP_85,AGTCCCTCCTACTGACTGCATTGCTTGCTACCCAGGCCTGGGCCGC...,TAGCAAGCAATGCAGTCAGTAGGAGGGACTTGATCGCGACCATGGT...
1,SP_201,MVQIKSFAVLATAISLLSTPAAA,2.045189,23,ATGGTCCAGATTAAGAGCTTCGCGGTGCTCGCCACTGCCATCTCTC...,SP_86,TGCTCGCCACTGCCATCTCTCTTCTGTCCACCCCTGCAGCTGCTGC...,TGGACAGAAGAGAGATGGCAGTGGCGAGCACCGCGAAGCTCTTAAT...
2,SP_58,MVHIKSLATALLASLAPFATA,2.038901,21,ATGGTCCATATCAAGAGCTTGGCTACCGCACTCCTGGCGTCCCTTG...,SP_87,TGGCTACCGCACTCCTGGCGTCCCTTGCTCCTTTCGCCACTGCCGC...,GAGCAAGGGACGCCAGGAGTGCGGTAGCCAAGCTCTTGATATGGAC...
3,SP_182,MVHIKSLATAVLATSFLSPALA,2.015560,22,ATGGTCCATATCAAGTCCCTGGCAACTGCGGTGTTGGCCACCTCTT...,SP_88,CAACTGCGGTGTTGGCCACCTCTTTCCTCAGCCCTGCCCTTGCTGC...,TGAGGAAAGAGGTGGCCAACACCGCAGTTGCCAGGGACTTGATATG...
4,SP_269,MVQITQFLSVALAALSPLATA,2.012376,21,ATGGTGCAAATCACCCAGTTCCTGAGCGTCGCACTCGCGGCCCTTT...,SP_89,TCCTGAGCGTCGCACTCGCGGCCCTTTCCCCTTTGGCTACTGCCGC...,GGGAAAGGGCCGCGAGTGCGACGCTCAGGAACTGGGTGATTTGCAC...
5,SP_45,MVAIKSLLVSGLLTTASLA,1.935643,19,ATGGTGGCTATCAAGTCCCTCCTGGTCAGCGGCTTGCTAACCACTG...,SP_90,AGTCCCTCCTGGTCAGCGGCTTGCTAACCACTGCATCTCTTGCCGC...,TGGTTAGCAAGCCGCTGACCAGGAGGGACTTGATAGCCACCATGGT...
6,SP_108,MVAIKSLLLSGLLATQAWA,1.925576,19,ATGGTCGCCATCAAGTCCCTACTGCTTAGCGGCCTCTTGGCTACCC...,SP_91,AGTCCCTACTGCTTAGCGGCCTCTTGGCTACCCAGGCGTGGGCAGC...,TAGCCAAGAGGCCGCTAAGCAGTAGGGACTTGATGGCGACCATGGT...
7,SP_105,MVLGLITIAIPTITGLAQA,1.912110,19,ATGGTCCTTGGTCTGATCACCATAGCTATCCCTACAATTACTGGCC...,SP_92,TGATCACCATAGCTATCCCTACAATTACTGGCCTCGCCCAGGCAGC...,CAGTAATTGTAGGGATAGCTATGGTGATCAGACCAAGGACCATGGT...
8,SP_978,MVLIKPLLTTALAVSAPLAQA,1.898729,21,ATGGTGCTTATCAAGCCCCTCCTGACCACTGCCCTAGCAGTCTCCG...,SP_93,TCCTGACCACTGCCCTAGCAGTCTCCGCTCCTTTGGCCCAGGCGGC...,GAGCGGAGACTGCTAGGGCAGTGGTCAGGAGGGGCTTGATAAGCAC...
9,SP_423,MVLIKPLLTTALLASASLLSPATA,1.860671,24,ATGGTCTTGATCAAGCCTCTTCTGACTACAGCGCTGCTCGCATCCG...,SP_94,CAGCGCTGCTCGCATCCGCTTCTCTACTCAGCCCCGCCACCGCCGC...,TGAGTAGAGAAGCGGATGCGAGCAGCGCTGTAGTCAGAAGAGGCTT...
10,SP_521,MVQIKSFAVLATAISLLSPLATA,1.860139,23,ATGGTCCAGATCAAGTCTTTCGCGGTGCTTGCTACTGCAATTTCCC...,SP_95,TGCTTGCTACTGCAATTTCCCTCTTGAGCCCTCTGGCCACCGCCGC...,GGCTCAAGAGGGAAATTGCAGTAGCAAGCACCGCGAAAGACTTGAT...
11,SP_429,MVLIKPLLATALASLFSSQGLA,1.856135,22,ATGGTCCTTATCAAGCCTCTGCTAGCGACCGCCTTAGCTTCCCTCT...,SP_96,TAGCGACCGCCTTAGCTTCCCTCTTCAGCTCTCAGGGCTTGGCAGC...,AGCTGAAGAGGGAAGCTAAGGCGGTCGCTAGCAGAGGCTTGATAAG...
12,SP_765,MVLIKPLVTAALAGLSLLTSHATA,1.841506,24,ATGGTGCTGATCAAGCCTCTAGTCACTGCCGCACTCGCTGGCCTTT...,SP_97,CCGCACTCGCTGGCCTTTCCTTATTGACCAGCCATGCGACAGCCGC...,TGGTCAATAAGGAAAGGCCAGCGAGTGCGGCAGTGACTAGAGGCTT...
13,SP_925,MVLIKPFVTAALAGLSLLSSHVAA,1.834244,24,ATGGTGCTTATCAAGCCTTTCGTCACCGCCGCTCTGGCCGGCTTGT...,SP_98,CCGCTCTGGCCGGCTTGTCCCTCCTAAGCTCTCATGTTGCGGCAGC...,AGCTTAGGAGGGACAAGCCGGCCAGAGCGGCGGTGACGAAAGGCTT...
14,SP_231,MVLGLLTIAIIPTITGLAQA,1.732299,20,ATGGTCCTCGGCTTGCTTACTATCGCTATAATTCCTACCATCACAG...,SP_99,TTACTATCGCTATAATTCCTACCATCACAGGTCTGGCCCAGGCAGC...,CTGTGATGGTAGGAATTATAGCGATAGTAAGCAAGCCGAGGACCAT...
15,SP_438,MVLGILTIAIAPTITGLAQA,1.705283,20,ATGGTCCTCGGCATACTGACAATCGCAATCGCTCCTACTATTACCG...,SP_100,TGACAATCGCAATCGCTCCTACTATTACCGGTCTTGCGCAGGCCGC...,CGGTAATAGTAGGAGCGATTGCGATTGTCAGTATGCCGAGGACCAT...
16,SP_727,MVLGILTIAITPTVIGTAEA,1.666517,20,ATGGTGCTGGGCATCCTCACTATTGCAATCACGCCTACCGTCATAG...,SP_101,TCACTATTGCAATCACGCCTACCGTCATAGGTACAGCTGAGGCCGC...,CTATGACGGTAGGCGTGATTGCAATAGTGAGGATGCCCAGCACCAT...
17,SP_701,MVLGILTIAITPTVIGTAEA,1.666517,20,ATGGTGCTGGGTATCCTCACTATAGCCATTACACCTACGGTCATCG...,SP_102,TCACTATAGCCATTACACCTACGGTCATCGGCACCGCAGAGGCTGC...,CGATGACCGTAGGTGTAATGGCTATAGTGAGGATACCCAGCACCAT...
18,SP_656,MVLGILTITAIPTVTGLANA,1.597785,20,ATGGTGCTCGGTATCCTTACTATCACGGCAATTCCTACAGTCACCG...,SP_103,TTACTATCACGGCAATTCCTACAGTCACCGGCCTGGCTAACGCCGC...,CGGTGACTGTAGGAATTGCCGTGATAGTAAGGATACCGAGCACCAT...
19,SP_696,MVLGLLTIAAIPTVTGVAQA,1.563614,20,ATGGTTCTTGGTCTCCTGACAATCGCCGCGATTCCTACCGTCACTG...,SP_104,TGACAATCGCCGCGATTCCTACCGTCACTGGCGTGGCACAGGCTGC...,CAGTGACGGTAGGAATCGCGGCGATTGTCAGGAGACCAAGAACCAT...
20,SP_757,MVLGLLTIAAIPTVTGVGNAVSA,1.554127,23,ATGGTCCTTGGACTGCTCACTATTGCTGCCATCCCTACAGTTACCG...,SP_105,CTGCCATCCCTACAGTTACCGGCGTAGGTAACGCGGTGTCCGCAGC...,TACCTACGCCGGTAACTGTAGGGATGGCAGCAATAGTGAGCAGTCC...
21,SP_253,MVLGILTITAIPTVTGVAQA,1.535361,20,ATGGTGCTGGGTATCCTCACCATCACTGCTATTCCTACAGTCACGG...,SP_106,TCACCATCACTGCTATTCCTACAGTCACGGGCGTTGCACAGGCCGC...,CCGTGACTGTAGGAATAGCAGTGATGGTGAGGATACCCAGCACCAT...
22,SP_13,MVLGILTITAIPTVTGVANA,1.530345,20,ATGGTTCTCGGCATCCTGACAATTACTGCCATCCCTACGGTCACCG...,SP_107,TGACAATTACTGCCATCCCTACGGTCACCGGTGTGGCAAACGCTGC...,CGGTGACCGTAGGGATGGCAGTAATTGTCAGGATGCCGAGAACCAT...

In [149]:

def find_duplicates_between_dfs(df1, df2, columns):
    """
    Find duplicate rows between two DataFrames based on specified columns.
    
    Parameters:
    - df1 (pd.DataFrame): The first DataFrame (e.g., final_sample).
    - df2 (pd.DataFrame): The second DataFrame (e.g., selected_rows).
    - columns (list): List of column names to consider for duplication.
    
    Returns:
    - duplicates_df (pd.DataFrame): Rows from df2 that are duplicates in df1.
    """
    # Ensure the specified columns exist in both DataFrames
    missing_cols_df1 = set(columns) - set(df1.columns)
    missing_cols_df2 = set(columns) - set(df2.columns)
    
    if missing_cols_df1:
        raise ValueError(f"The following columns are missing in df1: {missing_cols_df1}")
    if missing_cols_df2:
        raise ValueError(f"The following columns are missing in df2: {missing_cols_df2}")
    
    # Create a unique identifier by concatenating the specified columns
    df1_unique = df1[columns].drop_duplicates()
    df2_unique = df2[columns].drop_duplicates()
    
    # Merge df2 with df1 to find duplicates
    duplicates_df = pd.merge(df2_unique, df1_unique, on=columns, how='inner', indicator=False)
    
    # To get the full rows from df2 that are duplicates in df1
    # Merge with the original df2 to preserve all columns
    duplicates_full = pd.merge(df2, duplicates_df, on=columns, how='inner')
    
    return duplicates_full

duplicate_columns = ['Sequence', 'SecretoGen_ID']

duplicates = find_duplicates_between_dfs(final_sample, selected_rows, duplicate_columns)
duplicates

Empty DataFrame
Columns: [SecretoGen_ID, Sequence, Perplexity, Length, codon_optimized_sequences, sp_name, fwd_primers(5-3), rev_primers(5-3)]
Index: []

In [150]:

def report_duplicates(duplicates_df):
    """
    Print a summary and the duplicate rows.
    
    Parameters:
    - duplicates_df (pd.DataFrame): DataFrame containing duplicate rows.
    """
    if duplicates_df.empty:
        print("No duplicates found between the two DataFrames based on the specified columns.")
    else:
        print(f"Found {len(duplicates_df)} duplicate(s) between the DataFrames based on the specified columns.")
        print("Duplicate Rows:")
        print(duplicates_df)
    
report_duplicates(duplicates)

No duplicates found between the two DataFrames based on the specified columns.