In [2]:
import pandas as pd
from IPython.display import Image
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from pydna.dseqrecord import Dseqrecord

In [3]:
a_oryzae ={
    'F': {'TTT': 0.38, 'TTC': 0.62},
    'S': {'TCT': 0.18, 'TCC': 0.20, 'TCA': 0.14, 'TCG': 0.16, 'AGT': 0.13, 'AGC': 0.18},
    'Y': {'TAT': 0.47, 'TAC': 0.53},
    'C': {'TGT': 0.46, 'TGC': 0.54},
    '*': {'TAA': 0.33, 'TAG': 0.29, 'TGA': 0.38},
    'L': {'TTA': 0.07, 'TTG': 0.18, 'CTT': 0.19, 'CTC': 0.23, 'CTA': 0.11, 'CTG': 0.22},
    'W': {'TGG': 1.00},
    'P': {'CCT': 0.27, 'CCC': 0.26, 'CCA': 0.25, 'CCG': 0.22},
    'H': {'CAT': 0.53, 'CAC': 0.47},
    'Q': {'CAA': 0.43, 'CAG': 0.57},
    'R': {'CGT': 0.18, 'CGC': 0.23, 'CGA': 0.17, 'CGG': 0.18, 'AGA': 0.13, 'AGG': 0.12},
    'I': {'ATT': 0.36, 'ATC': 0.50, 'ATA': 0.14},
    'M': {'ATG': 1.00},
    'T': {'ACT': 0.24, 'ACC': 0.32, 'ACA': 0.23, 'ACG': 0.20},
    'N': {'AAT': 0.45, 'AAC': 0.55},
    'K': {'AAA': 0.36, 'AAG': 0.64},
    'V': {'GTT': 0.27, 'GTC': 0.33, 'GTA': 0.13, 'GTG': 0.27},
    'A': {'GCT': 0.27, 'GCC': 0.30, 'GCA': 0.23, 'GCG': 0.20},
    'D': {'GAT': 0.53, 'GAC': 0.47},
    'E': {'GAA': 0.44, 'GAG': 0.56},
    'G': {'GGT': 0.28, 'GGC': 0.31, 'GGA': 0.24, 'GGG': 0.17}
}

### SPs

In [4]:
sp_df = pd.read_csv('../data/15_SecretoGen/lyzozyme_sp_df_sorted.csv')
sp_df = sp_df.rename(columns={"Unnamed: 0": "SecretoGen_ID"})
sp_df['SecretoGen_ID'] = [f'SP_{i+1}' for i in range(len(sp_df))]
sp_df

     SecretoGen_ID                  Sequence  Perplexity
0             SP_1         MKFSIIALLPLVAAVSA    1.612892
1             SP_2    MKFSIIALLPLAALVAAAPAPE    1.630686
2             SP_3         MKFSIIALTLLPLAALA    1.642188
3             SP_4         MKFSIIALLPLALGVVA    1.657314
4             SP_5         MRFSIIALLPLAALVSA    1.692659
...            ...                       ...         ...
4995       SP_4996        MRFTIALLPLALAVAATA    4.293468
4996       SP_4997  MRFFALVALVAPLALAATPLTVEG    4.376352
4997       SP_4998     MRLTLISTILPLVLATPVPDA    4.585343
4998       SP_4999       MRLELSIITLLSLVSAVQA    4.591389
4999       SP_5000       MRLTLISSLMLAAASAVNA    4.837202

[5000 rows x 3 columns]

In [5]:
sp_df

     SecretoGen_ID                  Sequence  Perplexity
0             SP_1         MKFSIIALLPLVAAVSA    1.612892
1             SP_2    MKFSIIALLPLAALVAAAPAPE    1.630686
2             SP_3         MKFSIIALTLLPLAALA    1.642188
3             SP_4         MKFSIIALLPLALGVVA    1.657314
4             SP_5         MRFSIIALLPLAALVSA    1.692659
...            ...                       ...         ...
4995       SP_4996        MRFTIALLPLALAVAATA    4.293468
4996       SP_4997  MRFFALVALVAPLALAATPLTVEG    4.376352
4997       SP_4998     MRLTLISTILPLVLATPVPDA    4.585343
4998       SP_4999       MRLELSIITLLSLVSAVQA    4.591389
4999       SP_5000       MRLTLISSLMLAAASAVNA    4.837202

[5000 rows x 3 columns]

How many SPs are longer than 26?

In [6]:
# Adding the length of sequences to the dataframe
sp_df['Length'] = sp_df['Sequence'].apply(len)

# Removing sequences with length over 26
filtered_df = sp_df[sp_df['Length'] <= 23]
filtered_df

     SecretoGen_ID                Sequence  Perplexity  Length
0             SP_1       MKFSIIALLPLVAAVSA    1.612892      17
1             SP_2  MKFSIIALLPLAALVAAAPAPE    1.630686      22
2             SP_3       MKFSIIALTLLPLAALA    1.642188      17
3             SP_4       MKFSIIALLPLALGVVA    1.657314      17
4             SP_5       MRFSIIALLPLAALVSA    1.692659      17
...            ...                     ...         ...     ...
4994       SP_4995      MKLINLLILTTLATLGLA    4.261933      18
4995       SP_4996      MRFTIALLPLALAVAATA    4.293468      18
4997       SP_4998   MRLTLISTILPLVLATPVPDA    4.585343      21
4998       SP_4999     MRLELSIITLLSLVSAVQA    4.591389      19
4999       SP_5000     MRLTLISSLMLAAASAVNA    4.837202      19

[4722 rows x 4 columns]

In [7]:

# Getting the top 30
top_30 = sp_df.head(23)

# Sampling the remaining dataframe for a good mix
#remaining_sample_size = 84 - 30
#remaining_sample = sp_df.iloc[30:].sample(n=remaining_sample_size, random_state=1)

# Combining the top 30 with the remaining sample
final_sample = top_30 # pd.concat([top_30, remaining_sample]).reset_index(drop=True)
final_sample

   SecretoGen_ID                 Sequence  Perplexity  Length
0           SP_1        MKFSIIALLPLVAAVSA    1.612892      17
1           SP_2   MKFSIIALLPLAALVAAAPAPE    1.630686      22
2           SP_3        MKFSIIALTLLPLAALA    1.642188      17
3           SP_4        MKFSIIALLPLALGVVA    1.657314      17
4           SP_5        MRFSIIALLPLAALVSA    1.692659      17
5           SP_6        MKFTLINLLALTAAVSA    1.693007      17
6           SP_7        MKFSIIALLPLALGVSA    1.698680      17
7           SP_8        MKFSIIALLPLLAAVSA    1.699822      17
8           SP_9        MKFSIIALLPLVAAVSA    1.727175      17
9          SP_10        MKFSIIALLPLVAAVSA    1.732880      17
10         SP_11        MKFSIIALLPLALAVSA    1.737774      17
11         SP_12  MKFSIIALLPLAALVAASPTPDA    1.742775      23
12         SP_13        MRFSIIALTLLPLAALA    1.754269      17
13         SP_14        MKFSIIALLPLVAAVSA    1.761043      17
14         SP_15       MKFSIIALLPLLAAAVSA    1.767437      18
15         SP_16  MKFFTIIALMAPLAALAAPAPDA    1.769435      23
16         SP_17        MKFSIIALTLLPLAALA    1.777155      17
17         SP_18   MKFIALTLLPLAALVAAAPAPD    1.778253      22
18         SP_19        MKFSIIALLPLALAVSA    1.780316      17
19         SP_20       MRFINLALLLPLAALVSA    1.790374      18
20         SP_21        MKFSIIALLPLVALVSA    1.796229      17
21         SP_22        MRFSIIALLPLAALVSA    1.796728      17
22         SP_23        MKFSIVALALLPLAAMA    1.804731      17

# Back-translate

In [8]:
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio import SeqIO
from pydna.dseq import Dseq

# Simplified back-translation codon table
back_translation_code = {
        'A': ['GCA', 'GCC', 'GCG', 'GCT'],
        'C': ['TGT', 'TGC'],
        'D': ['GAC', 'GAT'],
        'E': ['GAG', 'GAA'],
        'F': ['TTT', 'TTC'],
        'G': ['GGT', 'GGG', 'GGA', 'GGC'],
        'H': ['CAT', 'CAC'],
        'I': ['ATC', 'ATA', 'ATT'],
        'K': ['AAG', 'AAA'],
        'L': ['CTT', 'CTG', 'CTA', 'CTC', 'TTA', 'TTG'],
        'M': ['ATG'],
        'N': ['AAC', 'AAT'],
        'P': ['CCT', 'CCG', 'CCA', 'CCC'],
        'Q': ['CAA', 'CAG'],
        'R': ['AGG', 'AGA', 'CGA', 'CGC', 'CGG', 'CGT'],
        'S': ['AGC', 'AGT', 'TCT', 'TCG', 'TCC', 'TCA'],
        'T': ['ACA', 'ACG', 'ACT', 'ACC'],
        'V': ['GTA', 'GTC', 'GTG', 'GTT'],
        'W': ['TGG'],
        'Y': ['TAT', 'TAC'],
        '*': ['TAA', 'TGA', 'TAG']
    }


def back_translate(protein_sequence):
    return ''.join([back_translation_code[aa][0] for aa in protein_sequence])

In [9]:

seq_records = []
for index, row in final_sample.iterrows():
    dna_sequence = back_translate(row['Sequence'])
    dseq_obj = Dseq(dna_sequence)
    dseqrecord = Dseqrecord(dseq_obj, name=row['SecretoGen_ID'], description=f"Perplexity: {row['Perplexity']}, Length: {row['Length']}")
    seq_records.append(dseqrecord)

seq_records

[Dseqrecord(-51),
 Dseqrecord(-66),
 Dseqrecord(-51),
 Dseqrecord(-51),
 Dseqrecord(-51),
 Dseqrecord(-51),
 Dseqrecord(-51),
 Dseqrecord(-51),
 Dseqrecord(-51),
 Dseqrecord(-51),
 Dseqrecord(-51),
 Dseqrecord(-69),
 Dseqrecord(-51),
 Dseqrecord(-51),
 Dseqrecord(-54),
 Dseqrecord(-69),
 Dseqrecord(-51),
 Dseqrecord(-66),
 Dseqrecord(-51),
 Dseqrecord(-54),
 Dseqrecord(-51),
 Dseqrecord(-51),
 Dseqrecord(-51)]

In [10]:
print(seq_records[0].seq)

ATGAAGTTTAGCATCATCGCACTTCTTCCTCTTGTAGCAGCAGTAAGCGCA

### Codon optimize the sequences:

A. oryzae tax id : 5062

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=5062&lvl=3&lin=f&keep=1&srchmode=1&unlock

In [11]:
# to make the codon optimization reproducible we can initialize a random seed
import numpy as np
np.random.seed(2)

In [12]:
from dnachisel import DnaOptimizationProblem, CodonOptimize, EnforceTranslation, EnforceGCContent

# Codon optimization for Aspergillus oryzae
codon_optimized_records = []
codon_optimized_records_str = []
taxonomy_id = 5062 # a oryzae

for seq in seq_records:
    problem = DnaOptimizationProblem(
        sequence=str(seq.seq),
        constraints=[
            EnforceGCContent(mini=0.3, maxi=0.7, window=len(seq)),
            EnforceTranslation(location=(0, len(seq)))
        ],
        #objectives=[CodonOptimize(codon_usage_table=a_oryzae, method='match_codon_usage')], 
        objectives=[CodonOptimize(species=taxonomy_id, method='match_codon_usage')], 
    )
    problem.resolve_constraints()
    
    problem.optimize()
    # PRINT SUMMARIES TO CHECK THAT CONSTRAINTS PASS
    print(problem.constraints_text_summary())
    print(problem.objectives_text_summary())

    # Save the sequences
    optimized_dna_sequence = str(problem.sequence)
    
    dseq_obj = Dseq(optimized_dna_sequence)
    dseqrecord = Dseqrecord(dseq_obj, name=row['SecretoGen_ID'], description=f"Perplexity: {row['Perplexity']}, Length: {row['Length']}")
    codon_optimized_records.append(dseqrecord)
    codon_optimized_records_str.append(str(dseqrecord.seq))
    
final_sample['codon_optimized_sequences']= codon_optimized_records_str

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.28
    -10.28 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.03E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.61
     -9.61 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -9.61E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:      -8.2
      -8.2 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -8.20E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.71
    -10.71 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.07E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.13
    -10.13 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.01E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.05
    -10.05 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.00E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -11.32
    -11.32 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.13E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.30
     -9.30 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -9.30E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.28
    -10.28 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.03E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.28
    -10.28 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.03E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.30
     -9.30 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -9.30E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-69](mini:0.30, maxi:0.70, window:69)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-69(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -12.05
    -12.05 ┍ MatchTargetCodonUsage[0-69](5062)
           │ Codon opt. on window 0-69 scored -1.20E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.03
     -9.03 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -9.03E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.28
    -10.28 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.03E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-54](mini:0.30, maxi:0.70, window:54)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-54(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.74
     -9.74 ┍ MatchTargetCodonUsage[0-54](5062)
           │ Codon opt. on window 0-54 scored -9.74E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-69](mini:0.30, maxi:0.70, window:69)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-69(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -8.65
     -8.65 ┍ MatchTargetCodonUsage[0-69](5062)
           │ Codon opt. on window 0-69 scored -8.65E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:      -8.2
      -8.2 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -8.20E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-66](mini:0.30, maxi:0.70, window:66)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-66(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.63
     -9.63 ┍ MatchTargetCodonUsage[0-66](5062)
           │ Codon opt. on window 0-66 scored -9.63E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.30
     -9.30 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -9.30E+00

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-54](mini:0.30, maxi:0.70, window:54)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-54(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:       -11
       -11 ┍ MatchTargetCodonUsage[0-54](5062)
           │ Codon opt. on window 0-54 scored -1.10E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -10.2
     -10.2 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.02E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:    -10.13
    -10.13 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -1.01E+01

===> SUCCESS - all constraints evaluations pass
✔PASS ┍ EnforceGCContent[0-51](mini:0.30, maxi:0.70, window:51)
      │ Passed !
✔PASS ┍ EnforceTranslation[0-51(+)]
      │ Enforced by nucleotides restrictions


===> TOTAL OBJECTIVES SCORE:     -9.31
     -9.31 ┍ MatchTargetCodonUsage[0-51](5062)
           │ Codon opt. on window 0-51 scored -9.31E+00

/var/folders/2f/lw3sfzbs7l7f_q1knzbtbwrr0000gp/T/ipykernel_49358/3536819536.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_sample['codon_optimized_sequences']= codon_optimized_records_str

## Final sample with sp_name

In [13]:
final_sample['sp_name'] = [f'SP_{i+1}' for i in range(len(final_sample['SecretoGen_ID'].to_list())) ]

/var/folders/2f/lw3sfzbs7l7f_q1knzbtbwrr0000gp/T/ipykernel_49358/3097797703.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_sample['sp_name'] = [f'SP_{i+1}' for i in range(len(final_sample['SecretoGen_ID'].to_list())) ]

In [14]:
with pd.option_context('display.max_rows', None,
                       'display.max_columns', None,
                       'display.precision', 3,
                       'display.width', None,
                       'display.max_colwidth', 1000
                       ):
    print(final_sample)

   SecretoGen_ID                 Sequence  Perplexity  Length  \
0           SP_1        MKFSIIALLPLVAAVSA       1.613      17
1           SP_2   MKFSIIALLPLAALVAAAPAPE       1.631      22
2           SP_3        MKFSIIALTLLPLAALA       1.642      17
3           SP_4        MKFSIIALLPLALGVVA       1.657      17
4           SP_5        MRFSIIALLPLAALVSA       1.693      17
5           SP_6        MKFTLINLLALTAAVSA       1.693      17
6           SP_7        MKFSIIALLPLALGVSA       1.699      17
7           SP_8        MKFSIIALLPLLAAVSA       1.700      17
8           SP_9        MKFSIIALLPLVAAVSA       1.727      17
9          SP_10        MKFSIIALLPLVAAVSA       1.733      17
10         SP_11        MKFSIIALLPLALAVSA       1.738      17
11         SP_12  MKFSIIALLPLAALVAASPTPDA       1.743      23
12         SP_13        MRFSIIALTLLPLAALA       1.754      17
13         SP_14        MKFSIIALLPLVAAVSA       1.761      17
14         SP_15       MKFSIIALLPLLAAAVSA       1.767      18
15         SP_16  MKFFTIIALMAPLAALAAPAPDA       1.769      23
16         SP_17        MKFSIIALTLLPLAALA       1.777      17
17         SP_18   MKFIALTLLPLAALVAAAPAPD       1.778      22
18         SP_19        MKFSIIALLPLALAVSA       1.780      17
19         SP_20       MRFINLALLLPLAALVSA       1.790      18
20         SP_21        MKFSIIALLPLVALVSA       1.796      17
21         SP_22        MRFSIIALLPLAALVSA       1.797      17
22         SP_23        MKFSIVALALLPLAAMA       1.805      17

                                                codon_optimized_sequences  \
0                     ATGAAGTTCAGCATCATTGCTCTTCTGCCTCTCGTCGCGGCCGTGTCCGCA
1      ATGAAGTTCTCCATCATTGCTCTCCTTCCTTTGGCAGCCCTGGTCGCCGCGGCTCCAGCACCCGAG
2                     ATGAAGTTCTCCATCATTGCTCTAACCCTTCTCCCTTTGGCGGCCCTGGCA
3                     ATGAAGTTCTCCATTATCGCTCTGCTTCCTCTCGCCTTGGGCGTCGTGGCA
4                     ATGCGCTTCAGCATTATCGCACTTTTGCCTCTGGCGGCTCTCGTCTCCGCC
5                     ATGAAGTTCACTCTTATCAACTTGCTGGCGCTCACCGCTGCCGTCTCCGCA
6                     ATGAAGTTCAGCATTATCGCTCTTCTGCCTCTCGCATTGGGCGTCTCCGCC
7                     ATGAAGTTCTCCATTATCGCACTCCTTCCTCTGTTGGCCGCTGTCAGCGCG
8                     ATGAAGTTCTCCATCATTGCACTGCTTCCTCTCGTCGCCGCTGTGAGCGCG
9                     ATGAAGTTCTCCATTATCGCACTTCTCCCTCTGGTCGCCGCTGTGAGCGCG
10                    ATGAAGTTCTCCATCATTGCACTGCTCCCTCTTGCTTTGGCGGTCAGCGCC
11  ATGAAGTTCTCCATCATTGCTTTGCTTCCTCTGGCGGCCCTCGTCGCTGCAAGCCCCACCCCAGATGCC
12                    ATGCGCTTCTCCATCATTGCACTCACCCTACTGCCTTTGGCTGCCCTTGCG
13                    ATGAAGTTCTCCATCATTGCTCTGCTTCCTCTCGTGGCCGCAGTCAGCGCG
14                 ATGAAGTTCAGCATCATTGCCTTGCTGCCTCTTCTCGCTGCAGCGGTCTCCGCC
15  ATGAAGTTCTTTACCATTATCGCTCTGATGGCTCCCCTTGCCGCACTCGCGGCGCCAGCCCCTGATGCA
16                    ATGAAGTTCTCCATTATCGCGCTTACCCTATTGCCTCTGGCCGCTCTCGCA
17     ATGAAGTTCATCGCTCTCACCCTGCTACCTCTTGCTGCCTTGGTCGCAGCCGCGCCAGCACCCGAT
18                    ATGAAGTTCAGCATTATCGCACTTCTGCCTCTCGCCTTGGCTGTCTCCGCG
19                 ATGCGCTTCATCAACCTTGCTTTGCTACTCCCTTTAGCGGCACTGGTCTCCGCC
20                    ATGAAGTTCAGCATTATCGCTCTGTTGCCTCTCGTCGCCCTTGTGTCCGCA
21                    ATGCGCTTCTCCATTATCGCGCTCTTGCCTCTGGCAGCCCTTGTCAGCGCT
22                    ATGAAGTTCTCCATCGTCGCGCTGGCTCTCTTGCCTCTTGCAGCCATGGCC

   sp_name
0     SP_1
1     SP_2
2     SP_3
3     SP_4
4     SP_5
5     SP_6
6     SP_7
7     SP_8
8     SP_9
9    SP_10
10   SP_11
11   SP_12
12   SP_13
13   SP_14
14   SP_15
15   SP_16
16   SP_17
17   SP_18
18   SP_19
19   SP_20
20   SP_21
21   SP_22
22   SP_23

In [15]:
final_sample

,SecretoGen_ID,Sequence,Perplexity,Length,codon_optimized_sequences,sp_name
0,SP_1,MKFSIIALLPLVAAVSA,1.612892,17,ATGAAGTTCAGCATCATTGCTCTTCTGCCTCTCGTCGCGGCCGTGT...,SP_1
1,SP_2,MKFSIIALLPLAALVAAAPAPE,1.630686,22,ATGAAGTTCTCCATCATTGCTCTCCTTCCTTTGGCAGCCCTGGTCG...,SP_2
2,SP_3,MKFSIIALTLLPLAALA,1.642188,17,ATGAAGTTCTCCATCATTGCTCTAACCCTTCTCCCTTTGGCGGCCC...,SP_3
3,SP_4,MKFSIIALLPLALGVVA,1.657314,17,ATGAAGTTCTCCATTATCGCTCTGCTTCCTCTCGCCTTGGGCGTCG...,SP_4
4,SP_5,MRFSIIALLPLAALVSA,1.692659,17,ATGCGCTTCAGCATTATCGCACTTTTGCCTCTGGCGGCTCTCGTCT...,SP_5
5,SP_6,MKFTLINLLALTAAVSA,1.693007,17,ATGAAGTTCACTCTTATCAACTTGCTGGCGCTCACCGCTGCCGTCT...,SP_6
6,SP_7,MKFSIIALLPLALGVSA,1.698680,17,ATGAAGTTCAGCATTATCGCTCTTCTGCCTCTCGCATTGGGCGTCT...,SP_7
7,SP_8,MKFSIIALLPLLAAVSA,1.699822,17,ATGAAGTTCTCCATTATCGCACTCCTTCCTCTGTTGGCCGCTGTCA...,SP_8
8,SP_9,MKFSIIALLPLVAAVSA,1.727175,17,ATGAAGTTCTCCATCATTGCACTGCTTCCTCTCGTCGCCGCTGTGA...,SP_9
9,SP_10,MKFSIIALLPLVAAVSA,1.732880,17,ATGAAGTTCTCCATTATCGCACTTCTCCCTCTGGTCGCCGCTGTGA...,SP_10
10,SP_11,MKFSIIALLPLALAVSA,1.737774,17,ATGAAGTTCTCCATCATTGCACTGCTCCCTCTTGCTTTGGCGGTCA...,SP_11
11,SP_12,MKFSIIALLPLAALVAASPTPDA,1.742775,23,ATGAAGTTCTCCATCATTGCTTTGCTTCCTCTGGCGGCCCTCGTCG...,SP_12
12,SP_13,MRFSIIALTLLPLAALA,1.754269,17,ATGCGCTTCTCCATCATTGCACTCACCCTACTGCCTTTGGCTGCCC...,SP_13
13,SP_14,MKFSIIALLPLVAAVSA,1.761043,17,ATGAAGTTCTCCATCATTGCTCTGCTTCCTCTCGTGGCCGCAGTCA...,SP_14
14,SP_15,MKFSIIALLPLLAAAVSA,1.767437,18,ATGAAGTTCAGCATCATTGCCTTGCTGCCTCTTCTCGCTGCAGCGG...,SP_15
15,SP_16,MKFFTIIALMAPLAALAAPAPDA,1.769435,23,ATGAAGTTCTTTACCATTATCGCTCTGATGGCTCCCCTTGCCGCAC...,SP_16
16,SP_17,MKFSIIALTLLPLAALA,1.777155,17,ATGAAGTTCTCCATTATCGCGCTTACCCTATTGCCTCTGGCCGCTC...,SP_17
17,SP_18,MKFIALTLLPLAALVAAAPAPD,1.778253,22,ATGAAGTTCATCGCTCTCACCCTGCTACCTCTTGCTGCCTTGGTCG...,SP_18
18,SP_19,MKFSIIALLPLALAVSA,1.780316,17,ATGAAGTTCAGCATTATCGCACTTCTGCCTCTCGCCTTGGCTGTCT...,SP_19
19,SP_20,MRFINLALLLPLAALVSA,1.790374,18,ATGCGCTTCATCAACCTTGCTTTGCTACTCCCTTTAGCGGCACTGG...,SP_20
20,SP_21,MKFSIIALLPLVALVSA,1.796229,17,ATGAAGTTCAGCATTATCGCTCTGTTGCCTCTCGTCGCCCTTGTGT...,SP_21
21,SP_22,MRFSIIALLPLAALVSA,1.796728,17,ATGCGCTTCTCCATTATCGCGCTCTTGCCTCTGGCAGCCCTTGTCA...,SP_22
22,SP_23,MKFSIVALALLPLAAMA,1.804731,17,ATGAAGTTCTCCATCGTCGCGCTGGCTCTCTTGCCTCTTGCAGCCA...,SP_23

# GEnerating primers

In [ ]:
RFP = Dseqrecord(SeqIO.read("../data/10_genetic_parts/parts/lysozyme.fasta", "fasta"))
pTef = Dseqrecord(SeqIO.read("../data/10_genetic_parts/parts/pTEF_w_A_homology.fasta", "fasta"))
print(f'The lenght of lysozyme is {len(RFP)}')
print(f'The lenght of pTef is {len(pTef)}')

The lenght of RFP is 384
The lenght of pTef is 1384

In [17]:
from pydna.amplify import pcr
from pydna.primer import Primer

In [ ]:
generic_pTef_fwd = Primer('CGAGACAGCAGAATCACCG') # generic 
generic_pTef_rev = Primer('GGTGAAGGTTGTGTTATGTTTTGTGG') # martis

generic_lyz_fwd = Primer('GTATTCGGCAGGTGTGAGC') # martis
generic_lyz_rev = Primer('CAGCCGGCAGCCGCGGATCC') # generic

## generating the overhangs

In [19]:
reverse_ovh_list = []
forward_ovh_list = []

for index, row in final_sample.iterrows():
    # get the sequence
    seq = str(row['codon_optimized_sequences'])

    # make the overhangs like marti propose: 
    # Forward
    fwd_ovh = seq[-44:] + generic_lyz_fwd
    fwd_ovh.name= f"{str(row['sp_name'])}_fwd"
    fwd_ovh.id = f"{str(row['sp_name'])}_fwd"

    # reverse
    rev_ovh = Seq(seq[:-14]).reverse_complement()+ generic_pTef_rev 
    rev_ovh.name = f"{str(row['sp_name'])}_rev"
    rev_ovh.id = f"{str(row['sp_name'])}_rev"


    forward_ovh_list.append(fwd_ovh)
    reverse_ovh_list.append(rev_ovh)

Amplicons

In [20]:
from pydna.amplify import pcr
from pydna.primer import Primer

pTef_amplicons = []
for i in range(len(reverse_ovh_list)): 
    amplicon = pcr(generic_pTef_fwd, reverse_ovh_list[i], pTef)
    pTef_amplicons.append(amplicon)

ValueError: No PCR product! Template pTef 1384 nt linear:
name anneals forward (--->) at 24
SP_1_rev anneals forward (--->) at 1384
No reverse primers anneal...

In [ ]:

RFP_amplicons = []
for i in range(len(forward_ovh_list)): 
    amplicon = pcr(forward_ovh_list[i], generic_lyz_rev, RFP)
    RFP_amplicons.append(amplicon)

# Testing the overlap

In [ ]:
id_names= final_sample['sp_name'].to_list()

In [ ]:
# changing the names of the amplicons
for i in range(len(pTef_amplicons)):
    pTef_amplicons[i].name =  f'pTef_{pTef_amplicons[i].name }_{id_names[i]}'
    
for i in range(len(RFP_amplicons)):
    RFP_amplicons[i].name =  f'RFP_{RFP_amplicons[i].name }_{id_names[i]}'

In [ ]:
from pydna.assembly import Assembly

In [ ]:
for i in range(len(RFP_amplicons)): 
    assemblyobj = Assembly([pTef_amplicons[i],RFP_amplicons[i]], limit = 18)
    contig = assemblyobj.assemble_linear()[0]

    print(contig.figure(), '\n')

pTef_923bp_PCR_prod_SP_1|30
                         \/
                         /\
                         30|RFP_428bp_PCR_prod_SP_1

pTef_938bp_PCR_prod_SP_2|30
                         \/
                         /\
                         30|RFP_428bp_PCR_prod_SP_2

pTef_923bp_PCR_prod_SP_3|30
                         \/
                         /\
                         30|RFP_428bp_PCR_prod_SP_3

pTef_923bp_PCR_prod_SP_4|30
                         \/
                         /\
                         30|RFP_428bp_PCR_prod_SP_4

pTef_923bp_PCR_prod_SP_5|30
                         \/
                         /\
                         30|RFP_428bp_PCR_prod_SP_5

pTef_923bp_PCR_prod_SP_6|30
                         \/
                         /\
                         30|RFP_428bp_PCR_prod_SP_6

pTef_923bp_PCR_prod_SP_7|30
                         \/
                         /\
                         30|RFP_428bp_PCR_prod_SP_7

pTef_923bp_PCR_prod_SP_8|30
                         \/
                         /\
                         30|RFP_428bp_PCR_prod_SP_8

pTef_923bp_PCR_prod_SP_9|30
                         \/
                         /\
                         30|RFP_428bp_PCR_prod_SP_9

pTef_923bp_PCR_prod_SP_10|30
                          \/
                          /\
                          30|RFP_428bp_PCR_prod_SP_10

pTef_923bp_PCR_prod_SP_11|30
                          \/
                          /\
                          30|RFP_428bp_PCR_prod_SP_11

pTef_941bp_PCR_prod_SP_12|30
                          \/
                          /\
                          30|RFP_428bp_PCR_prod_SP_12

pTef_923bp_PCR_prod_SP_13|30
                          \/
                          /\
                          30|RFP_428bp_PCR_prod_SP_13

pTef_923bp_PCR_prod_SP_14|30
                          \/
                          /\
                          30|RFP_428bp_PCR_prod_SP_14

pTef_926bp_PCR_prod_SP_15|30
                          \/
                          /\
                          30|RFP_428bp_PCR_prod_SP_15

pTef_941bp_PCR_prod_SP_16|30
                          \/
                          /\
                          30|RFP_428bp_PCR_prod_SP_16

pTef_923bp_PCR_prod_SP_17|30
                          \/
                          /\
                          30|RFP_428bp_PCR_prod_SP_17

pTef_938bp_PCR_prod_SP_18|30
                          \/
                          /\
                          30|RFP_428bp_PCR_prod_SP_18

pTef_923bp_PCR_prod_SP_19|30
                          \/
                          /\
                          30|RFP_428bp_PCR_prod_SP_19

pTef_926bp_PCR_prod_SP_20|30
                          \/
                          /\
                          30|RFP_428bp_PCR_prod_SP_20

pTef_923bp_PCR_prod_SP_21|30
                          \/
                          /\
                          30|RFP_428bp_PCR_prod_SP_21

pTef_923bp_PCR_prod_SP_22|30
                          \/
                          /\
                          30|RFP_428bp_PCR_prod_SP_22

pTef_923bp_PCR_prod_SP_23|30
                          \/
                          /\
                          30|RFP_428bp_PCR_prod_SP_23

In [ ]:
# changing the names of the amplicons
forward_primers = []
reverse_primers = []

for i in range(len(RFP_amplicons)):
    forward_primers.append(str(RFP_amplicons[i].forward_primer.seq))

for i in range(len(pTef_amplicons)):
    
    reverse_primers.append(str(pTef_amplicons[i].reverse_primer.seq))

In [ ]:
forward_ovh_list

[SP_1_fwd 63-mer:5'-TCAGCATCATTGCTC..AGC-3',
 SP_2_fwd 63-mer:5'-TCCTTCCTTTGGCAG..AGC-3',
 SP_3_fwd 63-mer:5'-TCTCCATCATTGCTC..AGC-3',
 SP_4_fwd 63-mer:5'-TCTCCATTATCGCTC..AGC-3',
 SP_5_fwd 63-mer:5'-TCAGCATTATCGCAC..AGC-3',
 SP_6_fwd 63-mer:5'-TCACTCTTATCAACT..AGC-3',
 SP_7_fwd 63-mer:5'-TCAGCATTATCGCTC..AGC-3',
 SP_8_fwd 63-mer:5'-TCTCCATTATCGCAC..AGC-3',
 SP_9_fwd 63-mer:5'-TCTCCATCATTGCAC..AGC-3',
 SP_10_fwd 63-mer:5'-TCTCCATTATCGCAC..AGC-3',
 SP_11_fwd 63-mer:5'-TCTCCATCATTGCAC..AGC-3',
 SP_12_fwd 63-mer:5'-TTCCTCTGGCGGCCC..AGC-3',
 SP_13_fwd 63-mer:5'-TCTCCATCATTGCAC..AGC-3',
 SP_14_fwd 63-mer:5'-TCTCCATCATTGCTC..AGC-3',
 SP_15_fwd 63-mer:5'-GCATCATTGCCTTGC..AGC-3',
 SP_16_fwd 63-mer:5'-TGATGGCTCCCCTTG..AGC-3',
 SP_17_fwd 63-mer:5'-TCTCCATTATCGCGC..AGC-3',
 SP_18_fwd 63-mer:5'-TGCTACCTCTTGCTG..AGC-3',
 SP_19_fwd 63-mer:5'-TCAGCATTATCGCAC..AGC-3',
 SP_20_fwd 63-mer:5'-TCAACCTTGCTTTGC..AGC-3',
 SP_21_fwd 63-mer:5'-TCAGCATTATCGCTC..AGC-3',
 SP_22_fwd 63-mer:5'-TCTCCATTATCGCGC..AGC-3',
 SP_23_fwd 63-mer:5'-TCTCCATCGTCGCGC..AGC-3']

In [ ]:
reverse_ovh_list

[SP_1_rev 63-mer:5'-CGACGAGAGGCAGAA..TGG-3',
 SP_2_rev 78-mer:5'-CCGCGGCGACCAGGG..TGG-3',
 SP_3_rev 63-mer:5'-AAGGGAGAAGGGTTA..TGG-3',
 SP_4_rev 63-mer:5'-AGGCGAGAGGAAGCA..TGG-3',
 SP_5_rev 63-mer:5'-CCGCCAGAGGCAAAA..TGG-3',
 SP_6_rev 63-mer:5'-CGGTGAGCGCCAGCA..TGG-3',
 SP_7_rev 63-mer:5'-ATGCGAGAGGCAGAA..TGG-3',
 SP_8_rev 63-mer:5'-CCAACAGAGGAAGGA..TGG-3',
 SP_9_rev 63-mer:5'-CGACGAGAGGAAGCA..TGG-3',
 SP_10_rev 63-mer:5'-CGACCAGAGGGAGAA..TGG-3',
 SP_11_rev 63-mer:5'-AAGCAAGAGGGAGCA..TGG-3',
 SP_12_rev 81-mer:5'-GGCTTGCAGCGACGA..TGG-3',
 SP_13_rev 63-mer:5'-AAGGCAGTAGGGTGA..TGG-3',
 SP_14_rev 63-mer:5'-CCACGAGAGGAAGCA..TGG-3',
 SP_15_rev 66-mer:5'-CAGCGAGAAGAGGCA..TGG-3',
 SP_16_rev 81-mer:5'-GCGCCGCGAGTGCGG..TGG-3',
 SP_17_rev 63-mer:5'-GAGGCAATAGGGTAA..TGG-3',
 SP_18_rev 78-mer:5'-CGGCTGCGACCAAGG..TGG-3',
 SP_19_rev 63-mer:5'-AGGCGAGAGGCAGAA..TGG-3',
 SP_20_rev 66-mer:5'-CCGCTAAAGGGAGTA..TGG-3',
 SP_21_rev 63-mer:5'-CGACGAGAGGCAACA..TGG-3',
 SP_22_rev 63-mer:5'-CTGCCAGAGGCAAGA..TGG-3',
 SP_23_rev 63-mer:5'-GAGGCAAGAGAGCCA..TGG-3']

In [ ]:
final_sample['fwd_primers(5-3)']= forward_primers
final_sample['rev_primers(5-3)']= reverse_primers
final_sample

/var/folders/2f/lw3sfzbs7l7f_q1knzbtbwrr0000gp/T/ipykernel_22736/2237364239.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_sample['fwd_primers(5-3)']= forward_primers
/var/folders/2f/lw3sfzbs7l7f_q1knzbtbwrr0000gp/T/ipykernel_22736/2237364239.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_sample['rev_primers(5-3)']= reverse_primers

,SecretoGen_ID,Sequence,Perplexity,Length,codon_optimized_sequences,sp_name,fwd_primers(5-3),rev_primers(5-3)
0,SP_1,MKFSIIALLPLVAAVSA,1.612892,17,ATGAAGTTCAGCATCATTGCTCTTCTGCCTCTCGTCGCGGCCGTGT...,SP_1,TCAGCATCATTGCTCTTCTGCCTCTCGTCGCGGCCGTGTCCGCAGT...,CGACGAGAGGCAGAAGAGCAATGATGCTGAACTTCATGGTGAAGGT...
1,SP_2,MKFSIIALLPLAALVAAAPAPE,1.630686,22,ATGAAGTTCTCCATCATTGCTCTCCTTCCTTTGGCAGCCCTGGTCG...,SP_2,TCCTTCCTTTGGCAGCCCTGGTCGCCGCGGCTCCAGCACCCGAGGT...,CCGCGGCGACCAGGGCTGCCAAAGGAAGGAGAGCAATGATGGAGAA...
2,SP_3,MKFSIIALTLLPLAALA,1.642188,17,ATGAAGTTCTCCATCATTGCTCTAACCCTTCTCCCTTTGGCGGCCC...,SP_3,TCTCCATCATTGCTCTAACCCTTCTCCCTTTGGCGGCCCTGGCAGT...,AAGGGAGAAGGGTTAGAGCAATGATGGAGAACTTCATGGTGAAGGT...
3,SP_4,MKFSIIALLPLALGVVA,1.657314,17,ATGAAGTTCTCCATTATCGCTCTGCTTCCTCTCGCCTTGGGCGTCG...,SP_4,TCTCCATTATCGCTCTGCTTCCTCTCGCCTTGGGCGTCGTGGCAGT...,AGGCGAGAGGAAGCAGAGCGATAATGGAGAACTTCATGGTGAAGGT...
4,SP_5,MRFSIIALLPLAALVSA,1.692659,17,ATGCGCTTCAGCATTATCGCACTTTTGCCTCTGGCGGCTCTCGTCT...,SP_5,TCAGCATTATCGCACTTTTGCCTCTGGCGGCTCTCGTCTCCGCCGT...,CCGCCAGAGGCAAAAGTGCGATAATGCTGAAGCGCATGGTGAAGGT...
5,SP_6,MKFTLINLLALTAAVSA,1.693007,17,ATGAAGTTCACTCTTATCAACTTGCTGGCGCTCACCGCTGCCGTCT...,SP_6,TCACTCTTATCAACTTGCTGGCGCTCACCGCTGCCGTCTCCGCAGT...,CGGTGAGCGCCAGCAAGTTGATAAGAGTGAACTTCATGGTGAAGGT...
6,SP_7,MKFSIIALLPLALGVSA,1.698680,17,ATGAAGTTCAGCATTATCGCTCTTCTGCCTCTCGCATTGGGCGTCT...,SP_7,TCAGCATTATCGCTCTTCTGCCTCTCGCATTGGGCGTCTCCGCCGT...,ATGCGAGAGGCAGAAGAGCGATAATGCTGAACTTCATGGTGAAGGT...
7,SP_8,MKFSIIALLPLLAAVSA,1.699822,17,ATGAAGTTCTCCATTATCGCACTCCTTCCTCTGTTGGCCGCTGTCA...,SP_8,TCTCCATTATCGCACTCCTTCCTCTGTTGGCCGCTGTCAGCGCGGT...,CCAACAGAGGAAGGAGTGCGATAATGGAGAACTTCATGGTGAAGGT...
8,SP_9,MKFSIIALLPLVAAVSA,1.727175,17,ATGAAGTTCTCCATCATTGCACTGCTTCCTCTCGTCGCCGCTGTGA...,SP_9,TCTCCATCATTGCACTGCTTCCTCTCGTCGCCGCTGTGAGCGCGGT...,CGACGAGAGGAAGCAGTGCAATGATGGAGAACTTCATGGTGAAGGT...
9,SP_10,MKFSIIALLPLVAAVSA,1.732880,17,ATGAAGTTCTCCATTATCGCACTTCTCCCTCTGGTCGCCGCTGTGA...,SP_10,TCTCCATTATCGCACTTCTCCCTCTGGTCGCCGCTGTGAGCGCGGT...,CGACCAGAGGGAGAAGTGCGATAATGGAGAACTTCATGGTGAAGGT...
10,SP_11,MKFSIIALLPLALAVSA,1.737774,17,ATGAAGTTCTCCATCATTGCACTGCTCCCTCTTGCTTTGGCGGTCA...,SP_11,TCTCCATCATTGCACTGCTCCCTCTTGCTTTGGCGGTCAGCGCCGT...,AAGCAAGAGGGAGCAGTGCAATGATGGAGAACTTCATGGTGAAGGT...
11,SP_12,MKFSIIALLPLAALVAASPTPDA,1.742775,23,ATGAAGTTCTCCATCATTGCTTTGCTTCCTCTGGCGGCCCTCGTCG...,SP_12,TTCCTCTGGCGGCCCTCGTCGCTGCAAGCCCCACCCCAGATGCCGT...,GGCTTGCAGCGACGAGGGCCGCCAGAGGAAGCAAAGCAATGATGGA...
12,SP_13,MRFSIIALTLLPLAALA,1.754269,17,ATGCGCTTCTCCATCATTGCACTCACCCTACTGCCTTTGGCTGCCC...,SP_13,TCTCCATCATTGCACTCACCCTACTGCCTTTGGCTGCCCTTGCGGT...,AAGGCAGTAGGGTGAGTGCAATGATGGAGAAGCGCATGGTGAAGGT...
13,SP_14,MKFSIIALLPLVAAVSA,1.761043,17,ATGAAGTTCTCCATCATTGCTCTGCTTCCTCTCGTGGCCGCAGTCA...,SP_14,TCTCCATCATTGCTCTGCTTCCTCTCGTGGCCGCAGTCAGCGCGGT...,CCACGAGAGGAAGCAGAGCAATGATGGAGAACTTCATGGTGAAGGT...
14,SP_15,MKFSIIALLPLLAAAVSA,1.767437,18,ATGAAGTTCAGCATCATTGCCTTGCTGCCTCTTCTCGCTGCAGCGG...,SP_15,GCATCATTGCCTTGCTGCCTCTTCTCGCTGCAGCGGTCTCCGCCGT...,CAGCGAGAAGAGGCAGCAAGGCAATGATGCTGAACTTCATGGTGAA...
15,SP_16,MKFFTIIALMAPLAALAAPAPDA,1.769435,23,ATGAAGTTCTTTACCATTATCGCTCTGATGGCTCCCCTTGCCGCAC...,SP_16,TGATGGCTCCCCTTGCCGCACTCGCGGCGCCAGCCCCTGATGCAGT...,GCGCCGCGAGTGCGGCAAGGGGAGCCATCAGAGCGATAATGGTAAA...
16,SP_17,MKFSIIALTLLPLAALA,1.777155,17,ATGAAGTTCTCCATTATCGCGCTTACCCTATTGCCTCTGGCCGCTC...,SP_17,TCTCCATTATCGCGCTTACCCTATTGCCTCTGGCCGCTCTCGCAGT...,GAGGCAATAGGGTAAGCGCGATAATGGAGAACTTCATGGTGAAGGT...
17,SP_18,MKFIALTLLPLAALVAAAPAPD,1.778253,22,ATGAAGTTCATCGCTCTCACCCTGCTACCTCTTGCTGCCTTGGTCG...,SP_18,TGCTACCTCTTGCTGCCTTGGTCGCAGCCGCGCCAGCACCCGATGT...,CGGCTGCGACCAAGGCAGCAAGAGGTAGCAGGGTGAGAGCGATGAA...
18,SP_19,MKFSIIALLPLALAVSA,1.780316,17,ATGAAGTTCAGCATTATCGCACTTCTGCCTCTCGCCTTGGCTGTCT...,SP_19,TCAGCATTATCGCACTTCTGCCTCTCGCCTTGGCTGTCTCCGCGGT...,AGGCGAGAGGCAGAAGTGCGATAATGCTGAACTTCATGGTGAAGGT...
19,SP_20,MRFINLALLLPLAALVSA,1.790374,18,ATGCGCTTCATCAACCTTGCTTTGCTACTCCCTTTAGCGGCACTGG...,SP_20,TCAACCTTGCTTTGCTACTCCCTTTAGCGGCACTGGTCTCCGCCGT...,CCGCTAAAGGGAGTAGCAAAGCAAGGTTGATGAAGCGCATGGTGAA...
20,SP_21,MKFSIIALLPLVALVSA,1.796229,17,ATGAAGTTCAGCATTATCGCTCTGTTGCCTCTCGTCGCCCTTGTGT...,SP_21,TCAGCATTATCGCTCTGTTGCCTCTCGTCGCCCTTGTGTCCGCAGT...,CGACGAGAGGCAACAGAGCGATAATGCTGAACTTCATGGTGAAGGT...
21,SP_22,MRFSIIALLPLAALVSA,1.796728,17,ATGCGCTTCTCCATTATCGCGCTCTTGCCTCTGGCAGCCCTTGTCA...,SP_22,TCTCCATTATCGCGCTCTTGCCTCTGGCAGCCCTTGTCAGCGCTGT...,CTGCCAGAGGCAAGAGCGCGATAATGGAGAAGCGCATGGTGAAGGT...
22,SP_23,MKFSIVALALLPLAAMA,1.804731,17,ATGAAGTTCTCCATCGTCGCGCTGGCTCTCTTGCCTCTTGCAGCCA...,SP_23,TCTCCATCGTCGCGCTGGCTCTCTTGCCTCTTGCAGCCATGGCCGT...,GAGGCAAGAGAGCCAGCGCGACGATGGAGAACTTCATGGTGAAGGT...

For IDT:

In [ ]:
fwd_name = [seq.name for seq in forward_ovh_list]
fwd_seq = [str(seq.seq) for seq in forward_ovh_list]

rev_name = [seq.name for seq in reverse_ovh_list]
rev_seq = [str(seq.seq) for seq in reverse_ovh_list]

In [ ]:
forward_primers_well_plate = pd.read_excel('../data/example_plate-file-upload (1).xls')[:23]
forward_primers_well_plate['Name'] = fwd_name
forward_primers_well_plate['Sequence'] = fwd_seq

forward_primers_well_plate

   Well Position       Name                                           Sequence
0             A1   SP_1_fwd  TCAGCATCATTGCTCTTCTGCCTCTCGTCGCGGCCGTGTCCGCAGT...
1             A2   SP_2_fwd  TCCTTCCTTTGGCAGCCCTGGTCGCCGCGGCTCCAGCACCCGAGGT...
2             A3   SP_3_fwd  TCTCCATCATTGCTCTAACCCTTCTCCCTTTGGCGGCCCTGGCAGT...
3             A4   SP_4_fwd  TCTCCATTATCGCTCTGCTTCCTCTCGCCTTGGGCGTCGTGGCAGT...
4             A5   SP_5_fwd  TCAGCATTATCGCACTTTTGCCTCTGGCGGCTCTCGTCTCCGCCGT...
5             A6   SP_6_fwd  TCACTCTTATCAACTTGCTGGCGCTCACCGCTGCCGTCTCCGCAGT...
6             A7   SP_7_fwd  TCAGCATTATCGCTCTTCTGCCTCTCGCATTGGGCGTCTCCGCCGT...
7             A8   SP_8_fwd  TCTCCATTATCGCACTCCTTCCTCTGTTGGCCGCTGTCAGCGCGGT...
8             A9   SP_9_fwd  TCTCCATCATTGCACTGCTTCCTCTCGTCGCCGCTGTGAGCGCGGT...
9            A10  SP_10_fwd  TCTCCATTATCGCACTTCTCCCTCTGGTCGCCGCTGTGAGCGCGGT...
10           A11  SP_11_fwd  TCTCCATCATTGCACTGCTCCCTCTTGCTTTGGCGGTCAGCGCCGT...
11           A12  SP_12_fwd  TTCCTCTGGCGGCCCTCGTCGCTGCAAGCCCCACCCCAGATGCCGT...
12            B1  SP_13_fwd  TCTCCATCATTGCACTCACCCTACTGCCTTTGGCTGCCCTTGCGGT...
13            B2  SP_14_fwd  TCTCCATCATTGCTCTGCTTCCTCTCGTGGCCGCAGTCAGCGCGGT...
14            B3  SP_15_fwd  GCATCATTGCCTTGCTGCCTCTTCTCGCTGCAGCGGTCTCCGCCGT...
15            B4  SP_16_fwd  TGATGGCTCCCCTTGCCGCACTCGCGGCGCCAGCCCCTGATGCAGT...
16            B5  SP_17_fwd  TCTCCATTATCGCGCTTACCCTATTGCCTCTGGCCGCTCTCGCAGT...
17            B6  SP_18_fwd  TGCTACCTCTTGCTGCCTTGGTCGCAGCCGCGCCAGCACCCGATGT...
18            B7  SP_19_fwd  TCAGCATTATCGCACTTCTGCCTCTCGCCTTGGCTGTCTCCGCGGT...
19            B8  SP_20_fwd  TCAACCTTGCTTTGCTACTCCCTTTAGCGGCACTGGTCTCCGCCGT...
20            B9  SP_21_fwd  TCAGCATTATCGCTCTGTTGCCTCTCGTCGCCCTTGTGTCCGCAGT...
21           B10  SP_22_fwd  TCTCCATTATCGCGCTCTTGCCTCTGGCAGCCCTTGTCAGCGCTGT...
22           B11  SP_23_fwd  TCTCCATCGTCGCGCTGGCTCTCTTGCCTCTTGCAGCCATGGCCGT...

In [ ]:
reverse_primers_well_plate = pd.read_excel('../data/example_plate-file-upload (1).xls')[:23]
reverse_primers_well_plate['Name'] = rev_name
reverse_primers_well_plate['Sequence'] = rev_seq

reverse_primers_well_plate

   Well Position       Name                                           Sequence
0             A1   SP_1_rev  CGACGAGAGGCAGAAGAGCAATGATGCTGAACTTCATGGTGAAGGT...
1             A2   SP_2_rev  CCGCGGCGACCAGGGCTGCCAAAGGAAGGAGAGCAATGATGGAGAA...
2             A3   SP_3_rev  AAGGGAGAAGGGTTAGAGCAATGATGGAGAACTTCATGGTGAAGGT...
3             A4   SP_4_rev  AGGCGAGAGGAAGCAGAGCGATAATGGAGAACTTCATGGTGAAGGT...
4             A5   SP_5_rev  CCGCCAGAGGCAAAAGTGCGATAATGCTGAAGCGCATGGTGAAGGT...
5             A6   SP_6_rev  CGGTGAGCGCCAGCAAGTTGATAAGAGTGAACTTCATGGTGAAGGT...
6             A7   SP_7_rev  ATGCGAGAGGCAGAAGAGCGATAATGCTGAACTTCATGGTGAAGGT...
7             A8   SP_8_rev  CCAACAGAGGAAGGAGTGCGATAATGGAGAACTTCATGGTGAAGGT...
8             A9   SP_9_rev  CGACGAGAGGAAGCAGTGCAATGATGGAGAACTTCATGGTGAAGGT...
9            A10  SP_10_rev  CGACCAGAGGGAGAAGTGCGATAATGGAGAACTTCATGGTGAAGGT...
10           A11  SP_11_rev  AAGCAAGAGGGAGCAGTGCAATGATGGAGAACTTCATGGTGAAGGT...
11           A12  SP_12_rev  GGCTTGCAGCGACGAGGGCCGCCAGAGGAAGCAAAGCAATGATGGA...
12            B1  SP_13_rev  AAGGCAGTAGGGTGAGTGCAATGATGGAGAAGCGCATGGTGAAGGT...
13            B2  SP_14_rev  CCACGAGAGGAAGCAGAGCAATGATGGAGAACTTCATGGTGAAGGT...
14            B3  SP_15_rev  CAGCGAGAAGAGGCAGCAAGGCAATGATGCTGAACTTCATGGTGAA...
15            B4  SP_16_rev  GCGCCGCGAGTGCGGCAAGGGGAGCCATCAGAGCGATAATGGTAAA...
16            B5  SP_17_rev  GAGGCAATAGGGTAAGCGCGATAATGGAGAACTTCATGGTGAAGGT...
17            B6  SP_18_rev  CGGCTGCGACCAAGGCAGCAAGAGGTAGCAGGGTGAGAGCGATGAA...
18            B7  SP_19_rev  AGGCGAGAGGCAGAAGTGCGATAATGCTGAACTTCATGGTGAAGGT...
19            B8  SP_20_rev  CCGCTAAAGGGAGTAGCAAAGCAAGGTTGATGAAGCGCATGGTGAA...
20            B9  SP_21_rev  CGACGAGAGGCAACAGAGCGATAATGCTGAACTTCATGGTGAAGGT...
21           B10  SP_22_rev  CTGCCAGAGGCAAGAGCGCGATAATGGAGAAGCGCATGGTGAAGGT...
22           B11  SP_23_rev  GAGGCAAGAGAGCCAGCGCGACGATGGAGAACTTCATGGTGAAGGT...

In [ ]:
forward_primers_well_plate.to_excel('../data/09_primers/forward_primers_2026_29_01.xlsx')
reverse_primers_well_plate.to_excel('../data/09_primers/forward_primers_2026_29_01.xlsx')
final_sample.to_excel('../data/09_primers/lysozyme_primers_2026_29_01.xlsx')

In [ ]:
final_sample

,SecretoGen_ID,Sequence,Perplexity,Length,codon_optimized_sequences,sp_name,fwd_primers(5-3),rev_primers(5-3)
0,SP_1,MKFSIIALLPLVAAVSA,1.612892,17,ATGAAGTTCAGCATCATTGCTCTTCTGCCTCTCGTCGCGGCCGTGT...,SP_1,TCAGCATCATTGCTCTTCTGCCTCTCGTCGCGGCCGTGTCCGCAGT...,CGACGAGAGGCAGAAGAGCAATGATGCTGAACTTCATGGTGAAGGT...
1,SP_2,MKFSIIALLPLAALVAAAPAPE,1.630686,22,ATGAAGTTCTCCATCATTGCTCTCCTTCCTTTGGCAGCCCTGGTCG...,SP_2,TCCTTCCTTTGGCAGCCCTGGTCGCCGCGGCTCCAGCACCCGAGGT...,CCGCGGCGACCAGGGCTGCCAAAGGAAGGAGAGCAATGATGGAGAA...
2,SP_3,MKFSIIALTLLPLAALA,1.642188,17,ATGAAGTTCTCCATCATTGCTCTAACCCTTCTCCCTTTGGCGGCCC...,SP_3,TCTCCATCATTGCTCTAACCCTTCTCCCTTTGGCGGCCCTGGCAGT...,AAGGGAGAAGGGTTAGAGCAATGATGGAGAACTTCATGGTGAAGGT...
3,SP_4,MKFSIIALLPLALGVVA,1.657314,17,ATGAAGTTCTCCATTATCGCTCTGCTTCCTCTCGCCTTGGGCGTCG...,SP_4,TCTCCATTATCGCTCTGCTTCCTCTCGCCTTGGGCGTCGTGGCAGT...,AGGCGAGAGGAAGCAGAGCGATAATGGAGAACTTCATGGTGAAGGT...
4,SP_5,MRFSIIALLPLAALVSA,1.692659,17,ATGCGCTTCAGCATTATCGCACTTTTGCCTCTGGCGGCTCTCGTCT...,SP_5,TCAGCATTATCGCACTTTTGCCTCTGGCGGCTCTCGTCTCCGCCGT...,CCGCCAGAGGCAAAAGTGCGATAATGCTGAAGCGCATGGTGAAGGT...
5,SP_6,MKFTLINLLALTAAVSA,1.693007,17,ATGAAGTTCACTCTTATCAACTTGCTGGCGCTCACCGCTGCCGTCT...,SP_6,TCACTCTTATCAACTTGCTGGCGCTCACCGCTGCCGTCTCCGCAGT...,CGGTGAGCGCCAGCAAGTTGATAAGAGTGAACTTCATGGTGAAGGT...
6,SP_7,MKFSIIALLPLALGVSA,1.698680,17,ATGAAGTTCAGCATTATCGCTCTTCTGCCTCTCGCATTGGGCGTCT...,SP_7,TCAGCATTATCGCTCTTCTGCCTCTCGCATTGGGCGTCTCCGCCGT...,ATGCGAGAGGCAGAAGAGCGATAATGCTGAACTTCATGGTGAAGGT...
7,SP_8,MKFSIIALLPLLAAVSA,1.699822,17,ATGAAGTTCTCCATTATCGCACTCCTTCCTCTGTTGGCCGCTGTCA...,SP_8,TCTCCATTATCGCACTCCTTCCTCTGTTGGCCGCTGTCAGCGCGGT...,CCAACAGAGGAAGGAGTGCGATAATGGAGAACTTCATGGTGAAGGT...
8,SP_9,MKFSIIALLPLVAAVSA,1.727175,17,ATGAAGTTCTCCATCATTGCACTGCTTCCTCTCGTCGCCGCTGTGA...,SP_9,TCTCCATCATTGCACTGCTTCCTCTCGTCGCCGCTGTGAGCGCGGT...,CGACGAGAGGAAGCAGTGCAATGATGGAGAACTTCATGGTGAAGGT...
9,SP_10,MKFSIIALLPLVAAVSA,1.732880,17,ATGAAGTTCTCCATTATCGCACTTCTCCCTCTGGTCGCCGCTGTGA...,SP_10,TCTCCATTATCGCACTTCTCCCTCTGGTCGCCGCTGTGAGCGCGGT...,CGACCAGAGGGAGAAGTGCGATAATGGAGAACTTCATGGTGAAGGT...
10,SP_11,MKFSIIALLPLALAVSA,1.737774,17,ATGAAGTTCTCCATCATTGCACTGCTCCCTCTTGCTTTGGCGGTCA...,SP_11,TCTCCATCATTGCACTGCTCCCTCTTGCTTTGGCGGTCAGCGCCGT...,AAGCAAGAGGGAGCAGTGCAATGATGGAGAACTTCATGGTGAAGGT...
11,SP_12,MKFSIIALLPLAALVAASPTPDA,1.742775,23,ATGAAGTTCTCCATCATTGCTTTGCTTCCTCTGGCGGCCCTCGTCG...,SP_12,TTCCTCTGGCGGCCCTCGTCGCTGCAAGCCCCACCCCAGATGCCGT...,GGCTTGCAGCGACGAGGGCCGCCAGAGGAAGCAAAGCAATGATGGA...
12,SP_13,MRFSIIALTLLPLAALA,1.754269,17,ATGCGCTTCTCCATCATTGCACTCACCCTACTGCCTTTGGCTGCCC...,SP_13,TCTCCATCATTGCACTCACCCTACTGCCTTTGGCTGCCCTTGCGGT...,AAGGCAGTAGGGTGAGTGCAATGATGGAGAAGCGCATGGTGAAGGT...
13,SP_14,MKFSIIALLPLVAAVSA,1.761043,17,ATGAAGTTCTCCATCATTGCTCTGCTTCCTCTCGTGGCCGCAGTCA...,SP_14,TCTCCATCATTGCTCTGCTTCCTCTCGTGGCCGCAGTCAGCGCGGT...,CCACGAGAGGAAGCAGAGCAATGATGGAGAACTTCATGGTGAAGGT...
14,SP_15,MKFSIIALLPLLAAAVSA,1.767437,18,ATGAAGTTCAGCATCATTGCCTTGCTGCCTCTTCTCGCTGCAGCGG...,SP_15,GCATCATTGCCTTGCTGCCTCTTCTCGCTGCAGCGGTCTCCGCCGT...,CAGCGAGAAGAGGCAGCAAGGCAATGATGCTGAACTTCATGGTGAA...
15,SP_16,MKFFTIIALMAPLAALAAPAPDA,1.769435,23,ATGAAGTTCTTTACCATTATCGCTCTGATGGCTCCCCTTGCCGCAC...,SP_16,TGATGGCTCCCCTTGCCGCACTCGCGGCGCCAGCCCCTGATGCAGT...,GCGCCGCGAGTGCGGCAAGGGGAGCCATCAGAGCGATAATGGTAAA...
16,SP_17,MKFSIIALTLLPLAALA,1.777155,17,ATGAAGTTCTCCATTATCGCGCTTACCCTATTGCCTCTGGCCGCTC...,SP_17,TCTCCATTATCGCGCTTACCCTATTGCCTCTGGCCGCTCTCGCAGT...,GAGGCAATAGGGTAAGCGCGATAATGGAGAACTTCATGGTGAAGGT...
17,SP_18,MKFIALTLLPLAALVAAAPAPD,1.778253,22,ATGAAGTTCATCGCTCTCACCCTGCTACCTCTTGCTGCCTTGGTCG...,SP_18,TGCTACCTCTTGCTGCCTTGGTCGCAGCCGCGCCAGCACCCGATGT...,CGGCTGCGACCAAGGCAGCAAGAGGTAGCAGGGTGAGAGCGATGAA...
18,SP_19,MKFSIIALLPLALAVSA,1.780316,17,ATGAAGTTCAGCATTATCGCACTTCTGCCTCTCGCCTTGGCTGTCT...,SP_19,TCAGCATTATCGCACTTCTGCCTCTCGCCTTGGCTGTCTCCGCGGT...,AGGCGAGAGGCAGAAGTGCGATAATGCTGAACTTCATGGTGAAGGT...
19,SP_20,MRFINLALLLPLAALVSA,1.790374,18,ATGCGCTTCATCAACCTTGCTTTGCTACTCCCTTTAGCGGCACTGG...,SP_20,TCAACCTTGCTTTGCTACTCCCTTTAGCGGCACTGGTCTCCGCCGT...,CCGCTAAAGGGAGTAGCAAAGCAAGGTTGATGAAGCGCATGGTGAA...
20,SP_21,MKFSIIALLPLVALVSA,1.796229,17,ATGAAGTTCAGCATTATCGCTCTGTTGCCTCTCGTCGCCCTTGTGT...,SP_21,TCAGCATTATCGCTCTGTTGCCTCTCGTCGCCCTTGTGTCCGCAGT...,CGACGAGAGGCAACAGAGCGATAATGCTGAACTTCATGGTGAAGGT...
21,SP_22,MRFSIIALLPLAALVSA,1.796728,17,ATGCGCTTCTCCATTATCGCGCTCTTGCCTCTGGCAGCCCTTGTCA...,SP_22,TCTCCATTATCGCGCTCTTGCCTCTGGCAGCCCTTGTCAGCGCTGT...,CTGCCAGAGGCAAGAGCGCGATAATGGAGAAGCGCATGGTGAAGGT...
22,SP_23,MKFSIVALALLPLAAMA,1.804731,17,ATGAAGTTCTCCATCGTCGCGCTGGCTCTCTTGCCTCTTGCAGCCA...,SP_23,TCTCCATCGTCGCGCTGGCTCTCTTGCCTCTTGCAGCCATGGCCGT...,GAGGCAAGAGAGCCAGCGCGACGATGGAGAACTTCATGGTGAAGGT...